### ISSUE TITLE
Error when creating a static Excel file as query output

### ISSUE THREAD

**Issue by juaneochoa** [DaxStudio/DaxStudio#946] opened 2022-09-19 14:51 UTC
DAX Studio v3.0.0.725
Connection: PowerBIDesktop - 16.0.44.29

## Summary of Issue
Query runs properly when displaying output on table or writing a CSV file. When writing a static Excel file is throws the following error: 

The type initializer for 'PerTypeValues'1' threw an exception.

No further indications on what the error might by

## Steps to Reproduce
1.SQL query that produces ~300k records
2.Show output on table. Output is properly displayed
3.Set output as CSV file: csv file created properly
4.Set output as Excel static: get error message above.

**Comment by CharlieMather** [comment] 2022-09-20 17:40
I am receiving the same error when saving results to a static Excel file.

**Comment by dgosbell** [comment] 2022-09-22 00:21
This is a duplicate of #891 so I'm going to close this as I'm tracking this issue there. You can subscribe to that issue to get notified of updates

**Closed by dgosbell** 2022-09-22 00:21 UTC
