### ISSUE TITLE
Bad "Learn More" Link - Metric Options

### ISSUE THREAD

**Issue by bgribaudo** [DaxStudio/DaxStudio#1295] opened 2024-08-19 14:32 UTC
**Describe the bug**
Bad "learn more" link. 

**To Reproduce**
1. In DAX Studio 3.2.0, ribbon tab _Advanced_, click _View Metrics_.
2. In the _Metric Options_ dialog that is displayed, click _Learn More_.
3. Browser window opens that attempts to access http://localhost:3000/docs/features/model-metrics/#metric-options-dialog. An "unable to connect" error is reported.

![image](https://github.com/user-attachments/assets/3cb8dcd4-192e-4e83-80a3-9573f26d25f7)

**Expected behavior**
"Learn more" page should open.

**Comment by dgosbell** [comment] 2024-08-19 23:15
This is a duplicate of #1293 so I'm closing this issue as I'm tracking the fix against the earlier bug

**Closed by dgosbell** 2024-08-19 23:15 UTC
Labels: triage
