### ISSUE TITLE
excel2016中加载dax studio出错

### ISSUE THREAD

**Issue by dqaudithillstone** [DaxStudio/DaxStudio#225] opened 2019-09-29 08:31 UTC
Version =  v0.0.0.0

Checking Operating System
=======================
    OSCaption       = Microsoft Windows 7 专业版 
    OSVersion       = 6.1.7601
    OSArchitecture  = 64-bit
    VisibleMemoryGB = 7.93
    FreeMemoryGB    = 3.81

    Culture Name              = zh-CN
    Culture DisplayName       = 中文(简体，中国)
    Culture EnglishName       = Chinese (Simplified, PRC)
    Culture 2-Letter ISO Name = zh
    Culture DecimalSeparator  = .
    Culture GroupSeparator    = ,
    Culture CurrencySymbol    = ¥
    Culture ShortDatePattern  = yyyy-M-d

Checking .Net Framework
=======================
    v2.0.50727 -> 2.0.50727.5420
    v2.0.50727\2052 -> 2.0.50727.5420
    v3.0 -> 3.0.30729.5420
    v3.0\Setup -> 3.0.30729.5420
    v3.0\Setup\2052 -> 3.0.30729.5420
    v3.0\Setup\Windows Communication Foundation -> 3.0.4506.5420
    v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.5011
    v3.5 -> 3.5.30729.5420
    v3.5\2052 -> 3.5.30729.5420
    v4\Client -> 4.7.02558
    v4\Client\1033 -> 4.7.02558
    v4\Client\2052 -> 4.6.00081
    v4\Full -> 4.7.02558
    v4\Full\1033 -> 4.7.02558
    v4\Full\2052 -> 4.6.00081
    v4.0\Client -> 4.0.0.0

Checking AMO (Local)
=======================
    Attempting to load: C:\Program Files\DAX Studio\bin\Microsoft.AnalysisServices.dll
    FAIL > 系统找不到指定的文件。 (异常来自 HRESULT:0x80070002)
    PASS > Microsoft.AnalysisServices, Version=18.0.5.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
           C:\Program Files\DAX Studio\Microsoft.AnalysisServices.dll

Checking ADOMD.NET (Local)
=======================
    Attempting to load: C:\Program Files\DAX Studio\bin\Microsoft.AnalysisServices.AdomdClient.dll
    FAIL > 系统找不到指定的文件。 (异常来自 HRESULT:0x80070002)
    PASS > Microsoft.AnalysisServices.AdomdClient, Version=18.0.5.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
           C:\Program Files\DAX Studio\Microsoft.AnalysisServices.AdomdClient.dll

Checking AMO (GAC)
=======================
    FAIL > 未能加载文件或程序集“Microsoft.AnalysisServices, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)
    PASS > Microsoft.AnalysisServices, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
           C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.AnalysisServices\v4.0_14.0.0.0__89845dcd8080cc91\Microsoft.AnalysisServices.dll
    WARN > 未能加载文件或程序集“Microsoft.AnalysisServices, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)

Checking ADOMD.NET (GAC)
=======================
    FAIL > 未能加载文件或程序集“Microsoft.AnalysisServices.AdomdClient, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)
    PASS > Microsoft.AnalysisServices.AdomdClient, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
           C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.AnalysisServices.AdomdClient\v4.0_14.0.0.0__89845dcd8080cc91\Microsoft.AnalysisServices.AdomdClient.dll
    WARN > 未能加载文件或程序集“Microsoft.AnalysisServices.AdomdClient, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)

Dax Studio Configuration
========================
    Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
    Processing DaxStudio.exe.config file...
    Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
    Bindings Found: 14
    AMO : 18.0.5.0
    ADOMD : <default>

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excel_v16
    Excel Path: D:\PROGRA~1\MICROS~1\Office16\EXCEL.EXE
    Excel Architecture: x64

    DAX Studio Excel Add-in Registry keys
       Description: Dax Studio Excel Add-In
       FriendlyName: Dax Studio Excel Add-In
       Manifest: file:///C:/Program Files/DAX Studio/DaxStudio.vsto|vstolocal
       LoadBehavior: 3

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      PASS > No Disabled items found.

      PASS >  Found Excel Addin: Microsoft Power Pivot for Excel

    Attempting to load Excel Add-in: 
      PASS > Loaded Excel Add-in: DaxStudio, Version=2.9.4.133, Culture=neutral, PublicKeyToken=null

    Checking VSTO Configuration
    Architecture: x64
      v2.0.50727
        Install 1
        SP 0
        MSI 1
        Update 1
      v4
        Version 10.0.31129
        Install 1
        InstallerPath C:\Program Files\Common Files\Microsoft Shared\VSTO\10.0\VSTOInstaller.exe
      v4M
        VSTOMFeature_UNM 1
        VSTOMFeature_CLR35 1
        VSTOMFeature_CLR40 1
      v4M_2052
        VSTOM_res_UNM 1
        VSTOM_res_CLR35 1
        VSTOM_res_CLR40 1

**Comment by dgosbell** [comment] 2019-09-29 12:08
Do you have a question or issue?

**Comment by dqaudithillstone** [comment] 2019-09-30 03:48
怎么解决这个错误呀，用Excel 打不开dax studio

**Comment by dgosbell** [comment] 2019-09-30 06:20
So according to google translate your previous comment is:
_How to solve this error, can't open dax studio with Excel_

So in the output you posted from DAX Studio Checker everything looks normal.

What error message are you getting? 

Can you see the DAX Studio button on the Addins ribbon?

Did you have an Excel file open that contains a Power Pivot model?

Can you post a screenshot of the error you are seeing?

**Comment by FrankPXG** [comment] 2019-10-08 00:16
Dear Gosbell, 
I met same issue. DAX Studio button is visible on the Addins ribbon, and Power Pivot Model is available also. (DAX Studio works fine when link to PowerBI file, but not works via. Excel Addins.).  
The screenshot as following:
![image](https://user-images.githubusercontent.com/56281564/66358072-f02e0680-e9a3-11e9-9948-e6e92b9e004b.png)

**Comment by dgosbell** [comment] 2019-10-08 00:33
@FrankPXG - we don't really know if this is the same issue or not as there is not information in the original report. So your issue could be entirely different. 

Can you try capturing some debug logs using the steps outlined [here] (https://daxstudio.org/documentation/troubleshooting/logging-settings/) and then attaching those logs to this issue? (note: you need to make sure all copies of Excel are closed as we only check for the shift key when the add-in is first loaded)

**Comment by FrankPXG** [comment] 2019-10-08 03:52
Dear Gosbell,
Highly appreciated for your quick checking, and It's so nice of you.
(It should be same issue with dqaudithillstone).

I started up Excel with pushing left "Shift" Key. And it's still with same problem -- cannot start up Studio from Excel Addin. The information below is: 1) information from DAX Studio Checker (and sorry that some Chinese word in this checker information), 2) Information from DAX Studio Excel Log. 
1)   from Checker
  Version =  v0.0.0.0

Checking Operating System
=======================
    OSCaption       = Microsoft Windows 10 家庭中文版
    OSVersion       = 10.0.18362
    OSArchitecture  = 64 位
    VisibleMemoryGB = 7.85
    FreeMemoryGB    = 4.61

    Culture Name              = zh-CN
    Culture DisplayName       = 中文(简体，中国)
    Culture EnglishName       = Chinese (Simplified, China)
    Culture 2-Letter ISO Name = zh
    Culture DecimalSeparator  = .
    Culture GroupSeparator    = ,
    Culture CurrencySymbol    = ¥
    Culture ShortDatePattern  = yyyy/M/d

Checking .Net Framework
=======================
    v2.0.50727 -> 2.0.50727.4927
    v2.0.50727\2052 -> 2.0.50727.4927
    v3.0 -> 3.0.30729.4926
    v3.0\Setup -> 3.0.30729.4926
    v3.0\Setup\2052 -> 3.0.30729.8795
    v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
    v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
    v3.5 -> 3.5.30729.4926
    v3.5\2052 -> 3.5.30729.5003
    v4\Client -> 4.8.03752
    v4\Client\1033 -> 4.8.03752
    v4\Client\2052 -> 4.8.03752
    v4\Full -> 4.8.03752
    v4\Full\1033 -> 4.8.03752
    v4\Full\2052 -> 4.8.03752
    v4.0\Client -> 4.0.0.0

Checking AMO (Local)
=======================
    Attempting to load: C:\Program Files\DAX Studio\bin\Microsoft.AnalysisServices.dll
    FAIL > 系统找不到指定的文件。 (异常来自 HRESULT:0x80070002)
    PASS > Microsoft.AnalysisServices, Version=18.0.5.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
           C:\Program Files\DAX Studio\Microsoft.AnalysisServices.dll

Checking ADOMD.NET (Local)
=======================
    Attempting to load: C:\Program Files\DAX Studio\bin\Microsoft.AnalysisServices.AdomdClient.dll
    FAIL > 系统找不到指定的文件。 (异常来自 HRESULT:0x80070002)
    PASS > Microsoft.AnalysisServices.AdomdClient, Version=18.0.5.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
           C:\Program Files\DAX Studio\Microsoft.AnalysisServices.AdomdClient.dll

Checking AMO (GAC)
=======================
    PASS > Microsoft.AnalysisServices, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
           C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.AnalysisServices\v4.0_13.0.0.0__89845dcd8080cc91\Microsoft.AnalysisServices.dll
    WARN > 未能加载文件或程序集“Microsoft.AnalysisServices, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)
    WARN > 未能加载文件或程序集“Microsoft.AnalysisServices, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)

Checking ADOMD.NET (GAC)
=======================
    PASS > Microsoft.AnalysisServices.AdomdClient, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
           C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.AnalysisServices.AdomdClient\v4.0_13.0.0.0__89845dcd8080cc91\Microsoft.AnalysisServices.AdomdClient.dll
    WARN > 未能加载文件或程序集“Microsoft.AnalysisServices.AdomdClient, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)
    WARN > 未能加载文件或程序集“Microsoft.AnalysisServices.AdomdClient, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)

Dax Studio Configuration
========================
    Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
    Processing DaxStudio.exe.config file...
    Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
    Bindings Found: 14
    AMO : 18.0.5.0
    ADOMD : <default>

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excel_v16
    Excel Path: C:\Program Files\Microsoft Office\Root\Office16\EXCEL.EXE
    Excel Architecture: x64

    DAX Studio Excel Add-in Registry keys
       Description: Dax Studio Excel Add-In
       FriendlyName: Dax Studio Excel Add-In
       Manifest: file:///C:/Program Files/DAX Studio/DaxStudio.vsto|vstolocal
       LoadBehavior: 3

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      N/A  >  - ࠧ
2) from Log
2019-10-08 11:42:11.777 +08:00 [Information] ============ Excel Add-in Startup =============
2019-10-08 11:42:11.827 +08:00 [Information] Excel Version: 16.0
2019-10-08 11:42:11.827 +08:00 [Information] Excel Build: 4266
2019-10-08 11:42:11.827 +08:00 [Information] Excel Operating System: Windows (64-bit) NT :.00
2019-10-08 11:42:11.847 +08:00 [Information]    Addin : Microsoft Power View for Excel Loaded: True
2019-10-08 11:42:11.847 +08:00 [Information]    Addin : Dax Studio Excel Add-In Loaded: True
2019-10-08 11:42:11.847 +08:00 [Information]    Addin : CESoft Excel Server AddIn Loaded: False
2019-10-08 11:42:11.847 +08:00 [Information]    Addin : Microsoft Power Map for Excel Loaded: True
2019-10-08 11:42:11.847 +08:00 [Information]    Addin : Mindjet MindManager 插件 Loaded: True
2019-10-08 11:42:11.847 +08:00 [Information]    Addin : Inquire Loaded: False
2019-10-08 11:42:11.847 +08:00 [Information]    Addin : Microsoft Power Pivot for Excel Loaded: True
2019-10-08 11:42:11.847 +08:00 [Information]    Addin : SAS Add-In 6.1 for Microsoft Office Loaded: False
2019-10-08 11:42:11.847 +08:00 [Information]    Addin : 中文转换加载项 Loaded: True
2019-10-08 11:42:11.847 +08:00 [Information]    Addin : think-cell Loaded: True
2019-10-08 11:42:11.847 +08:00 [Information] Logging enabled by Shift Key at startup
2019-10-08 11:42:29.561 +08:00 [Information] "WebHost" "Start" DaxStudio Host starting on port 9000
2019-10-08 11:42:30.129 +08:00 [Information] "WebHost" "Start" DaxStudio Host started on port 9000
2019-10-08 11:42:32.847 +08:00 [Error] "DaxStudioRibbon" "BtnDaxClick" "拒绝访问。" "   在 System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   在 System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   在 DaxStudio.ExcelAddin.DaxStudioRibbon.Launch(Boolean enableLogging)
   在 DaxStudio.ExcelAddin.DaxStudioRibbon.BtnDaxClick(Object sender, RibbonControlEventArgs e)"
System.ComponentModel.Win32Exception (0x80004005): 拒绝访问。
   在 System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   在 System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   在 DaxStudio.ExcelAddin.DaxStudioRibbon.Launch(Boolean enableLogging)
   在 DaxStudio.ExcelAddin.DaxStudioRibbon.BtnDaxClick(Object sender, RibbonControlEventArgs e)
2019-10-08 11:42:36.994 +08:00 [Error] "DaxStudioRibbon" "BtnDaxClick" "拒绝访问。" "   在 System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   在 System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   在 DaxStudio.ExcelAddin.DaxStudioRibbon.Launch(Boolean enableLogging)
   在 DaxStudio.ExcelAddin.DaxStudioRibbon.BtnDaxClick(Object sender, RibbonControlEventArgs e)"
System.ComponentModel.Win32Exception (0x80004005): 拒绝访问。
   在 System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   在 System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   在 DaxStudio.ExcelAddin.DaxStudioRibbon.Launch(Boolean enableLogging)
   在 DaxStudio.ExcelAddin.DaxStudioRibbon.BtnDaxClick(Object sender, RibbonControlEventArgs e)

**Comment by dgosbell** [comment] 2019-10-10 04:23
@FrankPXG - thanks for that reply, the Debug log helped me see where in the code the error is coming from. 

I may have a fix for this, but because I can't reproduce this issue I don't know if the change I've made will have any effect or not. I have a preview build of the next version available from our build server here [https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/28000028/artifacts](https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/28000028/artifacts) can you download the setup and try installing that version and see if that fixes this issue for you?

**Comment by dqaudithillstone** [comment] 2019-10-12 00:29
这是错误提示：Attempting to load: C:\Program Files\DAX Studio\bin\Microsoft.AnalysisServices.dll
FAIL > 系统找不到指定的文件。 (异常来自 HRESULT:0x80070002)


<img width="859" alt="daxerror" src="https://user-images.githubusercontent.com/55942795/66691621-46fc4e80-ecca-11e9-8bab-a33d7f0f1e51.PNG">

**Comment by dqaudithillstone** [comment] 2019-10-12 00:32
At 2019-10-10 12:23:34, "Darren Gosbell" <notifications@github.com> wrote:


@FrankPXG - thanks for that reply, the Debug log helped me see where in the code the error is coming from.

I may have a fix for this, but because I can't reproduce this issue I don't know if the change I've made will have any effect or not. I have a preview build of the next version available from our build server here https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/28000028/artifacts can you download the setup and try installing that version and see if that fixes this issue for you?

**Comment by dgosbell** [comment] 2019-10-12 06:37
> 这是错误提示：Attempting to load: C:\Program Files\DAX Studio\bin\Microsoft.AnalysisServices.dll
> FAIL > 系统找不到指定的文件。 (异常来自 HRESULT:0x80070002)
> 
> <img alt="daxerror" width="859" src="https://user-images.githubusercontent.com/55942795/66691621-46fc4e80-ecca-11e9-8bab-a33d7f0f1e51.PNG">

OK, so this is a completely different issue to the one reported by FrankPXG. That "FAIL" message is not important, DAX Checker scans multiple different locations, as long as we have 1 pass everything should work fine. But I can't read the Chinese part of the error message in your screenshot. Can you follow the same steps I told FrankPXG to do and generate a debug log file while re-producing the error and post the log file back here?

**Comment by FrankPXG** [comment] 2019-10-12 10:46
Dear Gosbell,
It still shows same problem "visit denied", as shown below,
![image](https://user-images.githubusercontent.com/56281564/66700049-04189600-ed1f-11e9-9daf-97139c1fa477.png)
**And the information from DAX Studio Checker as following:**
    Version =  v2.9.5.195
    DaxStudio.exe Version =  v2.9.5.195

Checking Operating System
=======================
    OSCaption       = Microsoft Windows 10 家庭中文版
    OSVersion       = 10.0.18362
    OSArchitecture  = 64 位
    VisibleMemoryGB = 7.85
    FreeMemoryGB    = 2.00

    Culture Name              = zh-CN
    Culture DisplayName       = 中文(简体，中国)
    Culture EnglishName       = Chinese (Simplified, China)
    Culture 2-Letter ISO Name = zh
    Culture DecimalSeparator  = .
    Culture GroupSeparator    = ,
    Culture CurrencySymbol    = ¥
    Culture ShortDatePattern  = yyyy/M/d

Checking Displays
=======================
Display: \\.\DISPLAY1 (Primary) 
         X: 0 Y: 0 Width: 1920 Height: 1080

Checking .Net Framework
=======================
    v2.0.50727 -> 2.0.50727.4927
    v2.0.50727\2052 -> 2.0.50727.4927
    v3.0 -> 3.0.30729.4926
    v3.0\Setup -> 3.0.30729.4926
    v3.0\Setup\2052 -> 3.0.30729.8795
    v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
    v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
    v3.5 -> 3.5.30729.4926
    v3.5\2052 -> 3.5.30729.5003
    v4\Client -> 4.8.03752
    v4\Client\1033 -> 4.8.03752
    v4\Client\2052 -> 4.8.03752
    v4\Full -> 4.8.03752
    v4\Full\1033 -> 4.8.03752
    v4\Full\2052 -> 4.8.03752
    v4.0\Client -> 4.0.0.0

    v4\Full\Release = 528040

Checking AMO (Local)
=======================
    Attempting to load: C:\Program Files\DAX Studio\Microsoft.AnalysisServices.dll
    FAIL > 系统找不到指定的文件。 (异常来自 HRESULT:0x80070002)
    FAIL > 未能加载文件或程序集“Microsoft.AnalysisServices”或它的某一个依赖项。系统找不到指定的文件。

Checking ADOMD.NET (Local)
=======================
    Attempting to load: C:\Program Files\DAX Studio\Microsoft.AnalysisServices.AdomdClient.dll
    FAIL > 系统找不到指定的文件。 (异常来自 HRESULT:0x80070002)
    FAIL > 未能加载文件或程序集“Microsoft.AnalysisServices.AdomdClient”或它的某一个依赖项。系统找不到指定的文件。

Dax Studio Configuration
========================
    Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
    Processing DaxStudio.exe.config file...
    Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
    Bindings Found: 15
    AMO : 18.0.5.0
    ADOMD : <default>

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excelv16
    Excel Path: C:\Program Files\Microsoft Office\Root\Office16\EXCEL.EXE
    Excel Architecture: x64

    DAX Studio Excel Add-in Registry keys
       Description: Dax Studio Excel Add-In
       FriendlyName: Dax Studio Excel Add-In
       Manifest: file:///C:/Program Files/DAX Studio/bin/DaxStudio.vsto|vstolocal
       LoadBehavior: 3

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      N/A  >  - ࠧ

And the interesting thing is that I cannot find the log file of today in the folder (I launched several times to triger DAX Studio from Excel Addin, with pushing left shift key.)
![image](https://user-images.githubusercontent.com/56281564/66700194-979e9680-ed20-11e9-9b5f-76ecc65dcac2.png)

Thank you very much.

**Comment by FrankPXG** [comment] 2019-10-12 10:57
@dgosbell   I tell @dqaudithillstone  in Chinese for the checking log.
@dqaudithillstone     
有2个 确认可以找一下，发给  Dear Gosbell,   他们分别是
1）在DAX Studio  安装目录里的  checker.exe文件，如下图所示，打开后复制
2）Log文件，复制地址“%APPDATA%\DaxStudio\log”，  找到 log 文件如下图所示，打开复制
![image](https://user-images.githubusercontent.com/56281564/66700375-1516d680-ed22-11e9-965f-2c5a91f109a1.png)

**Comment by FrankPXG** [comment] 2019-10-12 10:58
1）checker 图片
![image](https://user-images.githubusercontent.com/56281564/66700388-35469580-ed22-11e9-8f19-2c83d0dbbae8.png)

**Comment by dgosbell** [comment] 2019-10-14 19:47
@FrankPXG thanks for the translation. I can't do much more without the debug logs for both issues as I can't reproduce either of them. With your issue I'm not sure what else to try. Can you check the Application section of theWindows Event Viewer to see if there is anything reported in there when access is denied? Are you running a third party anti-virus scanner? If so maybe that is blocking access.

**Comment by FrankPXG** [comment] 2019-10-16 03:04
Dear  Gosbell,
Thank you very much anyway. I can use it anyway since the function to PowerBI works.
Have a nice day.

**Closed** 2020-07-28 23:51 UTC
Labels: awaiting reply
