### ISSUE TITLE
Error viewing metrics from AAS model

### ISSUE THREAD

**Issue by jcvv76** [DaxStudio/DaxStudio#892] opened 2022-08-24 22:56 UTC
DAX Studio v3.0.0.725
Connection: AnalysisServices - 16.0.40.19

## Summary of Issue
When trying to view metrics from an Azure Analysis Services model got an error and no data is shown.

## Steps to Reproduce
1. Connect to AAS Model
2. Go to advance, View metrics
![Error_DS_3](https://user-images.githubusercontent.com/67290676/186537751-0111ed51-eacd-41a7-a04c-57b57e1bb96b.jpg)

**Comment by dgosbell** [comment] 2022-08-24 23:58
this is a duplicate of #887 - so I'm closing this as we are tracking a fix there.

**Closed by dgosbell** 2022-08-24 23:58 UTC
