### ISSUE TITLE
Cannot Save Query Results to Static File 

### ISSUE THREAD

**Issue by cygnex** [DaxStudio/DaxStudio#929] opened 2022-09-07 15:33 UTC
DAX Studio v3.0.0.725
Connection: PowerBIDesktop - 16.0.36.23

## Summary of Issue
Queries run to static Excel file produces error "The type initializer for 'PerTypeValues'1' threw an exception. 

Output saved to grid or file produce the expected results, it is only with the Static File option I get this error.

## Steps to Reproduce
1. Open Saved query
2. Choose Results...Static ...Run

**Comment by dgosbell** [comment] 2022-09-08 00:21
Thanks for logging this. I have a fix checked in that will be part of the next release. I'm going to close this particular issue as it is a duplicate of #891 and I'm tracking this fault against that issue.

**Closed by dgosbell** 2022-09-08 00:21 UTC

**Comment by cygnex** [comment] 2022-09-08 00:53
Than you, I checked to see if this was already a logged issue but must have
missed it.

Do you know if the previous version of Dax Studio could still be installed
even if  I have already installed the newest version?

**Comment by cygnex** [comment] 2022-09-08 08:18
Awesome, thanks!
