### ISSUE TITLE
rror viewing metrics

### ISSUE THREAD

**Issue by chsauget** [DaxStudio/DaxStudio#554] opened 2021-02-27 09:51 UTC
DAX Studio v2.14.1.484
Connection: AnalysisServices - 15.1.76.24

## Summary of Issue
View of Export metrics fail on last version, still work on older versions.

## Steps to Reproduce
1. Hit Export Metrics or View Metrics
27/02/2021 10:49:43		Error viewing metrics: Une ou plusieurs erreurs se sont produites.
	Une erreur inattendue s'est produite (fichier « xmtwdatacache.cpp », ligne 2719, fonction « XMWindowingIterator::Init »).

Détails techniques :
RootActivityId : 90fd89d6-2198-4f36-a93f-3e5f69780c45
Date (UTC) : 2/27/2021 9:49:03 AM

**Comment by dgosbell** [comment] 2021-02-27 09:56
Duplicate of #459 - we've increased the accuracy of some of the metrics, but occasionally it seems to trigger this Microsoft bug. We are tracking this in the other issue so I'm going to close this one

**Closed by dgosbell** 2021-02-27 09:56 UTC

**Comment by chsauget** [comment] 2021-02-27 10:03
Thks for pointing out the duplicate, btw your workaround https://github.com/DaxStudio/DaxStudio/issues/459#issuecomment-769589539 made the it work. Thanks
