### ISSUE TITLE
DAX Studio not opening

### ISSUE THREAD

**Issue by senthilmkkdi** [DaxStudio/DaxStudio#737] opened 2021-10-12 22:35 UTC
I installed the latest version of DAX Studio on Windows 10, was working on it for couple of days, then closed it and re-opened it....it never opens...tried uninstalling and reinstalling several times, it would not open, when I double click nothing happens...the logo does not come up as well...any help in this regard is appreciated...when I open checker.exe I see an error in the below section. I tried skipping excel add-in installation, even then it does not work.
-----------------------------------------------------------------
Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excelv16
    Excel Path: C:\Program Files\Microsoft Office\Root\Office16\EXCEL.EXE
    Excel Architecture: x64

    DAX Studio Excel Add-in Registry keys
      ERROR: DAX Studio Excel addin registry keys not found!

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      PASS > No Disabled items found.

      PASS >  Found Excel Addin: Microsoft Power Pivot for Excel

    Attempting to load Excel Add-in: 
      ERROR: could not locate the Excel add-in location in the registry

**Comment by dgosbell** [comment] 2021-10-21 02:49
> The same issue I guess that other folks are saying.

I don't think it is. The issue from this thread is something brand new. I do not recall other reports of DAX Studio working and then stopping suddenly. I'm not sure what might be causing this, but I would guess that something - windows patches or security settings maybe - has changed recently on your machine. This is probably why the other fixes are not working for you since this appears to be a different issue.

Can you follow the steps on the [diagnostic logging](https://daxstudio.org/documentation/troubleshooting/logging-settings/) page and then try to startup DAX Studio outside of Excel (since it appears that the Excel add-in is working correctly). And can you also follow the steps under the section labelled **Startup Logging** and upload both sets of logs to this issue on github?

**Comment by AjaySharma2209** [comment] 2021-10-21 03:08
Actually when I open from Excel, it is not opening

**Comment by dgosbell** [comment] 2021-10-21 03:15
It does not matter as the UI is shared. Unless you are saying that it works standalone and only fails when launching from Excel then it is a different issue altogether. But if it does not launch from Excel it probably will not launch standalone either and it's easier to diagnose the issue using the standalone version.

**Comment by AjaySharma2209** [comment] 2021-10-21 03:19
yup yup. Does not work for both.

**Comment by dgosbell** [comment] 2021-11-15 02:05
Closing due to lack of diagnostic logs. If this issue is still affecting you please try v2.17 (or later) as there was a fix introduced there to work around a crash caused by corrupt WMI information. Otherwise if you can attach a diagnostic log that captures the call stack and error message for this issue I am happy to re-open it.

**Closed by dgosbell** 2021-11-15 02:05 UTC
Labels: awaiting reply

**Comment by Paruccone** [comment] 2021-12-03 07:06
same problem here, here's the log while holding shift on startup; do notice that I used it hours ago and no software/updates have been installed/removed since:

2021-12-03 08:00:07.917 +01:00 [INF] DAX STUDIO VERSION: 2.17.2.677
2021-12-03 08:00:07.946 +01:00 [INF] System Info: OSCaption = Microsoft Windows 10 Enterprise
2021-12-03 08:00:07.946 +01:00 [INF] System Info: OSRelease = 1909
2021-12-03 08:00:07.946 +01:00 [INF] System Info: OSVersion = 10.0.18363
2021-12-03 08:00:07.946 +01:00 [INF] System Info: OSArchitecture = 64-bit
2021-12-03 08:00:07.946 +01:00 [INF] System Info: VisibleMemoryGB = 31.73
2021-12-03 08:00:07.946 +01:00 [INF] System Info: FreeMemoryGB = 19.02
2021-12-03 08:00:07.946 +01:00 [INF] Culture Info: Name = en-US
2021-12-03 08:00:07.952 +01:00 [INF] Culture Info: DisplayName = English (United States)
2021-12-03 08:00:07.952 +01:00 [INF] Culture Info: EnglishName = English (United States)
2021-12-03 08:00:07.952 +01:00 [INF] Culture Info: 2-Letter ISO Name = en
2021-12-03 08:00:07.952 +01:00 [INF] Culture Info: DecimalSeparator = .
2021-12-03 08:00:07.952 +01:00 [INF] Culture Info: GroupSeparator = ,
2021-12-03 08:00:07.952 +01:00 [INF] Culture Info: CurrencySymbol = $
2021-12-03 08:00:07.952 +01:00 [INF] Culture Info: ShortDatePattern = M/d/yyyy
2021-12-03 08:00:07.954 +01:00 [INF] CommandLine Args: ["C:\\Users\\alessandro_tiberti_b\\AppData\\Local\\Programs\\DAX Studio\\DaxStudio.exe"]
2021-12-03 08:00:07.955 +01:00 [INF] Portable Mode: False
2021-12-03 08:00:07.955 +01:00 [INF] Changing minimum log event to Warning
2021-12-03 08:00:08.139 +01:00 [ERR] EntryPoint LogFatalCrash DAX Studio Standalone CurrentDomainOnUnhandledException
System.IO.FileNotFoundException: Could not load file or assembly 'MLib, Version=1.3.1.2, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'MLib, Version=1.3.1.2, Culture=neutral, PublicKeyToken=null'
   at DaxStudio.UI.AppBootstrapper.Configure()
   at Caliburn.Micro.BootstrapperBase.StartRuntime()
   at Caliburn.Micro.BootstrapperBase.Initialize()
   at DaxStudio.Standalone.EntryPoint.Main()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

2021-12-03 08:00:32.958 +01:00 [INF] DAX STUDIO VERSION: 2.17.3.683
2021-12-03 08:00:32.989 +01:00 [INF] System Info: OSCaption = Microsoft Windows 10 Enterprise
2021-12-03 08:00:32.989 +01:00 [INF] System Info: OSRelease = 1909
2021-12-03 08:00:32.989 +01:00 [INF] System Info: OSVersion = 10.0.18363
2021-12-03 08:00:32.989 +01:00 [INF] System Info: OSArchitecture = 64-bit
2021-12-03 08:00:32.989 +01:00 [INF] System Info: VisibleMemoryGB = 31.73
2021-12-03 08:00:32.989 +01:00 [INF] System Info: FreeMemoryGB = 19.27
2021-12-03 08:00:32.989 +01:00 [INF] Culture Info: Name = en-US
2021-12-03 08:00:32.991 +01:00 [INF] Culture Info: DisplayName = English (United States)
2021-12-03 08:00:32.991 +01:00 [INF] Culture Info: EnglishName = English (United States)
2021-12-03 08:00:32.991 +01:00 [INF] Culture Info: 2-Letter ISO Name = en
2021-12-03 08:00:32.991 +01:00 [INF] Culture Info: DecimalSeparator = .
2021-12-03 08:00:32.991 +01:00 [INF] Culture Info: GroupSeparator = ,
2021-12-03 08:00:32.991 +01:00 [INF] Culture Info: CurrencySymbol = $
2021-12-03 08:00:32.992 +01:00 [INF] Culture Info: ShortDatePattern = M/d/yyyy
2021-12-03 08:00:32.994 +01:00 [INF] CommandLine Args: ["C:\\Users\\alessandro_tiberti_b\\AppData\\Local\\Programs\\DAX Studio\\DaxStudio.exe"]
2021-12-03 08:00:32.995 +01:00 [INF] Portable Mode: False
2021-12-03 08:00:32.995 +01:00 [INF] Changing minimum log event to Warning
2021-12-03 08:00:33.184 +01:00 [ERR] EntryPoint LogFatalCrash DAX Studio Standalone CurrentDomainOnUnhandledException
System.IO.FileNotFoundException: Could not load file or assembly 'MLib, Version=1.3.1.2, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'MLib, Version=1.3.1.2, Culture=neutral, PublicKeyToken=null'
   at DaxStudio.UI.AppBootstrapper.Configure()
   at Caliburn.Micro.BootstrapperBase.StartRuntime()
   at Caliburn.Micro.BootstrapperBase.Initialize()
   at DaxStudio.Standalone.EntryPoint.Main()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

2021-12-03 08:00:40.944 +01:00 [INF] DAX STUDIO VERSION: 2.17.3.683
2021-12-03 08:00:40.971 +01:00 [INF] System Info: OSCaption = Microsoft Windows 10 Enterprise
2021-12-03 08:00:40.971 +01:00 [INF] System Info: OSRelease = 1909
2021-12-03 08:00:40.971 +01:00 [INF] System Info: OSVersion = 10.0.18363
2021-12-03 08:00:40.971 +01:00 [INF] System Info: OSArchitecture = 64-bit
2021-12-03 08:00:40.971 +01:00 [INF] System Info: VisibleMemoryGB = 31.73
2021-12-03 08:00:40.971 +01:00 [INF] System Info: FreeMemoryGB = 19.44
2021-12-03 08:00:40.971 +01:00 [INF] Culture Info: Name = en-US
2021-12-03 08:00:40.973 +01:00 [INF] Culture Info: DisplayName = English (United States)
2021-12-03 08:00:40.973 +01:00 [INF] Culture Info: EnglishName = English (United States)
2021-12-03 08:00:40.973 +01:00 [INF] Culture Info: 2-Letter ISO Name = en
2021-12-03 08:00:40.973 +01:00 [INF] Culture Info: DecimalSeparator = .
2021-12-03 08:00:40.973 +01:00 [INF] Culture Info: GroupSeparator = ,
2021-12-03 08:00:40.973 +01:00 [INF] Culture Info: CurrencySymbol = $
2021-12-03 08:00:40.974 +01:00 [INF] Culture Info: ShortDatePattern = M/d/yyyy
2021-12-03 08:00:40.975 +01:00 [INF] CommandLine Args: ["C:\\Users\\alessandro_tiberti_b\\AppData\\Local\\Programs\\DAX Studio\\DaxStudio.exe"]
2021-12-03 08:00:40.977 +01:00 [INF] Portable Mode: False
2021-12-03 08:00:40.977 +01:00 [INF] Changing minimum log event to Warning
2021-12-03 08:00:41.151 +01:00 [ERR] EntryPoint LogFatalCrash DAX Studio Standalone CurrentDomainOnUnhandledException
System.IO.FileNotFoundException: Could not load file or assembly 'MLib, Version=1.3.1.2, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'MLib, Version=1.3.1.2, Culture=neutral, PublicKeyToken=null'
   at DaxStudio.UI.AppBootstrapper.Configure()
   at Caliburn.Micro.BootstrapperBase.StartRuntime()
   at Caliburn.Micro.BootstrapperBase.Initialize()
   at DaxStudio.Standalone.EntryPoint.Main()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

2021-12-03 08:02:20.175 +01:00 [INF] DAX STUDIO VERSION: 2.17.3.683
2021-12-03 08:02:20.202 +01:00 [INF] System Info: OSCaption = Microsoft Windows 10 Enterprise
2021-12-03 08:02:20.202 +01:00 [INF] System Info: OSRelease = 1909
2021-12-03 08:02:20.202 +01:00 [INF] System Info: OSVersion = 10.0.18363
2021-12-03 08:02:20.202 +01:00 [INF] System Info: OSArchitecture = 64-bit
2021-12-03 08:02:20.202 +01:00 [INF] System Info: VisibleMemoryGB = 31.73
2021-12-03 08:02:20.202 +01:00 [INF] System Info: FreeMemoryGB = 19.34
2021-12-03 08:02:20.202 +01:00 [INF] Culture Info: Name = en-US
2021-12-03 08:02:20.204 +01:00 [INF] Culture Info: DisplayName = English (United States)
2021-12-03 08:02:20.204 +01:00 [INF] Culture Info: EnglishName = English (United States)
2021-12-03 08:02:20.204 +01:00 [INF] Culture Info: 2-Letter ISO Name = en
2021-12-03 08:02:20.204 +01:00 [INF] Culture Info: DecimalSeparator = .
2021-12-03 08:02:20.204 +01:00 [INF] Culture Info: GroupSeparator = ,
2021-12-03 08:02:20.204 +01:00 [INF] Culture Info: CurrencySymbol = $
2021-12-03 08:02:20.206 +01:00 [INF] Culture Info: ShortDatePattern = M/d/yyyy
2021-12-03 08:02:20.206 +01:00 [INF] Logging enabled due to Shift key being held down
2021-12-03 08:02:20.206 +01:00 [INF] Logging enabled by Excel Add-in
2021-12-03 08:02:20.207 +01:00 [INF] CommandLine Args: ["C:\\Users\\alessandro_tiberti_b\\AppData\\Local\\Programs\\DAX Studio\\DaxStudio.exe"]
2021-12-03 08:02:20.209 +01:00 [INF] Portable Mode: False
2021-12-03 08:02:20.209 +01:00 [DBG] Debug Logging Enabled
2021-12-03 08:02:20.209 +01:00 [INF] ============ DaxStudio Startup =============
2021-12-03 08:02:20.339 +01:00 [DBG] Loading Caliburn.Micro bootstrapper
2021-12-03 08:02:20.410 +01:00 [ERR] **EntryPoint LogFatalCrash DAX Studio Standalone **CurrentDomainOnUnhandledException
System.IO.FileNotFoundException: Could not load file or assembly 'MLib, Version=1.3.1.2, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.**
File name: 'MLib, Version=1.3.1.2, Culture=neutral, PublicKeyToken=null'**
   at DaxStudio.UI.AppBootstrapper.Configure()
   at Caliburn.Micro.BootstrapperBase.StartRuntime()
   at Caliburn.Micro.BootstrapperBase.Initialize()
   at DaxStudio.Standalone.EntryPoint.Main()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by Paruccone** [comment] 2021-12-03 07:25
and I have found the cause: McAfee EndPoint Security is deleting the file because it is flagged as malware:


EUROPE\XXXXX ran C:\Windows\explorer.exe, which attempted to access C:\Users\XXXXX\AppData\Local\Programs\DAX Studio\bin\MLib.dll. The Trojan named Artemis!FC88CDC2BD88 was detected and deleted.
Analyzer / Detector
Analyzer content creation date	12/2/2021 2:48 PM
Product name	McAfee Endpoint Security
Product version	10.7.0.2522
McAfee GTI query	Yes
Task name	On-Access Scan
Feature name	On-Access Scan
 
Threat
Action taken	Delete
Threat category	Malware detected
Threat detected on creation	Yes
Threat event ID	1027
Threat handled	Yes
Threat name	Artemis!FC88CDC2BD88
Threat severity	Critical
Threat timestamp	12/3/2021 8:23 AM
Threat type	Trojan
 
Source
Source hostName	W10FX6P5J3
Source process name	C:\Windows\explorer.exe
 
Target
Target access time	12/3/2021 8:23 AM
Target create time	12/3/2021 8:23 AM
Target file size (bytes)	195584
Target hash	fc88cdc2bd887be1e11acb520ed0cc68
Target host name	W10FX6P5J3
Target modify time	4/28/2020 5:45 PM
Target name	MLib.dll
Target path	C:\Users\XXXXXX\AppData\Local\Programs\DAX Studio\bin
Target user name	EUROPE\XXXXX
 
Other
Vector type	Local System
Cleanable	Yes
Detection message	McAfee Endpoint Security detected a threat.
Detection quarantine ID	{E9BF18B8-F51A-43B5-85DE-6E9C5491D2CC}
Duration before detection (days)	0
Description	EUROPE\XXXXX ran C:\Windows\explorer.exe, which attempted to access C:\Users\XXXXX\AppData\Local\Programs\DAX Studio\bin\MLib.dll. The Trojan named Artemis!FC88CDC2BD88 was detected and deleted.
First action status	Succeeded
First attempted action	Clean
Second attempted action	n/a

**Comment by dgosbell** [comment] 2021-12-03 08:55
It is unclear if this is the same problem as the other users. None of them have posted the requested log files.

Artemis is not a trojan as such it is a code name that McAfee assigns to something it thinks might be suspicious, see: 
https://service.mcafee.com/?articleId=TS100414&page=shell&shell=article-view

I suspect this could be a false positive. There are a couple of other libraries we use from the same open source author and none of those have been flagged. I suggest you follow up with McAffee. I can see a number of posts on the McAffee community forums where people get false Artemis flagging issues fixed.

**Comment by Paruccone** [comment] 2021-12-03 09:07
@dgosbell Totally agree.
McAfee has been installed on my corporate system for years: I think this happened with one of the recent security definitions' updates but something definitely up to the author to raise as a false positive :( and being a corporate system, even having local admin rights, I can't whitelist the Dll :( :(

**Comment by dgosbell** [comment] 2021-12-22 04:31
@Paruccone it looks like McAffee have fixed the false positive for this file. I just double checked at VirusTotal.com and they are now showing this file as being clean https://www.virustotal.com/gui/file/7a2c3145e84cb48ef016c57c7ea8155fcf30669cc4d09b185df62b01cbbcca21

**Comment by tsnyd111** [comment] 2022-09-13 16:24
I'm hitting on startup. The application shows in my taskbar as opened, but the actual DAX Studio window screen is invisible. I'm using the latest version (v3.0)

**Comment by dgosbell** [comment] 2022-09-13 23:02
@tsnyd111 - I think this might be a different problem so it might be worth opening a new issue. Can you try enabling the diagnostic logging by holding down the SHIFT key while starting DAX Studio (see https://daxstudio.org/docs/troubleshooting/logging-settings/ ) and then upload a copy of the log file?

**Comment by tsnyd111** [comment] 2022-09-14 00:23
@dgosbell I opened a new ticket and included the log file there.
