### ISSUE TITLE
Server Timings Not Displaying After 1st Run

### ISSUE THREAD

**Issue by daxnoob** [DaxStudio/DaxStudio#1285] opened 2024-08-05 14:03 UTC
DAX Studio v3.1.1.1031
Connection: PowerBIService - 16.0.146.21

## Summary of Issue
Server times only displaying after the first run. Subsequent runs produce the results below, even with clear cache on. I am using a DirectLake model if that helps. 

I reverted back to v3.0.11 and the behavior works as expected.

## Steps to Reproduce
1. Open DAX Studio
2. Turn on server timings
3. Run query
4. Run query a 2nd time

<img width="587" alt="image" src="https://github.com/user-attachments/assets/e34e1940-19b3-497b-a99d-c6a51adde511">

**Comment by dgosbell** [comment] 2024-08-05 21:56
Thanks for logging this. It's an issue caused by a combination of the auto clear cache and the new Execution Metrics events. I'll try and get a fix out in the next few days. A short term workaround is to switch off the auto clear cache and manually clear the cache between runs.

**Comment by daxnoob** [comment] 2024-08-06 12:34
Thanks!

**Comment by dgosbell** [comment] 2024-08-08 01:57
This should be fixed in the 3.2 update which I just released

**Closed by dgosbell** 2024-08-08 01:57 UTC
Labels: triage
