### ISSUE TITLE
Issue when Starting Dax Studio 3.0 from Excel FR  version

### ISSUE THREAD

**Issue by Durendal94** [DaxStudio/DaxStudio#910] opened 2022-08-29 08:09 UTC
DAX Studio v3.0.0.725
Connection: PowerBIDesktop - 16.0.36.23

## Summary of Issue
KO when I tried to connect to my Excel Files

![image](https://user-images.githubusercontent.com/37069416/187154863-adee06fd-6fc9-4f75-9cb7-400d6b255e92.png)

OK from PBI

My Excel is a FR version.
My PBI is a US version. 

Maybe there is a link with locales.

Best regards.
Christian

**Comment by dgosbell** [comment] 2022-09-02 02:00
This is a duplicate of #884 so I'm going to close this issue as I'm tracking this in the earlier issue.

This has something to do with changes in Excel and I'm in contact with someone on the Excel team to try and resolve this.

**Closed by dgosbell** 2022-09-02 02:00 UTC
