### ISSUE TITLE
Run DaxStudio within a filter context

### ISSUE THREAD

**Issue by Anthonyae** [DaxStudio/DaxStudio#239] opened 2019-11-01 22:05 UTC
Currently I am working within a pivot table and am working on a measure that is becoming harder to keep straight in my head. I am testing snippets of it in Dax Studio. But I have to keep updating and setting up variables to get the right filter context for my purposes. I think it would be nice to have a tab that lets you set up a filter context for your queries. That would last as long as you like until you click a button to cancel it. 

The interface could be a set of drop downs with filters to tables and an entry form for specifying specific row values if needed, similar to slicers. Or maybe taking a pivot tables current filter context directly from excel.

**Comment by dgosbell** [comment] 2019-11-02 08:33
I'm not sure if what you've described would actually be possible. But one similar idea I have been considering is maybe creating a drag & drop query builder. I was thinking that it would have a similar interface to what you have described, but it would generate the entire query rather than trying to alter an existing query. However I think we could make it work for your scenario by allowing for the expressions for any of the measures to be altered. It's still a fair bit of work, but generating the entire query would be easier to implement than trying to alter an ad-hoc query defined by the user. 

I'm thinking we would have a similar interface to the way the Power BI table visual works, but allow for the editing of measures. Does that sound it would be useful in your scenario?

**Comment by marcosqlbi** [comment] 2019-11-02 12:14
In the short term a simpler approach could creating a DAX query using a variation of the current feature "Define Filter Dump Measure (All tables)".
Such a query would be displayed in the tooltip of a Power BI report and would automatically have all the details about the filter context of that measure. Personally I don't find it really necessary, because by capturing a query for a visual with Performance Analyzer in Power BI you get the same result and you have a more realistic reproduction that could have multiple measures and filters in the same table result.

**Comment by dgosbell** [comment] 2020-06-08 10:05
A preview of the new Query Builder feature has been released with v2.11.0 which hopefully should help with this sort of scenario

**Closed by dgosbell** 2020-06-08 10:05 UTC
Labels: idea
