### ISSUE TITLE
Problems with  square brackets in Measure Name

### ISSUE THREAD

**Issue by PbISiegi** [DaxStudio/DaxStudio#837] opened 2022-04-27 07:18 UTC
DAX Studio v2.17.3.683
Connection: PowerBIDesktop - 16.0.20.17

## Summary of Issue
I need to use 
square brackets in the Measurenames to show Units of the measure for example:
WorkingHours [h]
It work without any Problems in PBI and in Dax Studio for using it.
But if I wanna redefine the Measure in Dax Studio with DEFINE MEASURES I'm getting problems.

## Steps to Reproduce
1. Use Square Brackets in Measure WorkingHours [h]
2.Use the DEFINE MEASURE in Dax Studio

**Comment by marcosqlbi** [comment] 2022-04-27 07:40
This is not a DAX Studio issue.
In the DAX syntax, you have to use ]] in order to reference a single ] in a measure name.
Power BI hides that, but internally it generates the following syntax:

[WorkingHours [h]]]

Therefore, you must use

DEFINE MEASURE 'Table'[WorkingHours [h]]] = <exp>

You should see that also measure references use this syntax in the remaining DAX code generated by Power BI.

**Comment by PbISiegi** [comment] 2022-04-27 07:45
Yes I know but that*s not the Issue.
But this code can't be used in DAX:
<img width="529" alt="image" src="https://user-images.githubusercontent.com/104488592/165467926-9fea1291-af91-449d-85de-b989872d4ade.png">

**Comment by PbISiegi** [comment] 2022-04-27 07:47
Now I think I see the Problem:
The Problem is if I use the Define Measure Function in DAX it "forgets" one Square Bracket!!
<img width="267" alt="image" src="https://user-images.githubusercontent.com/104488592/165468301-5977e8f3-7489-49c8-8cd7-efaa1a220b9a.png">

**Comment by marcosqlbi** [comment] 2022-04-27 08:40
You're right and I have good news.
The issue is fixed in the latest commit in develop branch.
You can try a preview version using the latest build from https://ci.appveyor.com/project/DarrenGosbell/daxstudio/build/artifacts
Thanks!

**Comment by PbISiegi** [comment] 2022-04-27 09:48
Thank you very much!!

**Comment by dgosbell** [comment] 2022-08-25 00:04
This should be fixed in the v3 release

**Closed by dgosbell** 2022-08-25 00:04 UTC
Labels: fix-checked-in
