### ISSUE TITLE
Issue with static xlsx output

### ISSUE THREAD

**Issue by ITManuelBZ** [DaxStudio/DaxStudio#917] opened 2022-08-31 06:55 UTC
DAX Studio v3.0.0.725
Connection: PowerBIDesktop - 16.0.39.24

## Summary of Issue
Since DAX Studio v3.0.0.725 version I cannot open exported xlsx files, an error message "Cannot be opened by excel since the file format is invalid" (translated from German) appears when opening the exported file with MS Excel. 

I tried the same export with the previous 2.17.13 version and it worked, but not with the new v3.0.0.725.

Br

**Comment by marcosqlbi** [comment] 2022-08-31 07:39
Which version of Excel are you using?

**Comment by dgosbell** [comment] 2022-08-31 07:43
Is there an error in the Log tab? This could be another instance of the issue in #891 which is due to an update in the Excel library we are using and will be fixed in the next release which should be available soon.

**Comment by ITManuelBZ** [comment] 2022-08-31 07:47
Thank you both for your prompt reply. 

I'm using Microsoft® Excel® für Microsoft 365 MSO (Version 2207 Build 16.0.15427.20182) 64 Bit

**Comment by ITManuelBZ** [comment] 2022-08-31 08:45
The error in the Log tab is "Der Typeninitialisierer für "PerTypeValues`1" hat eine Ausnahme verursacht." ...... i'm afraid its in German.

Br

**Comment by johntassetz** [comment] 2022-08-31 13:29
I'm getting the same problem. The error is
"The type initializer for 'PerTypeValues`1' threw an exception."

**Comment by dgosbell** [comment] 2022-09-02 01:56
OK, so this is a duplicate of issue #891 so I'm going to close this issue as I'm tracking this bug there. I've isolated the problem and should have a fix out shortly

**Closed by dgosbell** 2022-09-02 01:56 UTC

**Comment by ITManuelBZ** [comment] 2022-09-02 06:14
Great, thanks Darren.

Br
