### ISSUE TITLE
issue with IN operator in filters after loading .dax file

### ISSUE THREAD

**Issue by JarekWuDev** [DaxStudio/DaxStudio#1029] opened 2023-01-18 20:59 UTC
DAX Studio v3.0.5.767
Connection: PowerBIService - 16.0.59.21

## Summary of Issue
issue with filters, after loading .dax file IN operator changes to IS operator

## Steps to Reproduce
1. use filter with IN operator and at least two members
2. save .dax file
3. open .dax file
4. in filters section IN operator changes to IS operator

**Comment by dgosbell** [comment] 2023-01-20 03:43
Thanks for logging this, I've identified the issue and a fix will be included in the next release.

**Comment by Mcvein86** [comment] 2023-02-28 02:01
> Thanks for logging this, I've identified the issue and a fix will be included in the next release.

Hi thanks for looking into this case, i've reproduced this issue again, could you please look into this again?

DAX Studio v3.0.5 v3.0.4 v3.0.0 v2.17.3 v2.16.0 all tried
Excel for Microsoft 365 version 2211 Builde 16.0.15831.20098 64-bit

It apprears the saved .dax are showing IN operation if opened by some text editor such as NotePad++, guess .dax should be good, and issue lies with some process in DAX Studio.

**Comment by dgosbell** [comment] 2023-02-28 06:21
> i've reproduced this issue again

@Mcvein86 - that would be expected since this issue is still open and I have not pushed out a release with the fix yet. I'm hoping to get the next release out that will include the fix for this in the next week or two. 

This issue will close once that happens.

**Comment by Mcvein86** [comment] 2023-02-28 13:22
> > i've reproduced this issue again
> 
> @Mcvein86 - that would be expected since this issue is still open and I have not pushed out a release with the fix yet. I'm hoping to get the next release out that will include the fix for this in the next week or two.
> 
> This issue will close once that happens.

Great to hear that!

**Closed** 2023-03-14 00:03 UTC
Labels: bug, fix-checked-in
