### ISSUE TITLE
Clicking any tab while ribbon is minimized crashes the application.

### ISSUE THREAD

**Issue by SharmaAntriksh** [DaxStudio/DaxStudio#564] opened 2021-03-07 14:52 UTC
1. Open DAX Studio and minimize the ribbon. 

2. Click on any tab

Error:
![image](https://user-images.githubusercontent.com/73054674/110243988-b12e2700-7f82-11eb-9a66-4fcef3bfb093.png)

**Comment by dgosbell** [comment] 2021-03-08 00:37
Thanks for logging this. I've had a number of people clicking the "Send Report" button on this issue, but to date no one else has added any steps to reproduce this issue so I've been at a loss to know how to fix it. But now that I know how it's triggered I've been able to track it down to a recent bug in the ribbon control that we are using and it looks like they may have already fixed this so I'll do some testing against their latest release.

**Comment by dgosbell** [comment] 2021-03-19 05:37
I've been able to confirm that this is a bug in the ribbon control and updating to the latest version of this control has fixed this issue. This fix will be in the next release of DAX Studio and this issue will auto close itself when that is published

**Closed** 2021-03-28 08:30 UTC
Labels: bug, fix-checked-in
