### ISSUE TITLE
DAX Studio keeps hanging after asking to which data source to connect to

### ISSUE THREAD

**Issue by Robinio94** [DaxStudio/DaxStudio#252] opened 2019-11-18 13:00 UTC
Bug description: 
DAX Studio keeps hanging after asking to which data source to connect to

1. Click on the DAX Studio shortcut
2. Select the PBI model from the dropdown menu
3. Click Connect
4. No result

Screenshot:
![image](https://user-images.githubusercontent.com/57902925/69054374-b6710680-0a0b-11ea-8f23-4cd068eca323.png)

**Comment by Robinio94** [comment] 2019-11-18 13:01
Additionally: I've tried re-installing DAX Studio (with reboot), however, this did not fix the issue.

**Comment by Robinio94** [comment] 2019-11-18 13:13
Installed the preview version 2.9.5 of DAX Studio: also no succes

**Comment by dgosbell** [comment] 2019-11-18 19:52
Does this happen with all Power BI files or just one? If you try downloading and opening one of the [demo files](https://github.com/microsoft/powerbi-desktop-samples/tree/master/2019) that Microsoft publish when they do their monthly blog post can you connect to that?

Can you try starting DAX Studio with the [debug logging enabled](https://daxstudio.org/documentation/troubleshooting/logging-settings/) then reproduce this issue and see if that captures any error messages?

**Comment by Robinio94** [comment] 2019-11-20 11:07
Hi Darren,

Thanks for your reply!

I just tried to boot DAX Studio again and the issue seems to have resolved itself.. (Luckily 😊) I cannot reproduce the issue at the moment (both with- and without connecting to a dataset). I will send you the debug log when the issue happens again!

Kind regards,

Robin Everaars

Van: Darren Gosbell <notifications@github.com>
Verzonden: maandag 18 november 2019 20:53
Aan: DaxStudio/DaxStudio <DaxStudio@noreply.github.com>
CC: Robin Everaars <Robin.Everaars@broadhorizon.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [DaxStudio/DaxStudio] DAX Studio keeps hanging after asking to which data source to connect to (#252)


Does this happen with all Power BI files or just one? If you try downloading and opening one of the demo files<https://github.com/microsoft/powerbi-desktop-samples/tree/master/2019> that Microsoft publish when they do their monthly blog post can you connect to that?

Can you try starting DAX Studio with the debug logging enabled<https://daxstudio.org/documentation/troubleshooting/logging-settings/> then reproduce this issue and see if that captures any error messages?

**Comment by dgosbell** [comment] 2019-11-20 22:20
OK, so if you can't reproduce this behaviour I might close this issue. Feel free to re-open it or raise a new issue if this problem re-occurs

**Closed by dgosbell** 2019-11-20 22:20 UTC
