### ISSUE TITLE
DAX studio button in Excel does not start DAX studio

### ISSUE THREAD

**Issue by nVenticDW** [DaxStudio/DaxStudio#17] opened 2017-10-09 06:42 UTC
Config: v2.7 Excel 2013 64 bit the Daxstudio button in excel has no effect.  see issue #15 end of trail: dgsbell asked me to  run Excel with logging enabled: 

dgsbell wrote: "If you close all your Excel windows, then hold down left-shift while Excel starts up the add-in should start up with diagnostic logging enabled. If you can then click on the Excel add-in button to try to launch the DAX Studio UI hopefully the logs will capture some information about what is causing the issue here. If you then close Excel and paste the following path into a Windows Explorer window %AppData%\DaxStudio\Log you should see a file called DaxStudioExcel-yyyymmdd.log where the yyyymmdd reflects today's date. If you can attach that file to this issue we can have a look through it."

I decided to simply upgrade to Office 2016 Pro Plus. Installed v2.7 and got exactly the same issue. 
New Config: Office 2016 Pro Plus  64 bit, German location,  English language Full Retail
 
The DAXstudio  button doesn't work. The log file from starting Excel with Left shift pressed is attached. 

[DaxStudioExcel-20171008.log](https://github.com/DaxStudio/DaxStudio/files/1367636/DaxStudioExcel-20171008.log)

also the StudioChecker output is attached. 

[DaxStudioChecker.txt](https://github.com/DaxStudio/DaxStudio/files/1367640/DaxStudioChecker.txt)

**Comment by WSAyan** [comment] 2017-10-17 04:49
I am facing same problem. Using Excel 2013 and DaxStudio 2.6.0. DaxStudio button appears in ADD-INS section but doesn't work.

**Comment by dgosbell** [comment] 2017-10-17 05:04
@nVenticDW - unfortunately while I know which line is throwing the error the log did not capture any details. I've updated the logging in the recent 2.7.1 release to hopefully capture the error details. So could  you please try those steps again and upload the logs again?

**Comment by dgosbell** [comment] 2017-10-17 05:05
@WSAyan - we've done some improvements to the Excel integration since the 2.6 release. Can you try 2.7.1 and see if that fixes your issue?

**Comment by WSAyan** [comment] 2017-10-17 10:55
@dgosbell 
Thanks for the suggestion. It's opening now but crashing while trying to connect with PowerPivot Model.

![sda](https://user-images.githubusercontent.com/7785995/31661267-e616976e-b35b-11e7-924f-a48fb81738a3.PNG)

**Comment by dgosbell** [comment] 2017-10-17 11:41
@WSAyan - yes a separate issue might be better as this is not the same problem as the one this issue relates to. Can you also please run daxstudio.checker.exe from the same folder where you installed DAX Studio and copy the output from that into the new issue?

**Comment by nVenticDW** [comment] 2017-10-17 22:27
Version 2.7.1 
I opened excel  2016 64 bit (without opening any sheet or powerpivot model)
the DAX studio addin button starts DAX studio but caused Excel to crash and this seems to be consistent behaviour when there is no model
[DaxStudioExcel-20171018.log](https://github.com/DaxStudio/DaxStudio/files/1392793/DaxStudioExcel-20171018.log)

If I start Excel, open a powerpivot model and press the DAXstudio button it all appears to work (no excel crash) and dax studio opens. I was writing this up, went back to Dax studio. The studio crashed followed by Excel.

I tried again with a powerpivot model and didn't idle any time. It all seems to work. 
and then more crashes in Excel

I managed to get something done and it throws Excel (or was it server) sent unrecognizable response  (maybe that is me just making an error in the query though) 
[DaxStudio-20171018.log](https://github.com/DaxStudio/DaxStudio/files/1392815/DaxStudio-20171018.log)

Its a bit of touch and go whether I get a crash

hope that helps
Dan

**Comment by WSAyan** [comment] 2017-10-18 03:46
@dgosbell I've  opened a new issue #19

**Comment by EricMametPro** [comment] 2017-10-19 21:17
Hi Dan,

Don't want to be a pain but I upgraded this evening from 2.6.0 to 2.7.1

I used to be able to connect to PowerPivot through the Excel Add-In (not through the connect dialog within DaxStudio) but now I can't connect through the Excel Add-In anymore...

Not sure if that helps in any way... Happy to help if I can


Cheers

Eric

**Comment by dgosbell** [comment] 2017-10-25 06:27
@nVenticDW - I can't reproduce the behaviour you are seeing at all, either on my machine or on a test VM. And unfortunately the log files only record a connection timeout which is expected if the app is idle for some time. Do you remember which version you were running? I've added some extra error logging in 2.7.1 which should now log out unhandled exceptions at the top level which could have bypassed the logging in 2.7.0 or earlier.

**Comment by dgosbell** [comment] 2017-10-25 06:31
@EricMametPro - can't connect sounds like a different issue to the addin not starting up at all. 

If you close all your Excel windows, then hold down left-shift while Excel starts up the add-in should start up with diagnostic logging enabled. If you can then click on the Excel add-in button to try to launch the DAX Studio UI hopefully the logs will capture some information about what is causing the issue here. If you then close Excel and paste the following path into a Windows Explorer window %AppData%\DaxStudio\Log you should see some log files with the current date in the form yyyy-mm-dd. 

Can you create a new issue and post those logs there?

**Comment by EricMametPro** [comment] 2017-10-25 08:15
Hi Daren,

Actually, I can't reproduce it myself either now!
I had to install some other stuff on my workstation, which involved rebooting, and everything works fine since!

Thanks for coming back to me.

Long live 2.7.1! :+1:

**Comment by EricMametPro** [comment] 2017-10-25 08:15
I forgot to mention this is an absolutely brilliant tool.
Thanks for the good work

**Comment by iamnvt** [comment] 2018-01-12 06:28
hi,

after I upgraded to V2.7.1, I can not open the DAX Studio for Excel Model anymore.
Even if I unistall V2.7.1, and reinstall V2.6.0a, it is still the same.

**Comment by dgosbell** [comment] 2018-01-13 07:52
@iamnvt  - can you please follow the steps outlined in the first post in this issue to generate a debug log file and then attach a copy of the log to this issue so we can have a look.

**Comment by dgosbell** [comment] 2018-02-15 04:10
I'm going to close this issue as with at least 4 different people I don't know who is now working and who is not. If you are still experiencing issues please check that you have the latest release and if so create a new issue and include the output from [DaxStudio.Checker](http://daxstudio.org/documentation/troubleshooting/daxstudio-checker/) as well as a [debug log file](http://daxstudio.org/documentation/troubleshooting/logging-settings/) captured while reproducing the issue

**Closed by dgosbell** 2018-02-15 04:10 UTC
