### ISSUE TITLE
Query builder stops auto generating or running query being defined

### ISSUE THREAD

**Issue by bruce-clawson** [DaxStudio/DaxStudio#851] opened 2022-05-11 17:04 UTC
DAX Studio v2.17.3.683
Connection: AnalysisServices - 16.0.26.19

## Summary of Issue
Query Builder fails to update or run queries after adding columns below a defined measure in the Columns/Measures pane with "Error generating query: Object reference not set to an instance of an object."

## Steps to Reproduce
1. Drag some columns into the Columns/Measures area
2. Define a couple of measures
3. Add some more columns below the new measure
4. Remove one of the measures
5. For me, the "Edit Query", "Auto Generate Query", and "Run Query" buttons stop working at this point and the Output tab shows the error message noted above.

**Comment by dgosbell** [comment] 2022-05-11 23:12
So I cannot reproduce this issue using the steps provided, but I *may* have seen this issue happen from time to time.

If it is the same issue I have seen what appears to happen is that somehow one of the new measures blanks out the table setting for some reason. If you can reproduce this issue can you click on the edit icon for each new measure and check that the table is not blank?

![image](https://user-images.githubusercontent.com/8241830/167961672-82bf6012-bfdf-440e-8a14-5a4c4940576a.png)

If you are able to confirm that this is the issue and setting the table fixes this can you let me know? I think it could be a multi-threading timing issue which is why it is hard to reproduce consistently, but I should be able to add some safe guards if this appears to be the case.

**Comment by dgosbell** [comment] 2023-04-19 00:38
This should be fixed in the 3.0.7 release

**Closed by dgosbell** 2023-04-19 00:38 UTC
Labels: bug
