### ISSUE TITLE
Cannot Export Results to Excel File

### ISSUE THREAD

**Issue by bonbon622** [DaxStudio/DaxStudio#891] opened 2022-08-24 21:31 UTC
DAX Studio v3.0.0.725
Connection: AzureAnalysisServices - 16.0.40.19

## Summary of Issue
Static Excel file rendering is not working.  I have tried and replicated this issue with several different queries.   I have ensured first that these queries return data, and successfully rendered results to the table in the UI, the clipboard and files (.csv) without any issues.   Note that the linked Excel file option does not work either (.odc temp file render).  This same issue was present for me in the previous versions of DAX Studio, but the error associated with that issue displays in Excel (driver issue).

## Steps to Reproduce
1. Prepare query.
2. Under Output, Select Results.  Select Static (Excel).
3. Run query.  
4. DAX Studio log will state, "Command Complete, writing output file".
5. An error will be displayed in the log "The type initializer for 'PerTypeValues`1' threw an exception."
6. The log will display message that the Query Batch completed.

![DAX Error Excel](https://user-images.githubusercontent.com/24813567/186526873-97ab7d79-0b2e-4285-82d6-2b1937325b0c.png)
7. An Excel (.xlsx) file will render but will be 0 bytes in size.  Empty file cannot be opened.

**Comment by dgosbell** [comment] 2022-08-25 08:53
I cannot reproduce this issue myself, but I've had someone else send me an example and it only seems to be triggered by certain values in the data. I think I have found what the issue is and I'm trying to trace it back to the root cause.

**Comment by suemareverton** [comment] 2022-08-25 11:48
I can reproduce this issue for released version, but when I run DaxStudio from source-code (even using currently master branch, without suggested fix), everything works fine.

**Comment by dgosbell** [comment] 2022-08-25 21:52
> I can reproduce this issue for released version, but when I run DaxStudio from source-code (even using currently master branch), everything works fine.

Yes, I've tracked this to an issue with the build injecting an incorrect assembly binding. But it only seems to be triggered by a subset of data and it does not seem to happen when you run from Visual Studio. A colleague of mine in Japan sent me a file which reproduces this issue, so I just need to figure out why the release build is not doing the right thing.

**Comment by suemareverton** [comment] 2022-08-26 10:29
Thanks. I'm not sure if this bug only occurs for specific subsets of data, here even an EVALUATE { 0 } statment  is enough to throw the exception.

**Comment by suemareverton** [comment] 2022-08-26 11:24
It's seems some problem with diferent versions of dependencies files.

The file's version of System.Runtime.CompilerService.Unsafe.dll of released version located at C:\Users\<user>\AppData\Local\Programs\DAX Studio\bin is 5.0.20.51904, while the same file for Dev Version located at \src\bin\debug is 6.0.21.52210. 

Replacing the released file with the file from Dev Enviroment (version 6) will make the official version works fine!

**Comment by dgosbell** [comment] 2022-08-26 14:05
yes, but both the release and debug builds are created from the same .sln file so it's not clear yet why they end up with different versions of this dll. 

Altering the assembly binding redirect in the daxstudio.exe.config file to point to v 5.0.0.0 also fixes this. 

It's currently pulled into the main build as a transitive dependency and I'm guessing there may be multiple transitive dependencies for different versions. So possibly directly referencing this dll will force a specific version to be referenced. Or I could maybe override the assembly binding redirects in app.config. Either way I might need to build a test around this as this will hard code the specific dependency which could break future builds if the transitive dependencies are updated.

**Comment by suemareverton** [comment] 2022-08-26 15:30
When I execute DaxStudio.Standalone project from Visual Studio, everything works fine (debug and release version). The bug occurs when I rebuild the entire solution, because others projects replace the DDL with other file versions:

DAXStudio.Common, DAXStudio.Interfaces, DAXStudio.QueryTrace and DAXStudio.QueryTrace.Excel -> version 5.0
DAXStudio.ExcelAddmin -> version 4.6

For example, since in Solution's Projects Builder Order, the DAXStudio.ExcelAddIn project is after DAXStudio.UI, the DLL's version will be 4.6. If I unload this project from solution, the DLL's version will be 6.0.

Since rebuild solution must be last step to generate the released version, this must be the origin of the problem.

**Comment by dgosbell** [comment] 2022-08-27 11:35
> Since rebuild solution must be last step to generate the released version, this must be the origin of the problem.

All the releases are generated on AppVeyor build servers. When I commit to the master branch they pull down a fresh copy of the latest source and do a fresh build. 

But ideally it should not matter if you do an incremental or a full build. I think it's a bug in msbuild that it writes the binding redirects for 6.0, but then overwrites the dll with an older version. But I think editing the dependencies to force the UI dll to build after the others might fix this so I'm going to test that as it feels like the least fragile work around so far.

**Comment by yibuyimu** [comment] 2022-09-16 18:20
l have also meet this problem,wish it can be solved asap

**Comment by dgosbell** [comment] 2022-09-22 02:51
this should now be fixed in the 3.0.1 update

**Closed by dgosbell** 2022-09-22 02:51 UTC
Labels: bug

**Comment by CharlieMather** [comment] 2022-09-23 00:00
Thanks, Darren.  Really liking 3.0!!
Regards,

Charlie

Charlie Mather
***@***.*** 

    On Wednesday, September 21, 2022 at 10:51:52 PM EDT, Darren Gosbell ***@***.***> wrote:  
 
 


this should now be fixed in the 3.0.1 update

**Comment by bonbon622** [comment] 2022-09-28 16:22
This is working in 3.0.5 and everything else looks great also.  Thanks again, Darren!

**Comment by CharlieMather** [comment] 2022-10-11 07:35
Agreed!  Thanks Darren.
Regards,

Charlie

Charlie Mather
***@***.*** 

    On Wednesday, September 28, 2022 at 12:22:14 PM EDT, bonbon622 ***@***.***> wrote:  
 
 


This is working in 3.0.5 and everything else looks great also. Thanks again, Darren!
