### ISSUE TITLE
Option for tabs vs spaces

### ISSUE THREAD

**Issue by Arklur** [DaxStudio/DaxStudio#263] opened 2019-12-12 18:32 UTC
QoL thingy: make it possible to pick whether to use tabs over spaces (and preferably the size of spaces / make the default 4).

**Comment by dgosbell** [comment] 2019-12-12 19:19
This is a duplicate of #195 which is coming in the next release exactly as you've stated

**Closed by dgosbell** 2019-12-12 19:19 UTC
Labels: duplicate, fix-checked-in
