### ISSUE TITLE
Out of memory error exporting a query to a file

### ISSUE THREAD

**Issue by Natshenoy** [DaxStudio/DaxStudio#311] opened 2020-04-13 15:10 UTC
Hi,

I am running a query In DAX studio from  my PBI file and I get the following error: There is not enough memory to complete this operation, Please try again when there may be more memory available. What do I do? The final line is Query Batch completed with errors and I do not see the query anywhere.

**Comment by Natshenoy** [comment] 2020-04-13 15:11
Please let me know how to fix the issue above

**Comment by AstroBernal** [comment] 2020-04-13 15:13
Did you know that Power BI and DAX studio are note the same thing?

**Comment by Natshenoy** [comment] 2020-04-13 15:15
Yes I do know that. I am writing a query to extract some data from my PBI file so that I can have it in the csv format for something else.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dgosbell** [comment] 2020-04-13 23:40
If you have a look in Task Manager I think you will find that it is Power BI Desktop running out of memory, not DAX Studio. The only way to fix this is to alter your query to extract smaller sets of data at a time. Every time I've seen this issue in the past it's been caused by Power BI Desktop. It's currently targeted at producing summary data sets and when you try to dump a large, detailed dataset the internal materialization of the dataset can result in out of memory errors like this.

**Comment by dgosbell** [comment] 2020-04-13 23:41
> The final line is Query Batch completed with errors and I do not see the query anywhere.

Sometimes the error messages are longer than the output window, you may need to scroll back up or increase the size of the output pane to see the message

**Comment by Natshenoy** [comment] 2020-04-13 23:45
Thanks for your reply. The data is all in my power bi file but it cannot be extracted via dax studio to csv. Does that still mean power but is unable to take the load of the data?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dgosbell** [comment] 2020-04-14 01:04
Yes, that is entirely possible and every time someone has reported a memory issue on export like this that has been the case. 

When Power BI loads data it reads and compresses the data in 1 million row segments. But when you run a query the **entire** result set gets materialized and decompressed in memory before sending it to the client. So if you are trying to export all your data you could be hitting this issue. You can also hit problems with certain patterns of measures which trigger internal materialization.

As I said earlier, if you check Task Manager while doing an export you should be able to see if it is PowerBI.exe or msmdsrve.exe using the memory or daxstudio.exe (msmdsrv.exe is the tabular engine process)

**Comment by dgosbell** [comment] 2020-06-08 10:06
Closing as this is a PowerBI issue, not something we can fix in DAX Studio

**Closed by dgosbell** 2020-06-08 10:06 UTC
Labels: awaiting reply
