### ISSUE TITLE
Error Stating Trace

### ISSUE THREAD

**Issue by Lomarques-s** [DaxStudio/DaxStudio#1024] opened 2023-01-15 14:03 UTC
DAX Studio v3.0.5.767
Connection: PowerPivot - 13.0.1700.1119

## Steps to Reproduce
1. Click on "Server Timings"
2. 
3.
![image](https://user-images.githubusercontent.com/121581060/212545197-3daf6456-e4a5-4f43-8cf5-4203d10f726f.png)

**Comment by dgosbell** [comment] 2023-01-15 22:50
Sorry, but I cannot reproduce this or work on any of the Excel functionality at the moment since I am blocked by issue #884 and am waiting on Microsoft to release an Excel update which fixes that issue. Once that is fixed I can try and look at this.

**Comment by Lomarques-s** [comment] 2023-01-15 23:07
Thank you by all.

**Comment by dgosbell** [comment] 2023-03-18 23:18
I believe this is fixed in 3.0.6 now that the Excel update has been released that fixes the PowerPivot connectivity. Can you please try that and let me know if it works for you?

**Comment by dgosbell** [comment] 2023-03-29 22:08
closing due to lack of response. assuming 3.0.6 fixed this.

**Closed by dgosbell** 2023-03-29 22:08 UTC
Labels: awaiting reply
