### ISSUE TITLE
Error: The connection cannot be used while an XmlReader object is open.

### ISSUE THREAD

**Issue by KarlosMuradyan** [DaxStudio/DaxStudio#488] opened 2020-12-21 01:24 UTC
Hi,

An issue arises when exporting the data to csv files when using DaxStudio with PowerBI. Please see below for detailed description.

**Describe the bug**
In the issue setting, DaxStudio is connected to PowerBI Desktop, which is connected to the data source. When exporting the data to csv files using Advanced -> Extract Data button, error is being thrown after 1.5-2 minutes (in the progress bar, around 20,000 rows is extracted when the error occurs). Please see the screenshot below for the error log.

**To Reproduce**
1. Connect PowerBI Desktop to data source
2. Establish connection from DaxStudio to PowerBI Desktop
3. Click on Advanced -> Export Data -> CSV Files
4. Wait for 1 - 2 mins, see error

**Expected behavior**
The data is extracted to the given directory

**Screenshots**
![error_log](https://user-images.githubusercontent.com/18456186/102729905-7f90b280-42e7-11eb-9c98-2c711bfc2454.jpg)

Any support or advice from your side would be very helpful.

Thanks in advance

**Comment by dgosbell** [comment] 2020-12-21 21:57
Thanks for logging this, The issue is not actually time or size related, I was able to reproduce this by clicking away to another app then back to DAX Studio. I just tested the fix with a 120 million row table and it generated a 20Gb file over a couple of hours with no errors and I was constantly clicking back and forth during that time to check the progress.

**Comment by KarlosMuradyan** [comment] 2020-12-21 22:43
Thanks for the quick response!

**Comment by meens174** [comment] 2021-01-04 05:46
Hi Darren, 

 I am facing the same issue , if I switch tabs and come back to DAX, my export stops throwing the same error - could you please help me locate the fix done ( I tried looking but could not find the same)

Thanks
Meenakshi

**Comment by dgosbell** [comment] 2021-01-04 09:11
@meens174 the fix has not been deployed yet. I'm looking to publish a new release shortly which will include this fix

**Comment by meens174** [comment] 2021-01-04 22:20
Sure, no worries. Thank you !

**Comment by tschiku666** [comment] 2021-01-05 19:23
same issue here. a 10.5M rows table.

**Comment by dgosbell** [comment] 2021-01-18 11:48
This should be fixed in the 2.14 release which was just published

**Closed by dgosbell** 2021-01-18 11:48 UTC
Labels: bug, fix-checked-in
