### ISSUE TITLE
'Write Parameter XML' bug

### ISSUE THREAD

**Issue by SharmaAntriksh** [DaxStudio/DaxStudio#780] opened 2021-12-17 10:21 UTC
When using the Write Parameter XML option, DAX Studio crashes.

https://user-images.githubusercontent.com/73054674/146529612-f6779946-7ca8-4e37-ba0b-4129635fe10f.mp4

![image](https://user-images.githubusercontent.com/73054674/146529313-254b6641-0c60-427f-bffa-c52fc12aad01.png)

**Comment by dgosbell** [comment] 2021-12-18 03:45
Thanks for reporting this. The problem is that DAX Studio is not expecting a blank value in the parameter. The whole point of the 'Write Parameter XML" was to save out the values typed into the dialog so that you did not have type them in repeatedly. But I have a fix checked in that will go out in the next release which will allow for blanks in the parameter values.

As a short term work around you can type any value into the Value box then if you really want to filter against an empty string you can just remove the value by editing the generated XML.

**Comment by dgosbell** [comment] 2022-09-28 22:00
This should be fixed in the v3 releases

**Closed by dgosbell** 2022-09-28 22:00 UTC
Labels: bug, fix-checked-in
