### ISSUE TITLE
CTRL + Backspace should put the cursor at the start of the current line

### ISSUE THREAD

**Issue by SharmaAntriksh** [DaxStudio/DaxStudio#1247] opened 2024-03-18 11:04 UTC
As the title suggest when pressing CTRL + Backspace can the cursor be put at the start of the same line, right now it jumps to the end of the previous line.

**Comment by dgosbell** [comment] 2024-03-21 22:20
I cannot replicate this issue. For me ctrl+backspace just deletes the whole word in front of the cursor. It's not jumping lines expectantly

**Comment by dgosbell** [comment] 2024-04-23 05:27
This behaviour is built into the edit control library which we are using (AvalonEdit). There are no options / settings to alter this behaviour so I'm going to close it as by design

**Closed by dgosbell** 2024-04-23 05:27 UTC
Labels: idea, triage
