### ISSUE TITLE
Column formatting not preserved in results

### ISSUE THREAD

**Issue by MarconosII** [DaxStudio/DaxStudio#964] opened 2022-09-26 04:25 UTC
DAX Studio v3.0.3.762
Connection: AnalysisServices - 15.0.35.22

When you run a query the data formatting is not reading what is in the model and applying it correctly.  Additionally once a $ formatting is set all numeric columns after that one are formatted as $ values until you hit a text value that seems to reset things.

## Steps to Reproduce
1. Type in a query that has a % column, $ column and % column
2. Run the query, the % column will not get it's formatting applied, $ column will get it's value formatted, the 2nd % column will be formatted as a $ column.

**Comment by dgosbell** [comment] 2022-09-26 10:20
DAX queries do not return the data in a formatted state, so DAX Studio looks up the format in the data model based on the output column names. I've just added the details of how I do the result formatting [here](https://daxstudio.org/docs/features/result-formatting/) - can you have a look at that and see if it explains your issue?

If not, can you post an example query and some screen shots as I cannot reproduce your issue based on the description above?

If you cannot use your production data set, could you try to maybe reproduce this problem using the sample pbix file from the [tutorials](https://daxstudio.org/docs/tutorials/writing-dax-queries/)

**Comment by dgosbell** [comment] 2022-10-24 03:46
Closing due to lack of reply. Feel free to re-open if you have more information to add

**Closed by dgosbell** 2022-10-24 03:46 UTC
Labels: awaiting reply
