### ISSUE TITLE
Dax Studio crashes when laptop wakes up from sleep

### ISSUE THREAD

**Issue by Martina222** [DaxStudio/DaxStudio#230] opened 2019-10-16 07:01 UTC
This doesn't happen every time, but about 30% to 50% of the time.

DAX Studio 2.9.4 crashes on wake up from sleep.

Steps to reproduce:
- Work in DAX Studio with several windows open, connected to same Analysis Server, or to different ones
- Instead of closing Dax Studio and shutting down laptop at the end of the day, click on Windows Start button and choose Sleep
- The next morning, wake laptop from sleep
- Dax Studio crashes

[DaxStudio-20190910.log](https://github.com/DaxStudio/DaxStudio/files/3732857/DaxStudio-20190910.log)

**Comment by dgosbell** [comment] 2019-10-17 06:36
I think I may have seen this once myself, but it appears to bypass the logging and crash reporting. I'll see if I can find some time to do a few sleep wake cycles in debug mode to try and capture the root cause.

**Comment by Martina222** [comment] 2019-10-17 06:58
Yes, the attached log file may be irrelevant, as I am not even sure that it was created during one of those crashes.
However, it shows that Dax Studio does things in the background (in this case autosave), and if I had a way to turn off everything that it does in the background, I am pretty sure I wouldn't have those crashes any more.
I imagine it does autosave, and some sort of polling of the server.
An option to turn all of this off, and have Dax Studio only be active on user interaction would be great.

**Comment by dgosbell** [comment] 2019-10-24 22:25
@Martina222 we don't do a lot of things in the background. We do check for model changes when the app gets focus (so this happens any time you alt-tab to DAX Studio or click on it after working in another app) This is off by default for cloud based data sources, but you can also turn it off in the options for local network and localhost based connections
![image](https://user-images.githubusercontent.com/8241830/67528104-5a64dc00-f704-11e9-9b36-d2a53dbc19a8.png)
And there is the auto-save running in the back ground. But both of those things are running all the time so I can't think what makes waking from sleep different.
I've tried a bunch of different tests waking and sleeping my laptop and have not been able to trigger a crash. But this could just be due to different hardware or drivers. 

I'd be curious to know if switching off the automatic metadata refresh improves this situation.

**Comment by Martina222** [comment] 2019-10-25 07:19
I have more details on the case:

I have metadata refreshes disabled and it still happens, so it looks like it is autosave.
It appears not to crash when the laptop goes to sleep and wakes up while connected to the corporate network. However, when the laptop wakes up at a location where it first connects to Wifi and then has to authenticate to the VPN, it crashes. I think it is because the location for the autosave is not available until VPN tunnel is available.
If there was a way to force the autosave to a specific location, I would assign it somewhere on the C drive (because our MyDocuments folder is redirected on the corporate network). Or alternatively maybe autosave could get error handling that makes it survive a condition where the autosave location is not available.

**Comment by dgosbell** [comment] 2019-10-28 00:08
Thanks for the extra information

> Or alternatively maybe autosave could get error handling that makes it survive a condition where the autosave location is not available.

Unfortunately this is not our issue as the autosave already has this. I double checked this by temporarily hard coding the autosave location to a folder on a usb drive and then removed the drive while DAX Studio was running, it logged an error for the missing drive, but did not crash the application. 

However you do bring up a valid point. I might look at changing the default location for the auto save and logging to the local profile instead of the roaming one. (the roaming profile can be re-directed by IT departments, the local one is always local to the machine)

There is one other event that could be affected by switching from a corporate network to a local one which I'm investigating.

Next time you see a crash can you open Event Viewer (just type "Event Viewer" into the start menu) and check under Windows Logs > Application and see if there is an error logged by Windows when DAX Studio crashes, if there is something that may give a hint as to what is going on.

**Comment by Martina222** [comment] 2019-10-29 07:43
I have reproduced the issue last night, where can I send you the evidence (at a non-public location) ?
Alternatively, you may want to try removing the USB drive while the laptop is in sleep, instead of when Dax Studio is running. To me it looks like this happens only in the start up phase for some reason.

**Comment by dgosbell** [comment] 2019-10-30 05:44
You can send any extra info you have to ![image](https://user-images.githubusercontent.com/8241830/67818857-edd44d80-fb06-11e9-825d-6c1b583774e2.png) I've been able to make some improvements to the error handling and I've found one scenario where a crash does not trigger the crash reporting. So if you wanted to try a preview version of the next release which includes these improvements you can download a copy from our build server [here](https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/28475946/artifacts). Unfortunately I'm still not able to force this crash on my machine so I can't tell if the improvements to the error handling will make any difference.

**Comment by dgosbell** [comment] 2019-11-07 03:32
Thanks for the extra information you emailed through. The stack traces enabled me to see exactly where this error was coming from. I actually had already found the root cause of this issue and it is fixed in current preview builds and will go out officially in the next release. Thanks very much for helping me to sort this out.

**Comment by dgosbell** [comment] 2019-12-19 21:56
This should now be fixed in the 2.10.0 release

**Closed by dgosbell** 2019-12-19 21:56 UTC
Labels: bug, fix-checked-in
