### ISSUE TITLE
Database now defaults to the first alphabetical perspective instead of model

### ISSUE THREAD

**Issue by o-o00o-o** [DaxStudio/DaxStudio#445] opened 2020-10-27 12:05 UTC
**Describe the bug**
Database now defaults to the first alphabetical perspective instead of model (since 2.13)

**To Reproduce**
1. Connect to a database with 3 perspectives, A, B and Model
2. Notice that A is selected and you have to select Model manually
3. Then if you change database it goes back to A again..

**Expected behavior**
Model should be selected by default as per previous versions of DaxStudio

**Screenshots**

**Additional context**
This is a real problem as it takes nearly 2 minutes to load our metadata and we always want model so this means what used to take 2 minutes now takes 4

**Comment by dgosbell** [comment] 2020-10-27 23:40
Thanks for logging this. This was an unintended side effect of the introduction of the "resilient connections" feature which adds retry logic if the connection is dropped for any reason. This will be fixed in the next release so that the base model is selected by default. (Technically it's possible to rename the base model to something other than "Model" so I'm using metadata from the DMVs to find the base cube).

A preview build with this fix included is available here if you'd like to test it: [https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/35993899/artifacts](https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/35993899/artifacts)

2 minutes seems like an extremely long time. Is this a very large model on AzureAS? Do other clients take this long (or longer) to fetch the metadata for this model?

If you run a query like the following, replacing <database name> with the name of your database, does it take a few minutes to return?
```
SELECT * FROM SYSTEMRESTRICTSCHEMA($SYSTEM.DISCOVER_CSDL_METADATA, [CATALOG_NAME] = '<database name>') 
```

I'm just curious if there is anything I can do to improve the load time, but if the above query is what is taking all the time then there is not much we can do from the DAX Studio side of things.

**Comment by o-o00o-o** [comment] 2020-10-29 13:35
I can't seem to install the preview version. Am getting this error on installation. I've closed powerbi, excel, visual studio so not sure what could be blocking it. Also no matching items from a handle search using process explorer.. 

![image](https://user-images.githubusercontent.com/13693159/97580627-73752c80-19eb-11eb-96f5-6d35f62ec02a.png)

Any ideas?

**Comment by o-o00o-o** [comment] 2020-10-29 13:48
Ok, restarted my machine and this solve it but now when starting I get this

Could not load file or assembly 'Microsoft.AnalysisServices.Core, Version=19.12.3.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by dgosbell** [comment] 2020-10-29 21:17
So I have seen issues updating the vsto recently. It can either be caused by a crashed version of Excel (so you will see an excel.exe in Task Manager, but no visible windows). Or it can be caused by ccmexec.exe which is part of the Microsoft System Centre software some organisations use to deploy software. I'm not sure why this sometimes holds on to the vsto file, but a reboot will fix this.

And the second error is an issue with an update to one of the microsoft libraries, it's references twice and somehow the update process only updated one of the 2 references causing this issue. This is fixed in the current preview build here:
[https://ci.appveyor.com/project/DarrenGosbell/daxstudio/build/artifacts](https://ci.appveyor.com/project/DarrenGosbell/daxstudio/build/artifacts)

**Comment by o-o00o-o** [comment] 2020-11-03 22:02
Thanks @dgosbell but I can't see an installer at the end of that link?

**Comment by dgosbell** [comment] 2020-11-03 22:21
Sorry, @o-o00o-o I was doing some work on an experimental branch on the weekend and I've deliberately blocked the installer build for those. Here is a link to the latest preview build [https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/36048210/artifacts](https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/36048210/artifacts)

**Comment by o-o00o-o** [comment] 2020-11-05 09:00
Yes in my case it was ccmexec. I can kill it by running task manager as an admin. It would be good if this area could be improved as having to manually kill this everytime I install an update will be confusing for people. 

I can confirm that that version selects Model correctly now. Still looking into the performance issue

**Comment by dgosbell** [comment] 2020-11-05 10:49
> Yes in my case it was ccmexec. I can kill it by running task manager as an admin. It would be good if this area could be improved as having to manually kill this everytime we install an update will be confusing for people.

This is not a DAX Studio bug, it is a bug in Microsoft Endpoint Configuration Manager that was apparently fixed back in Aug in this hotfix [https://support.microsoft.com/en-us/help/4560496](https://support.microsoft.com/en-us/help/4560496)

If you search that KB article for VSTO you will find the following in the **Issues Fixed** section:

>The installation or removal of Office updates may fail. This occurs when the SMS Agent Host (ccmexec.exe) incorrectly holds a lock on Office add-in files, such as Visual Studio Tools for Office (VSTO) add-ins, after hardware inventory runs.

So if your IT department install this hotfix this sounds like it should resolve this issue.

**Comment by o-o00o-o** [comment] 2020-11-05 11:52
Ah yes that makes sense, thanks for that information.

**Closed** 2021-01-18 09:23 UTC
Labels: bug, fix-checked-in
