### ISSUE TITLE
Column Cardinality

### ISSUE THREAD

**Issue by m-kovalsky** [DaxStudio/DaxStudio#504] opened 2021-01-14 17:49 UTC
Vertipaq Analyzer in Excel (v1.93) gets a different number for column cardinality than DAX Studio's .vpax. Vertipaq Analyzer in Excel calculates it by taking the ROWS_COUNT from the $system.discover_storage_tables DMV where LEFT(TABLE_ID,2) = 'H$'. I'm not sure how DAX Studio calculates this. However, the DAX Studio value is correct while the Vertipaq Analyzer in Excel value is incorrect. I confirmed this by doing a countrows(distinct('table'[column])). This DAX provides the column cardinality which equals the value provided by DAX Studio.

How is DAX Studio calculating the column cardinality? And, perhaps Vertipaq Analyzer in Excel should be fixed accordingly?

Thanks!

**Comment by marcosqlbi** [comment] 2021-01-14 17:55
VertiPaq Analyzer 2.0 is a library we included in DAX Studio. It uses a more accurate system to retrieve the number of unique values in a column, using a DAX query to get the exact number.
VertiPaq Analyzer 1.93 relies on a DMV that is not accurate after a refresh and possibly in other conditions. The number seems to be accurate only after you restore a database from a backup.
I'm going to close this case because the current code is correct and VertiPaq Analyzer 1.93 cannot be fixed (please use 2.0 instead!).

**Closed by marcosqlbi** 2021-01-14 17:55 UTC

**Comment by m-kovalsky** [comment] 2021-01-14 18:33
Vertipaq Analyzer 1.93 is the last version that actually does calculations on its own. The versions after this (2.0 etc) simply organize data in Excel from a given .vpax file.

That's really interesting that DMVs can show an inaccurate number. Sounds like a bug for the product group to fix. I wonder if there are other stats from DVMs used in Vertipaq Analyzer which can be incorrect in various situations. Do you know?

**Comment by marcosqlbi** [comment] 2021-01-14 19:02
The DMV has the purpose to show allocated resources, and they are correct by doing so. However, I think you prefer to know that you are using 15 unique values now, rather than knowing that you had 19 slots in the dictionary because there were values now no longer present after a new update of a partition or something like that. Also, the memory size is the allocated memory, which after a refresh is bigger than required because the memory is allocated in blocks.
Thus, these are not bugs, but "by design" behavior. Because we wanted a different feature in VertiPaq Analyzer, we had to use other techniques other than relying on DMVs only.

**Comment by m-kovalsky** [comment] 2021-03-25 10:20
I believe a faster way (than using DAX) to get the column cardinality is to use the Statistics_DistinctStates column within TMSCHEMA_COLUMN_STORAGES.

**Comment by marcosqlbi** [comment] 2021-03-25 10:27
DAX is fast getting the DISTINCTCOUNT if the model is in memory, because it does not send any query to the storage engine if you don't filter data. The real issue is whether you use DirectQuery with VertiPaq Analyzer, of course!
However, the expensive part is not the DISTINCTCOUNT but the analysis of invalid relationships. We have parameters to disable that (in VertiPaq libraries) and there is now an option in DAX Studio.
Do you know whether TMSCHEMA_COLUMN_STORAGES is not affected by the issue I described above (providing the dictionary size instead of the number of unique values you actually have in the column)?

**Comment by m-kovalsky** [comment] 2021-03-25 11:11
I have to find out if this DMV is affected by the issue you described. If not, it seems like a preferred method since the values are more readily available. 
How are you calculating the invalid relationships? I believe using DAX is the only method. Unfortunately haven't seen any useful DMVs for that.

**Comment by marcosqlbi** [comment] 2021-03-25 12:28
Invalid relationships are evaluated in  [LoadRelationshipStatistics](https://github.com/sql-bi/VertiPaq-Analyzer/blob/0e946c72ce807fb64d7bdf3e368887ffff2dd55a/Dax.Model.Extractor/StatExtractor.cs#L51) function.
I look forward to hearing from you about the DMV. However, the timing seems not a problem for the query in [(LoadColumnStatistics)](https://github.com/sql-bi/VertiPaq-Analyzer/blob/0e946c72ce807fb64d7bdf3e368887ffff2dd55a/Dax.Model.Extractor/StatExtractor.cs#L218).
