### ISSUE TITLE
Dax Studio can't connect to Excel 2016 PowerPivot

### ISSUE THREAD

**Issue by vbakh** [DaxStudio/DaxStudio#3] opened 2017-04-11 20:09 UTC
When I click Dax Studio on AddIn tab in Excel with a spreadsheet with PowerPivot loaded, it doesn't do anything. I am not getting any notifications, error messages etc. 

Windows Application Log shows the following informational event:
*The description for Event ID 0 from source DaxStudio cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.
If the event originated on another computer, the display information had to be saved with the event.
The following information was included with the event: 
DaxStudio Excel Add-in Listening on port 9000
the message resource is present but the message is not found in the string/message table*

Troubleshooting steps I've done:
- Enabled VSTO logging - no luck, no notifications
- Manually enabled Fusion Logging - no logs appeared in the folder I provided even after I opened a standalone version of Dax Studio. 
- Checked for dependencies using a powershell script provided on Dax Studio's Codeplex page - everything needed is in place.

I do not see any *.config files in the c:\program files\Dax Studio folder, nor in appdata\Roaming\DaxStudio. Are they stored somewhere else?

BTW, the tooltip on the icon says "Exectute Dax Query".

**Comment by marcosqlbi** [comment] 2017-04-29 19:31
I'm not able to repro, I can run DAX Studio with Excel 2016 on different PCs. I hope Darren will be able to provide you some more guidance for the troubleshooting.

**Comment by vbakh** [comment] 2017-04-29 19:44
Thanks Marco.

**Comment by dgosbell** [comment] 2017-04-30 20:41
I can't reproduce this either. I've setup a new Windows 10 VM, installed Excel 2016 and DAX Studio and it works fine. So all I can think is that it is probably some other add-in or something else on the PC that is interfering somehow. I've been working on making the debug logging easier to enable and adding some extra logging statements around the PowerPivot connection to hopefully help isolate this issue.

**Comment by vbakh** [comment] 2017-05-02 06:47
Thanks Darren. It works on my another machine with 64-bit Excel. I haven't tried it anywhere else (yet).

**Comment by chrisezard** [comment] 2017-06-27 14:47
I have just installed DAX Studio and tried opening it in an Excel 2016 Power Pivot workbook.
Instead of opening the Connect dialog, it opens the Excel 2016 Help dialog, so I can't use it!

Any help would be much appreciated :)

BTW, confirm "Exectute Dax Query" misspelling

**Comment by dgosbell** [comment] 2017-06-28 01:01
We still have not been able to replicate this issue. Can you check in Excel File -> Options -> Addins that DAX Studio is not listed in the Disabled Addins? The help dialog thing is strange, we don't have any code linking to the Excel help.

Otherwise I've just released an update to DAX Studio Checker here [https://daxstudio.codeplex.com/releases/view/631424](https://daxstudio.codeplex.com/releases/view/631424) that includes some more diagnostics specifically around the Excel add-in. So you could try running that and seeing posting the updated results back here.

What Anti-Virus software are you running? I've seen some mentions that AV software can sometimes block some Office Addins.

**Comment by chrisezard** [comment] 2017-06-28 20:32
1. DAX Studio is an active COM Add In.
2. I will need to check what AV software is running
3. I have run DAX Studio Checker (nice work, BTW) with these results...

Checking .Net Framework
=======================
v2.0.50727 -> 2.0.50727.5420
v2.0.50727\1033 -> 2.0.50727.5420
v3.0 -> 3.0.30729.5420
v3.0\Setup -> 3.0.30729.5420
v3.0\Setup\1033 -> 3.0.30729.5420
v3.0\Setup\Windows Communication Foundation -> 3.0.4506.5420
v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.5011
v3.5 -> 3.5.30729.5420
v3.5\1033 -> 3.5.30729.5420
v4\Client -> 4.6.01055
v4\Client\1033 -> 4.6.01055
v4\Full -> 4.6.01055
v4\Full\1033 -> 4.6.01055
v4.0\Client -> 4.0.0.0

Checking AMO
=======================
FAIL > Could not load file or assembly 'Microsoft.AnalysisServices, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
PASS > Microsoft.AnalysisServices, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
WARN > Could not load file or assembly 'Microsoft.AnalysisServices, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.

Checking ADOMD.NET
=======================
FAIL > Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
PASS > Microsoft.AnalysisServices.AdomdClient, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
WARN > Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.

Dax Studio Configuration
========================
Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
C:\Program Files\DAX Studio\DaxStudio.exe.config file not found.

Checking Excel Add-in
=======================
Detected Excel Version: 16 - Excel_v16
DAX Studio Excel Add-in Registry keys
   Description: Dax Studio Excel Add-In
   FriendlyName: Dax Studio Excel Add-In
   Manifest: file:///C:/Program Files/DAX Studio/DaxStudio.vsto|vstolocal
   LoadBehavior: 3

Checking for Excel 2010 Disabled Add-ins
  PASS > No Disabled items found.
Checking for Excel 2013 Disabled Add-ins
  PASS > No Disabled items found.
Checking for Excel 2016 Disabled Add-ins
  PASS > No Disabled items found.

Attempting to load Excel Add-in: 
  PASS > Loaded Excel Add-in: DaxStudio, Version=2.6.0.76, Culture=neutral, PublicKeyToken=null

**Comment by chrisezard** [comment] 2017-06-29 08:53
1. AV software: Microsoft Endpoint Protection
2. Is this the problem?
Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
C:\Program Files\DAX Studio\DaxStudio.exe.config file not found.

**Comment by dgosbell** [comment] 2017-06-29 09:23
no, we only ever use the config file to override defaults, it runs fine without it. And this is the config file for the UI, it does not affect the Excel Addin.

I can't see anything out of the ordinary in the checker output. Its a bit of a long shot, but in Excel under File > Options > Trust Center if you open the "Trust Center Settings" and have a look under the "Add-ins" section - are all the options there un-ticked? (if any of them ticked this could cause issues)

**Comment by chrisezard** [comment] 2017-06-29 09:25
![image](https://user-images.githubusercontent.com/29733765/27680888-3914a620-5cb5-11e7-83c1-a883d7308414.png)

Policy Tips is checked, I'll try without it

**Comment by chrisezard** [comment] 2017-06-29 09:34
![image](https://user-images.githubusercontent.com/29733765/27681111-ff55ff96-5cb5-11e7-8aee-1afccb61e374.png)
Still get the same result, whether clicking on...
1. "Exectute DAX query"
2. "DAX Studio Excel Add-In"
3. "Tell me more"

**Comment by dgosbell** [comment] 2017-06-29 09:37
That screenshot of the Trust Center is for the "Message Bar" settings, you need to click on the "Add-ins" section in the left hand list. It should look like the following
![image](https://user-images.githubusercontent.com/8241830/27681391-6aeff49a-5d02-11e7-9699-6d03e88c71b4.png)

**Comment by chrisezard** [comment] 2017-06-29 09:40
Doh! All options are unchecked.
![image](https://user-images.githubusercontent.com/29733765/27681495-634c4c20-5cb7-11e7-9453-bcfb8ef76593.png)

**Comment by chrisezard** [comment] 2017-06-29 20:08
I installed PP Utilities today :1st_place_medal: , which helped me define the problem better.

Hovering over the DAX Studio icon in Add-Ins brings up a dialog with Caption, Add-In name (DAX Studio), "tell me more"
Hovering over the DAX Studio icon in PP Utilities brings up a dialog with Caption, Add-In name (PP Utilities), "tell me more"
Both lead to Excel 2016 help on Add-Ins https://user-images.githubusercontent.com/29733765/27681111-ff55ff96-5cb5-11e7-8aee-1afccb61e374.png

The problem is that when I press the DAX Studio button in either location NOTHING HAPPENS, so I was clicking around and following the prompt that leads to Excel help, no doubt intentionally.

I hope this helps to resolve the issue. Thanks for your help so far.
Chris

**Comment by chrisezard** [comment] 2017-07-02 19:43
I have uninstalled DAX Studio 2.6.0a, downloaded to from SQLBI again (this time the .zip file) and re-installed it. Still no joy - the Add-In is active but nothing happens when I click the DAX Studio icon.

Is an earlier version available that I could try? DAX Studio is well reviewed, it's future seems to be secure after the move to GitHub, and I'm keen to try the Performance features.

**Comment by dgosbell** [comment] 2017-07-02 20:30
The full history of all our downloads is available at [http://daxstudio.codeplex.com/releases](http://daxstudio.codeplex.com/releases) You can scroll through the list on the right hand side to go back to older releases. Although little has changed in the Excel Addin in the last year or so. 

Clicking on the tooltip explains where the help dialog was coming from, but we're still no closer to understanding why nothing happens when you click the button. 

I've tested with a bunch of colleagues from work and I've set up a couple of new virtual machines, installed Windows, Office and DAX Studio (so these VMs have no visual studio or local Analysis Services instances) and it always works as it should. 

The code for the add-in is heavily wrapped in error handling as it has no UI of its own. I'm looking at adding some more diagnostic logging for the next release so that maybe we can get closer to understanding exactly where in the code it stops working, but at the moment I have nothing to go on. It should work or throw an error, It's very frustrating as I can't see where it could fail without logging an error so unfortunately we have no idea what needs to be changed to fix this at the moment.

**Comment by chrisezard** [comment] 2017-07-02 20:35
Thanks for all your effort. It's the classic bug - absolutely nothing appears to be wrong apart from the software not working - I get it all the time :) Is there anything more about my set up you need to know? I am using Excel 2016 64-bit.

**Comment by chrisezard** [comment] 2017-07-02 20:56
Good - something has changed! I uninstalled 2.6.0.76 and installed 2.5.0, and it loads!
However, I can't load my model, see attached screenshot.
The 2.5.0 help does not refer to Excel 2016
![image](https://user-images.githubusercontent.com/29733765/27773418-2f50a77e-5f71-11e7-9491-519b7610e72b.png)

**Comment by dgosbell** [comment] 2017-07-03 22:51
That's interesting. I'll do some comparisons and see if I can track down the change between 2.5 and 2.6 that might have caused this.

Did you have your workbook open when you launched DAX Studio from Excel? The connection dialog looks like there was no workbook active in Excel for it to connect to.

**Comment by chrisezard** [comment] 2017-07-04 09:25
I launched DAX Studio from within a Power Pivot workbook. I get the same message as the previous image when opening it from other non-PP workbooks when the PP workbook is open but inactive. All of this was in Excel 2016.

**Comment by chrisezard** [comment] 2017-07-04 15:32
I have tested 2.6.0 with a colleague, who is running Excel 2013 32-bit, and it connects and runs.
So the problem is either 2016 or 64-bit or both. 
Hope this helps, Chris
![dax studio 2 6 0 connection](https://user-images.githubusercontent.com/29733765/27836164-2b062df4-60d6-11e7-8534-3194bd83ae78.png)
![dax studio 2 6 0 working](https://user-images.githubusercontent.com/29733765/27836169-2ec4fa56-60d6-11e7-95e8-514a266d439c.png)

**Comment by chrisezard** [comment] 2017-07-05 18:24
I have tested 2.6.0 with another colleague, who is also running Excel 2016 64-bit, which works fine!
Her set up...
![excel 2016 com add-ins 1](https://user-images.githubusercontent.com/29733765/27878576-9b8c1d64-61b6-11e7-8fa3-cfcfb1142dcd.png)
And mine...
![excel 2016 com add-ins 2](https://user-images.githubusercontent.com/29733765/27878588-a5348d24-61b6-11e7-8207-7db2d1578dd8.png)
1. Both are accessing DAX Studio in the same way
2. It makes no difference if I enable Power Maps + Power View (at least to DS 2.5 behaviour)
3. I notice the older style of the dialog box in my installation. Excel 2016 was installed on top of Excel 2013 on my machine, whereas it was a fresh install on my colleague's. I'll discuss with IT in the morning.

So, possibly, DAX Studio is fine (as suggested by your tests, and now mine too) but there's something wrong with my instance of Excel 2016.

**Comment by marcosqlbi** [comment] 2017-07-05 20:24
Another difference is that you have Windows 7 and your colleague has Windows 10, right?

**Comment by chrisezard** [comment] 2017-07-06 09:45
Yes, I have Windows 7 Enterprise and she has Windows 10 Enterprise

**Comment by chrisezard** [comment] 2017-07-06 11:32
This is a summary of the 4 different situations I have tested
[DAX Studio issue.pdf](https://github.com/DaxStudio/DaxStudio/files/1127686/DAX.Studio.issue.pdf)

**Comment by chrisezard** [comment] 2017-07-06 11:36
This is a summary of the 4 different situations I have tested - easier to view
![image](https://user-images.githubusercontent.com/29733765/27909227-9c5bc320-6247-11e7-9324-39e9a02e3495.png)

**Comment by chrisezard** [comment] 2017-07-07 14:40
Reading through all of this again it seems there are two users with the same problem, and both of us can get DAX Studio to work on other machines.

vbakh: "When I click Dax Studio on AddIn tab in Excel with a spreadsheet with PowerPivot loaded, it doesn't do anything."

chrisezard: "The problem is that when I press the DAX Studio button... NOTHING HAPPENS"

**Comment by vbakh** [comment] 2017-07-07 17:18
I recently reinstalled my machine and got the same results as earlier - clicking on DAX Studio in Excel doesn't do anything. I use Windows 10 64bit and Excel 2016 32Bit. I have SSMS 
The output from the DAX Studio Checker and SSMS versioning information are attached. 
[DaxStudioCkecker.txt](https://github.com/DaxStudio/DaxStudio/files/1131778/DaxStudioCkecker.txt)
![ssms](https://user-images.githubusercontent.com/24619419/27968867-972231c6-62fd-11e7-88d1-76bedb49fc72.png)

**Comment by chrisezard** [comment] 2017-07-07 18:12
Thanks for the update - I also have SSMS 17.1 installed. On Monday I will try uninstalling it. 

I am also considering going back to Excel 2013 to ensure the application I am developing works for all users, most of whom do not have 2016.

**Comment by dgosbell** [comment] 2017-07-11 04:46
This is the difficulty we are facing in resolving this issue, It only appears to happen on a small handful of machines. And unfortunately it's not simply a single configuration always failing (like 64bit Excel 2016). I've run tests previously on combinations of Windows 7/8/10 both 32 and 64 bit as well as Excel 2010/2013/2016 (but only about 7-8 combinations, not all possible 25). But we have a single code base and we don't do any special handling for operating system or 32 vs 64 bit. The only special code branch is for detecting the presence of a model for Excel 2010, but that only kicks in once the connection dialog opens. 

Have you tried re-installing 2.6 since installing 2.5? There is a reasonable chance that it was the act of re-installing that change something

**Comment by chrisezard** [comment] 2017-07-11 09:37
Yes, this must be frustrating! I know it is for me, because I really want to use DAX Studio!

Uninstalled 2.5, restarted computer, installed 2.6. Still no joy - same "nothing happens" behaviour.
I noticed this screen on installation, which I presume is correct?
![image](https://user-images.githubusercontent.com/29733765/28061952-52789e46-6624-11e7-98b7-361341475374.png)

The colleague whose installation is the closest match to mine also runs SSMS 17.1, so I think that is not likely to be the cause.

**Comment by dgosbell** [comment] 2017-07-11 10:27
Yes, that screen is normal. It gives the option not to install the Excel components if you don't want them (if you were installing on a machine that did not have Excel). We're working on adding a crash reporter and enhancing the error logging for the next release so hopefully that will give us some more information on what's happening.

**Comment by chrisezard** [comment] 2017-07-11 13:50
Good idea. When is the next release likely to be available?

**Comment by chrisezard** [comment] 2017-07-12 11:51
Deep joy! I now have a second laptop running Excel 2013 64-bit, and DAX Studio 2.6 works!!!
So I can develop in Excel 2013 and 2016, and I can use DS on one of the machines.

Thinking about your next release. Would it help if vbakh, myself and any other users with the same problem you are aware of, tested a beta version? You would see how well your new features worked, and hopefully you would learn enough to include the solution to this problem in the final release.

Best regards,
Chris

**Comment by dgosbell** [comment] 2017-07-13 20:21
@chrisezard  - yes, I was thinking that I might post a link to a beta version on the issues where people have report this issue and see if the new code helps to identify the issue. Hopefully I should have something out shortly, I just want to do some testing as a non-admin user to make sure none of the new code causes issues in that sort of environment.

**Comment by dgosbell** [comment] 2017-07-23 10:48
We still don't know what's causing this issue, but the beta of version 2.7 is available on my OneDrive here [https://1drv.ms/f/s!AnSKp2UbblSYgZlNWkrpq3eInReMNg](https://1drv.ms/f/s!AnSKp2UbblSYgZlNWkrpq3eInReMNg) It has a crash reporting component and if you hold down the left SHIFT key while starting Excel it should enable debug logging (more details can be found in the release notes in the OneDrive link

**Comment by serdarsoydemir** [comment] 2017-07-26 18:12
Hi all, I was suffering from the same issue with 2.6.0 and I have installed 2.7-beta version suggested above, and it works without problem. Thank you very much!

**Comment by dgosbell** [comment] 2017-07-26 20:25
Thanks for letting us know. I've been working with someone on one of the other issues raised about this problem on the old codeplex site and the logs he sent in helped isolate an issue so I had pushed a beta2 update to that OneDrive folder - when you run DAX Studio does it say 2.8.0.81 in the title bar or just 2.8.0 (I added the extra detail to the version in the title bar for the beta when I pushed out the Excel fix)

**Comment by serdarsoydemir** [comment] 2017-07-27 06:33
It says 2.8.0.81

**Comment by dgosbell** [comment] 2017-10-03 21:58
Should be fixed by the 2.7 release

**Closed by dgosbell** 2017-10-03 21:58 UTC
