### ISSUE TITLE
After Installing latest version of Excel, DAX Studio does not connect to PowerPivot

### ISSUE THREAD

**Issue by lbveselaj** [DaxStudio/DaxStudio#1012] opened 2022-12-22 17:22 UTC
After Installing latest version of Excel, DAX Studio does not connect to PowerPivot. I should mention that the version of Excel I am running is the Beta Version of O365 Personal. The error messages I see are the following: 

The following error occurred while updating the connection: The connection either timed out or was lost.
Error Connecting: The remote server returned an error: (500) Internal Server Error.

**Comment by dgosbell** [comment] 2022-12-22 21:23
I'm going to close this issue as it is a duplicate of #884 and you can subscribe to that issue if you want updates. This is a problem with the latest version of Excel. The Excel team have a fix coming and we are just waiting for it to be published.

**Closed by dgosbell** 2022-12-22 21:23 UTC
