### ISSUE TITLE
Exporting metrics issue when using a field parameter

### ISSUE THREAD

**Issue by DaniilMaslyuk** [DaxStudio/DaxStudio#879] opened 2022-07-22 05:39 UTC
<img width="746" alt="image" src="https://user-images.githubusercontent.com/10683126/180370500-4d20171b-621a-4afa-a616-3a62cd434abb.png">

**Comment by dgosbell** [comment] 2022-07-23 03:53
Hi @DaniilMaslyuk are you able to share a small demo model which reproduces this issue? 

I just tried to recreate it by adding multiple different types of parameters to an AdventureWorks pbix file and I could not reproduce this error. I added fields, measures, fields & measures and even a numeric range parameter to my demo file and could not trigger this error.

**Comment by DaniilMaslyuk** [comment] 2022-08-02 04:59
Hi @dgosbell, here's the file:
[879 sample file.zip](https://github.com/DaxStudio/DaxStudio/files/9239137/879.sample.file.zip)
I run DAX Studio 2.16.1 if it helps (cannot install a newer version yet)

**Comment by DaniilMaslyuk** [comment] 2022-08-02 05:04
Hi @dgosbell, here's the file:
[879 sample file.zip](https://github.com/DaxStudio/DaxStudio/files/9239152/879.sample.file.zip)
I run DAX Studio 2.16.1 if it helps (cannot install a newer version yet)

**Comment by dgosbell** [comment] 2022-08-03 01:29
Thanks @DaniilMaslyuk - I see it now. It's not actually blocking the collection of the metrics, but we do fall back to a less accurate DMV when issues like this happen. I've created pull request against the vertipaq-analyzer libraries from SQLBI with a fix for this. I've also fixed issues with tooltips and the Query Builder which were an extension of this issue. This will be part of the next major release.

**Comment by Loudal** [comment] 2022-08-15 21:13
Hi, I'm also having the same issue to use PBi Documenter, when its exports Vpax. Theres any perspective when it will be lauch the release?
![image](https://user-images.githubusercontent.com/59846829/184719422-cc0531f3-f459-45e2-85a7-fee7ebfe1680.png)

**Comment by marcosqlbi** [comment] 2022-08-16 04:26
Coming soon, weeks, not months :)

**Closed** 2022-08-24 09:53 UTC
Labels: fix-checked-in
