### ISSUE TITLE
dax studio can't connect excel365(2209)

### ISSUE THREAD

**Issue by lyliuyouyang** [DaxStudio/DaxStudio#921] opened 2022-09-03 08:35 UTC
DAX Studio v3.0.0.725
Connection: not connected

## Summary of Issue

DAX Studio v3 can't connect office365(the latest 2209) everytime

## Steps to Reproduce
1.DAX Studio v3 can't connect office365(the latest 2209) everytime

**Comment by dgosbell** [comment] 2022-09-03 09:37
Yes, this is a duplicate of #884 - Microsoft have changed something and I'm trying to figure out a fix. I'm going to close this issue as I'm tracking this problem in the earlier one

**Closed by dgosbell** 2022-09-03 09:37 UTC
