### ISSUE TITLE
Dax Studio does not connect in Excel 365 Beta channel.

### ISSUE THREAD

**Issue by Doonzu** [DaxStudio/DaxStudio#911] opened 2022-08-29 16:18 UTC
DAX Studio v3.0.0.725
Connection: not connected

## Summary of Issue
I'm a Korean.
When I open Dax Studio from the beta channel I registered to take advantage of the latest features in MS365 Excel, I get 'Connection timed out or lost connection', 'The remote server returned a (500) internal server error.' is displayed and there is no connection. If you cancel the Beta channel again and change to the current channel, you will be able to connect normally.

## Steps to Reproduce
1.
2.
![image](https://user-images.githubusercontent.com/107117213/187246571-1058768d-5b37-437c-87cb-7b69c9fb6922.png)
![image](https://user-images.githubusercontent.com/107117213/187247249-a25930de-a4ad-4544-a085-e48402744e87.png)

**Comment by marcosqlbi** [comment] 2022-08-29 16:42
It's the same issue we are discussing in #910

**Comment by dgosbell** [comment] 2022-09-02 02:00
This is a duplicate of #884 so I'm going to close this issue as I'm tracking this in the earlier issue.

This has something to do with changes in Excel and I'm in contact with someone on the Excel team to try and resolve this.

**Closed by dgosbell** 2022-09-02 02:00 UTC
