### ISSUE TITLE
Server Timings wait spinner gets stuck when clicking Clear Cache button

### ISSUE THREAD

**Issue by Minova2018** [DaxStudio/DaxStudio#469] opened 2020-11-26 09:41 UTC
**Describe the bug**
After starting Server Timings and hitting "Clear cache" the spinner in the Server Timings pane doesn't stop spinning

**To Reproduce**
1. Open DAX Studio
2. Connect to a Power BI Desktop data model
3. Start Server Timings
4. hit the "Clear cache" button

**Expected behavior**
The Server Timings spinner should not get stuck

**Comment by dgosbell** [comment] 2020-11-26 11:35
Can you provide some more information about this issue? Are you seeing an error? What sort of data source are you connected to?

This may be a duplicate of #456

**Comment by Minova2018** [comment] 2020-11-26 13:36
I am connected to a Power BI model.



On 26 Nov 2020, at 12:35, Darren Gosbell <notifications@github.com> wrote:

﻿

Can you provide some more information about this issue? Are you seeing an error? What sort of data source are you connected to?

This may be a duplicate of #456<https://github.com/DaxStudio/DaxStudio/issues/456>

**Comment by dgosbell** [comment] 2020-11-26 21:41
OK, so I assume you are using Power BI Desktop. I just double checked and this worked without error for me. What error message are you getting?

**Comment by dgosbell** [comment] 2020-11-27 05:07
Oh I see you edited the original issue description to say that you see a spinner. But I still can't reproduce this. And the spinner most likely means we are waiting for the data engine to respond.

Does it happen with all Power BI files for you or just a certain one? 

Can you upload a file that exhibits this behaviour to this issue? Or can't upload the pbix can you run the View Metrics and export a .vpax file and attach that?

**Comment by Minova2018** [comment] 2020-11-27 14:10
It happens with all PBI files. I just noticed, however, that the spinner keeps running while I'm in the Server timings tab. In the output tab it does say "Cache cleared for database"

**Comment by dgosbell** [comment] 2020-11-28 01:21
OK so the fact you had Server Timings running and that you are talking about the spinner on that pane is new information. So this is not actually a bug with the Clear Cache button (as you can see in the output pane the clear cache command worked). This is a UI glitch on the Server Timings pane. 

This is an over simplification, but basically it "sees" a command sent to the data source and it's waiting for the query results to return, but there are no results from a clear cache, so it waits forever. 

I should be able to fix the event filtering to stop the spinner animation starting when it's a clear cache command. 

### Work Around
But in the mean time the work around is to simply ignore this. The "Run Query" button will not activate until the Clear Cache is complete and the next query that you run will reset the spinner and will still capture the timings correctly.

**Comment by dgosbell** [comment] 2020-11-28 11:29
I now have a fix checked it, this will be part of the next release. When we publish the next release github will automatically close this issue.

**Closed** 2021-01-18 09:23 UTC
Labels: bug, fix-checked-in
