### ISSUE TITLE
Excel add-in is not displayed after DAX Studio is installed

### ISSUE THREAD

**Issue by xiaohaha1** [DaxStudio/DaxStudio#902] opened 2022-08-26 05:23 UTC
**Describe the bug**
The Excel add-in is not displayed after DAX Studio is installed. DAX Studio Checker-Enable VSTO Alerts, the error information is displayed as follows , I partially masked the file path. Please help to check the problem, thanks

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excelv16
    Excel Path: 
    Excel Architecture: Unknown

      ERROR: Unsupported Excel Architecture Unknown
    DAX Studio Excel Add-in Registry keys
       Description: DAX Studio Excel Add-In
       FriendlyName: DAX Studio Excel Add-In
       Manifest: file:///C:/Program Files/DAX Studio/bin/DaxStudio.vsto|vstolocal
       LoadBehavior: 3

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      N/A  >  - \\10.180.55.121\public\业务杂文件\**\**\4.29 第二单\4.29第二单未使用数据(20210805 ***usd).xl

      PASS >  Found Excel Addin: Microsoft Power Pivot for Excel

    Attempting to load Excel Add-in: 
      PASS > Loaded Excel Add-in: DaxStudio, Version=3.0.0.725, Culture=neutral, PublicKeyToken=null

    Checking VSTO Configuration
    Architecture: x64
      v4
        Version 10.0.60828
        Install 1
        InstallerPath c:\Program Files\Common Files\Microsoft Shared\VSTO\10.0\VSTOInstaller.exe
      v4M
        VSTOMFeature_UNM 1
        VSTOMFeature_CLR35 1
        VSTOMFeature_CLR40 1
      v4M_2052
        VSTOM_res_UNM 1
        VSTOM_res_CLR35 1
        VSTOM_res_CLR40 1

Registry Settings
=======================
    CurrentDownloadVersion = 3.0.0.725
    LastVersionCheckUTC = 2022-08-26T02:45:01Z
    WindowPosition = ﻿<?xml version="1.0" encoding="utf-8"?><WINDOWPLACEMENT xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><length>44</length><flags>0</flags><showCmd>1</showCmd><minPosition><X>-1</X><Y>-1</Y></minPosition><maxPosition><X>-1</X><Y>-1</Y></maxPosition><normalPosition><Left>49</Left><Top>10</Top><Right>2289</Right><Bottom>1450</Bottom></normalPosition></WINDOWPLACEMENT>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dgosbell** [comment] 2022-08-27 05:15
This is a duplicate of #865 so I'm going to close this as we are tracking this fault there. But I still don't know what causes this as we don't appear to have any error messages. It could be IT security policies blocking the addin or something that has changed in Excel recently.

**Closed by dgosbell** 2022-08-27 05:15 UTC

**Comment by xiaohaha1** [comment] 2022-08-27 07:13
Thank you very much for your reply. I tried to install it many times, and finally I succeeded when I chose to use it only for myself
