### ISSUE TITLE
Server Timings Trace dont start in 2.16.1, Timeout

### ISSUE THREAD

**Issue by nexus150** [DaxStudio/DaxStudio#664] opened 2021-07-02 12:14 UTC
**Describe the bug**
Server Timings Trace fail to start in SSAS On Premise 2019 or 2017 (1500 or 1400) 

**To Reproduce**
1. Open Dax Studio
2. Connect to an tabular model in ssas tabular 2019 or 2017  
3.Click on Server Timings
4. See error ("Timeout exceeded attempting start the trace")

**Expected behavior**
Server timings trace start

**Screenshots**
![image](https://user-images.githubusercontent.com/11592309/124272869-9d18c180-db3f-11eb-86bd-a58a907e6ff3.png)

**Additional context**
i make the test with 2.15.0 and it works fine

**Comment by dgosbell** [comment] 2021-07-03 01:04
Thanks for reporting this. We have already been investigating this issue. But the tracing seems to work in some scenarios and not others which is why it was not picked up earlier. There was one minor internal change in preparation for another feature I'm working on which may have contributed to this problem. 

I think I have a fix for this issue, but the inconsistent nature of the problem is making it hard to know for sure. 

If you don't mind would you be able to test the following preview build and let me know if that fixes the issue for you?
https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/39828643/artifacts

**Comment by nexus150** [comment] 2021-07-03 19:46
Hello Darren, i did the tests, and in that preview, the trace starts and
works perfectly, in both, SSAS Tabular 2017 and 2019, thank you very much.

**Comment by NickCodesDotNET** [comment] 2021-07-05 14:50
Darren. Looks like you got it all figured out but I would like to confirm that indeed Server Timings is buggy for the current DAX Studio 2.16.1 release. Won't connect.

**Comment by dgosbell** [comment] 2021-07-13 05:31
This is fixed in v2.16.2

**Closed by dgosbell** 2021-07-13 05:31 UTC
Labels: bug
