### ISSUE TITLE
Recovered queries execute different query

### ISSUE THREAD

**Issue by ccparkhill** [DaxStudio/DaxStudio#1126] opened 2023-05-25 08:51 UTC
We have VMs which are shut down each evening, when I reopen DAX Studio the following day and recovery my queries and then create a new query it will attempt to execute one of the recovered queries instead, so the result set can be totally unrelated to the query I'm trying to execute or it won't run at all because the query was intended for a different model.

**Comment by dgosbell** [comment] 2023-05-25 09:33
I've tried to reproduce this by killing DAX Studio from Task Manager, but it only ever runs the currently active document as expected. Can you provide detailed, step by step instructions of what you are doing? 

I don't reconnect recovered files automatically as they only have the query text and there are no details of what the active connection was and you could have been connected to PBI Desktop or Power Pivot and that model may not currently be available.

**Comment by ccparkhill** [comment] 2023-05-26 11:10
Perhaps try shutting down your machine with DAX Studio open?

Once I restart the VM:
1. Open DAX Studio
2. Open Recovered Files
3. Create a new query
4. Execute query

**Comment by dgosbell** [comment] 2023-05-27 13:28
Are you running v3.0.7 or an earlier version?

**Comment by ccparkhill** [comment] 2023-05-30 08:50
3.0.7.

Thanks,

**Comment by dgosbell** [comment] 2023-05-30 09:51
hmm, I still cannot reproduce this at all. Can you try the following:

1. Go into File > Options > Logging and turn the level up to Verbose
2. The next morning see if you can reproduce this issue.
3. If the issue manifests itself open the log folder (there is a link in the Help > About dialog)
4. Close DAX Studio to make sure it flushes out all the events to the log file
5. Upload the log file with the current date to this issue on Github

**Comment by ccparkhill** [comment] 2023-05-30 10:23
Thanks, I have enabled that. I notice that I create a new query which is "Query1.dax" but it actually executes the recovered "Query1.dax". I also get the following error when I create a new query (not sure if that's related):
Error refreshing table list: Value cannot be null. Parameter name: key

Thanks,

**Comment by dgosbell** [comment] 2023-05-30 22:19
The name of the tabs is not relevant to this, the active tab is tracked internally using an object reference. The other error is unusual, but probably not relevant to the active tab issue.

**Comment by ccparkhill** [comment] 2023-05-31 09:33
[DaxStudio-20230531.log](https://github.com/DaxStudio/DaxStudio/files/11611136/DaxStudio-20230531.log)
Hi, please find attached. Thanks

**Comment by dgosbell** [comment] 2023-06-02 09:05
Thanks for the log file. I can see what is happening now, so I should be able to track the sequence of events and figure out a fix.

**Comment by dgosbell** [comment] 2023-07-03 01:16
This should be fixed in the 3.0.8 release

**Closed by dgosbell** 2023-07-03 01:16 UTC
Labels: bug, fix-checked-in
