### ISSUE TITLE
Excel Add-in fails to launch DAX Studio

### ISSUE THREAD

**Issue by ulawe** [DaxStudio/DaxStudio#698] opened 2021-08-13 22:34 UTC
&emsp;The IT Support installed **DAX Studio** 2.15.0 on my work laptop, but the Excel add-in fails to launch **DAX Studio** with the error:
> The following Error occurred while trying to launch the DAX Studio User Interface
> Access is denied

&emsp;Even though the location _file:///C:/Program Files/DAX Studio/bin/DaxStudio.vsto|vstolocal_ is trusted in _Trust Center_, the add-in does not load when first selected in Excel's _COM add-in_ list. However, restarting Excel activates the _Add-ins_ ribbon and the **DAX Studio** icon becomes visible.
&emsp;When starting **DAX Studio** separately, the _PowerPivot Model_ data source is inactive.
&emsp;I am running **Excel 2016** v.16.0.5188.1000 from a 64bit **Office** install under **Windows 10 Enterprise** 20H2 build 19042.1110.
&emsp;My IT has given up, so I would greatly appreciate your help.

Thank you!

**Comment by ulawe** [comment] 2021-08-13 22:41
* Running **DAX Studio Checker** shows _PASS_ for all items except for _WARNING: No Registry settings found_.

**Comment by dgosbell** [comment] 2021-08-14 02:23
>  When starting DAX Studio separately, the PowerPivot Model data source is inactive.

Yes this is the expected behaviour, only Excel and Excel add-ins can "talk" to the PowerPivot engine. 

> Running DAX Studio Checker shows PASS for all items except for WARNING: No Registry settings found.

As it says, this is just a warning. It could indicate that you have not changed any default settings (I don't save non-default settings). Or it could be that your IT department has somehow blocked the ability for DAX Studio to access the registry

> My IT has given up, so I would greatly appreciate your help.

This is unfortunate as this issue is most likely caused by some policy your IT department has put in place and they would need to change whatever it is that they have done in order to fix this.

An "access denied" error is a permissions issue and there is no way that I can bypass or work around restrictions put in place by your IT department.  They would need to check the Windows Event Viewer or the AV logs or they could try using the sysinternals Process Monitor tool to try and diagnose what permissions are being denied so that they can fix them.

This error has come up once before (see https://github.com/DaxStudio/DaxStudio/issues/489#issuecomment-766188658) and it turned out to be an overly aggressive anti-virus  program. But this could potentially be caused by changes to permissions in the registry or the file system or by an app locker implementation or by group policy settings.

**Comment by dgosbell** [comment] 2021-08-27 23:44
I don't think there is any action I can take from my end to resolve this issue so I'm going to close it. If you have extra information to add or think there is some other way I can help feel free to re-open this or create a new issue

**Closed by dgosbell** 2021-08-27 23:44 UTC

**Comment by ulawe** [comment] 2022-07-21 23:02
Thank you @dgosbell for your fast reply. My IT support used your suggestion yesterday and was able to fix my issue. You were right. It turned out that Windows Defender had a corporate rule preventing creation of child processes.
