### ISSUE TITLE
Excel Add In is not enabling

### ISSUE THREAD

**Issue by akhawar** [DaxStudio/DaxStudio#510] opened 2021-01-19 15:11 UTC
I am using Microsoft 365 Apps for enterprise. Installed the 2.14.0 version yesterday and was getting an error when trying to enable the Add In. 
This morning, I have installed the 2.14.1 version that is supposed to fix it. I do not see the error but DAX studio does not show up in Excel. When I go back to my Com Add Ins, the add in shows unchecked. I have tried to check the box and relaunch Excel multiple times but it goes back to unchecked

**Comment by FrankFromGermany** [comment] 2021-01-19 15:53
I can confirm that the Excel Add-In is still (2.14.1) not working with Microsoft 365 Apps for enterprise (latest insider version)

**Comment by dgosbell** [comment] 2021-01-19 21:46
So the 2.14.0 version threw an error on load - it was a release build issue which I was able to reproduce and then work around. But I'm not seeing any issues on any of my machines with 2.14.1 so we are going to need to see if we can gather more details to figure out what is going on.

Can you go into File -> Options -> Add-ins and check the Disabled Items and make sure DAX Studio is not in there? If it is you need to manually re-enable it from that dialog.

If that does not help make sure that all copies of Excel are closed then try doing an uninstall / re-install of DAX Studio. (it's probably worth opening task manager and making sure there are no hidden excel.exe processes running)

If it's still not loading then if you run DaxStudio.Checker.exe (which should be in the folder where DAX Studio is installed) then in the file menu is an option to *Enable VSTO Alerts* if you close all your Excel windows, then enable this, then open Excel and try to enable the addin (if it's not already enabled) this should show an alert if Excel is having issues loading the addin

**Comment by akhawar** [comment] 2021-01-20 00:44
Thanks for the responses. It has now appeared in my Excel after I stopped trying (enabled it 4-5 times). Seems tobe working fine now. Not sure what fixed it as i had restarted earlier and that had not enabled it. 

Thanks,
Ali

**Comment by dgosbell** [comment] 2021-01-20 01:11
@akhawar - thanks for letting me know. That is very strange I have no idea why the Excel addin sometimes misbehaves like that. I have seen hidden/crashed excel.exe processes cause issues with the PowerPivot and DAX Studio addins not enabling, but a reboot would definitely clear that.

**Comment by FrankFromGermany** [comment] 2021-01-20 10:14
@dgosbell - I ran DAXStudio.Checker and got no alerts.

Nonetheless, although the add-in was registered to load on startup, it did not appear in Excel under add-ins (com) at all.

Reinstallation, restarting, removing all other add-ins, etc did not help.

Thus, I decided to reinstall 2.13.1. With this version I've had no problems at all, but now it did not appear as well.

This got me thinking and I tried to install the add-in just for me and not for all users (as recommended).

Now, it works. What was different is that this time a screen appeared asking me whether I really want to install the VSTO. This screen did never appear when I tried to install for all users.

Maybe, this makes sense for you.

I love your add-in and I'm glad I got it working.

**Comment by dgosbell** [comment] 2021-01-20 11:24
> I ran DAXStudio.Checker and got no alerts.

@FrankFromGermany  - you will not see any alerts in DaxStudio.Checker itself. You use that tool to change a setting that should cause Excel to display an alert if it runs into an error while loading an add-in. But since it's working now that is not really necessary.

> What was different is that this time a screen appeared asking me whether I really want to install the VSTO. This screen did never appear when I tried to install for all users.

That would be expected, the digital certificate used to sign previous versions has expired. I had to get a new one issued so Excel should prompt to ask if you trust the add-in again since it's signed with a new certificate. You should only get asked once if you trust code signed with a given certificate and the new one is valid for 3 years. But as far as I am aware it should to that for either an all users or a current user install

**Comment by dgosbell** [comment] 2021-03-19 05:42
I'm going to close this issue now since you have found a work around

**Closed by dgosbell** 2021-03-19 05:42 UTC
