### ISSUE TITLE
Can not get power pivot model from Excel

### ISSUE THREAD

**Issue by korsar75** [DaxStudio/DaxStudio#291] opened 2020-02-19 05:20 UTC
When I run Dax Studio and try to connect my Excel file with PowerPivot Table I see error message (see screenshoot).
![Connect To 2020-02-19 15 09 33](https://user-images.githubusercontent.com/61220657/74804937-73d20980-532d-11ea-824f-cc315b46b09f.jpg)

I'm using Win7 Professional Service Pack 1 64 bit, Excel 2010 64 bit

Also I can not connect to PB file. Error is "Путь содержит недопустимые знаки". It's in russian (I'm from Russia). In English is "Path contains wrong (incorrect) symbols"

I'm not well in English so... I try to do the best to help solve the problem.
Thank you in advance

[DaxStudio-20200219.log](https://github.com/DaxStudio/DaxStudio/files/4223247/DaxStudio-20200219.log)

**Comment by dgosbell** [comment] 2020-02-19 05:36
Is your file stored in a OneDrive folder? There seems to an issue connecting to xlsx files that are stored in OneDrive folders. If this is your situation the only work around I have at the moment is for you to copy the file to a folder on a local drive.

And what version are you running? There were some issues in older versions if your file path had certain special characters, but this should be fixed in the current release.

**Comment by korsar75** [comment] 2020-02-19 05:48
Hi.

File is stored on local drive. In My Documents folder.
I'm using latest version of Dax Studio (2.10.2)

**Comment by dgosbell** [comment] 2020-02-19 08:36
As long as the file with the PowerPivot model in it is saved to a location that is **not** a http(s);// address  it should work fine.

Can you follow the steps [here](https://daxstudio.org/documentation/troubleshooting/logging-settings/) - holding down the SHIFT key while starting Excel, to enable debug logging. Then start DAX Studio and try to connect and then shut down DAX Studio and Excel and attach the resulting log files to this issue on Github.

**Comment by korsar75** [comment] 2020-02-19 22:35
Hello
Here it is
[DaxStudioExcel-20200220.log](https://github.com/DaxStudio/DaxStudio/files/4227838/DaxStudioExcel-20200220.log)
[DaxStudio-20200220.log](https://github.com/DaxStudio/DaxStudio/files/4227839/DaxStudio-20200220.log)

**Comment by dgosbell** [comment] 2020-02-20 23:27
@korsar75 thanks for the logs, this looks like an issue with one of the assembly bindings just for Excel 2010. I've updated these in a preview build [here](https://ci.appveyor.com/api/buildjobs/t953fp68fu7ac78n/artifacts/package%2FDaxStudio_2_10_3_setup.exe) can you test this and see if it is working now?

**Comment by korsar75** [comment] 2020-02-21 06:53
Ok, I'll try

**Comment by korsar75** [comment] 2020-02-24 23:28
Hello I ran new version and still have a problem.
![Connect To 2020-02-25 08 50 37](https://user-images.githubusercontent.com/61220657/75200308-17e60580-57b1-11ea-9e27-5b0db988f012.jpg)
[DaxStudio-20200225.log](https://github.com/DaxStudio/DaxStudio/files/4247347/DaxStudio-20200225.log)

**Comment by dgosbell** [comment] 2020-02-24 23:44
Can you run the diagnostic logging for Excel again and post the DaxStudioExcel log file?

**Comment by korsar75** [comment] 2020-02-24 23:53
[DaxStudioExcel-20200225.log](https://github.com/DaxStudio/DaxStudio/files/4247415/DaxStudioExcel-20200225.log)

**Comment by dgosbell** [comment] 2020-02-25 02:45
Ok, so this is now a different error so the assembly binding issue appears to be resolved. It looks like this might be caused by something in Excel, either one of your other add-ins or maybe some sort of dialog box or window open. I have not seen any reports of anything like this before. Did you have any other windows open in Excel at the time? If you try to close and open DAX Studio a few times does it work eventually or does it always fail? (I'm wondering if adding some retry logic would help here)

**Comment by korsar75** [comment] 2020-02-26 03:03
Hi
I ran only one Excel copy. And open file with Power Pivot table only.
When I open Dax studio I can see that Dax studio trying to connect to workbook. Please look at screenshot, please
![DaxStudio - 2 10 3 257 (PREVIEW) 2020-02-26 10 47 32](https://user-images.githubusercontent.com/61220657/75303644-0bcf7600-588d-11ea-96e7-2fddbd403008.jpg)
But Dax studio can not connect in result.
And Dax Studio does not see any open workbook
![Connect To 2020-02-26 11 29 29](https://user-images.githubusercontent.com/61220657/75307580-cc5a5700-5897-11ea-9ee8-10fe3757f286.jpg)
In this book I use Power Query to gets data for Power Pivot. Power query connects to files from local network
I try to open another file with Power Pivot. File has xlsm extension. End Dax studio sees this workbook but does not see any Power Pivot table. See screenshot
![Connect To 2020-02-26 11 30 39](https://user-images.githubusercontent.com/61220657/75307808-61f5e680-5898-11ea-83f3-e6152313c540.jpg)

**Comment by korsar75** [comment] 2020-02-27 02:49
Hi
I ran only one Excel copy. And open file with Power Pivot table only.
When I open Dax studio I can see that Dax studio trying to connect to workbook. Please look at screenshot, please
![DaxStudio - 2 10 3 257 (PREVIEW) 2020-02-26 10 47 32](https://user-images.githubusercontent.com/61220657/75303644-0bcf7600-588d-11ea-96e7-2fddbd403008.jpg)
But Dax studio can not connect in result.
And Dax Studio does not see any open workbook
![Connect To 2020-02-26 11 29 29](https://user-images.githubusercontent.com/61220657/75307580-cc5a5700-5897-11ea-9ee8-10fe3757f286.jpg)
In this book I use Power Query to gets data for Power Pivot. Power query connects to files from local network
I try to open another file with Power Pivot. File has xlsm extension. End Dax studio sees this workbook but does not see any Power Pivot table. See screenshot

**Comment by dgosbell** [comment] 2020-04-18 23:16
Sorry for the delay, I was just checking back through the open issues.

Can you try temporarily disabling any other addins and just having DAX Studio active?

Can you try with a plain xlsx file instead of an xlsm file?

The error in the logs is saying that Excel was busy, I've never seen this before and I'm not sure what else it is on your system that could be causing this.

**Comment by dgosbell** [comment] 2020-06-11 06:57
The new release v2.11.0 has some extra re-try logic which may help with this issue. Can you try that and see if it works?

**Comment by dgosbell** [comment] 2020-07-28 23:51
closing due to lack of response

**Closed by dgosbell** 2020-07-28 23:51 UTC
Labels: awaiting reply
