### ISSUE TITLE
Error when returning query output to static excel

### ISSUE THREAD

**Issue by NickM273** [DaxStudio/DaxStudio#897] opened 2022-08-25 11:39 UTC
DAX Studio v3.0.0.725
Connection: PowerBIDesktop - 16.0.36.23
When choosing to export query to Static Excel file there's an error in the log and the excel file will not open

## Summary of Issue
Ran a simple query
```
EVALUATE 
ROW("test",Now()) 
```
Returns the expected:
![image](https://user-images.githubusercontent.com/43351746/186653619-1684e0ac-183f-4bc4-8a8c-da0eeee31c14.png)

But when exporting to Static Excel file seems to produce an error, though the actual excel file will still be created:
![image](https://user-images.githubusercontent.com/43351746/186654190-1c2f45c9-583b-486f-99b8-c11cf59ed91b.png)

When trying to open the actual excel file you get this error:
![image](https://user-images.githubusercontent.com/43351746/186654308-a9e83527-3edb-4650-a487-e3f577da49e3.png)

Exporting to File doesnt produce the same error. 

## Steps to Reproduce
1. Change the output to Static Excel File
2. Run Query
3. Try to open the produced excel file

**Comment by suemareverton** [comment] 2022-08-25 12:28
duplicate of #891

**Comment by dgosbell** [comment] 2022-08-25 21:54
Thanks @NickM273 - I'm tracking this problem issue in #891 so I'm going to close this as a duplicate. I hope to have a fix out shortly

**Closed by dgosbell** 2022-08-25 21:54 UTC
