### ISSUE TITLE
mesure defined on dax studio's Query Editor cannot be written back to the excel2016 data model

### ISSUE THREAD

**Issue by dqaudithillstone** [DaxStudio/DaxStudio#246] opened 2019-11-13 05:52 UTC
1. mesure defined on dax studio's Query Editor cannot be written back to the excel2016 data model.
but mesure defined on  excel2016 data model can displayed to the dax studio's Query Editor
2. code  can't  auto prompt when defining measure

**Comment by dgosbell** [comment] 2019-11-13 06:08
> mesure defined on dax studio's Query Editor cannot be written back to the excel2016 data model. but mesure defined on excel2016 data model can displayed to the dax studio's Query Editor

Yes, this is by design DAX Studio only creates a read-only connection to a data model. And with Excel data models Microsoft does not support write back from External tools (I have attempted this and it crashes Excel and corrupts the file)

> code can't auto prompt when defining measure

This is one of the known issues with our current (very basic) parser. I'd like to re-build this at some point, but this requires a major time investment so it's not likely to happen any time soon. It's lines that start ```MEASURE ...``` or ```DEFINE MEASURE ...``` that it does not like. So one work around is to put the expression for your measure on a different line, then the intellisense should start functioning again.

**Comment by dqaudithillstone** [comment] 2019-11-13 08:05
thanks a lot 
if have this feature which writing back to excel feature ,it will be  a beutiful thing

**Comment by dqaudithillstone** [comment] 2019-11-13 09:50
code can't auto prompt when defining measure

thanks a lot, 
So one work around is to put the expression for your measure on a different line, then the intellisense should start functioning again.
e. g. 
define measure  
'orders'[recnum]=
if you add line break after "define measure", then the intellisense should start functioning again.

**Comment by dgosbell** [comment] 2019-11-13 10:45
> thanks a lot
if have this feature which writing back to excel feature ,it will be a beutiful thing

It would, but given that it is not possible I am going to close this issue.

**Closed by dgosbell** 2019-11-13 10:45 UTC
Labels: idea
