### ISSUE TITLE
M Engine error - System.Data No support for MSDASQL

### ISSUE THREAD

**Issue by Iviglious** [DaxStudio/DaxStudio#644] opened 2021-06-07 18:01 UTC
**Bug description**
When clicking on the Advanced -> View Metrics for a 2019 model I get the following error:
```
07/06/2021 18:59:02		Establishing Connection
07/06/2021 18:59:56		Updated Model Metadata detected
07/06/2021 18:59:56		Error viewing metrics with ReadStatisticsFromData enabled (retry without statistics): M Engine error: 'System.Data; The .Net Framework Data Provider for OLEDB (System.Data.OleDb) does not support the Microsoft OLE DB Provider for ODBC Drivers (MSDASQL). Use the .Net Framework Data Provider for ODBC (System.Data.Odbc).'.
07/06/2021 18:59:57		Metadata Refreshed
07/06/2021 18:59:57		Metadata Refreshed
07/06/2021 19:00:27		Error viewing metrics: One or more errors occurred.
	M Engine error: 'System.Data; The .Net Framework Data Provider for OLEDB (System.Data.OleDb) does not support the Microsoft OLE DB Provider for ODBC Drivers (MSDASQL). Use the .Net Framework Data Provider for ODBC (System.Data.Odbc).'.
```

**To Reproduce**
1. Open the Dax Studio 2.15.0 app in my laptop.
2. Connect to a 2019 Tabular AS server.
3. Select a 1500 Tabular model.
4. Click on Advanced menu -> View Metrics button
5. The error is printed in the log and no metrics are shown.

**Expected behavior**
Metrics (stats) are displayed just like for other models (1200 level).
When I try with 1200 models (in the same 2019 server) this error is not displayed.

**Additional context**
Client OS: Windows 10 Enterprise 20H2
Dax Studio: v2.15.0
SQL Server: Microsoft SQL Server 2019 (RTM-CU8) (KB4577194) - 15.0.4073.23 (X64)   Sep 23 2020 16:03:08   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor) 
Test model: compatibility level 1500, using one connection to a datasource (via ODBC) in Legacy mode.

Here is a screenshot from Visual Studio 2019 on how to enable Legacy data sources:
![image](https://user-images.githubusercontent.com/5268602/121056871-91dbab80-c7b6-11eb-9b61-8cb502d310be.png)

And the configuration of the Data Source (using a Presto cluster via Qubole):
![image](https://user-images.githubusercontent.com/5268602/121067651-37951780-c7c3-11eb-80b9-df787d63f218.png)

**Comment by dgosbell** [comment] 2021-06-11 05:14
This is definitely not related to the 1500 compatibility mode as I have a number of models using that and higher. Is this an in-memory model or direct query? I can't think of any reason why the data provider would be triggered for an in-memory model.

**Comment by Iviglious** [comment] 2021-06-17 16:33
Hi @dgosbell,
It's in-memory model.
I noticed that for the model I tested in the connection provider the value is actually `MSDASQL.1`:
![image](https://user-images.githubusercontent.com/5268602/122437810-fa364400-cf91-11eb-96e2-1a74db0833b3.png)
I changed it to `MSDASQL` and the DAX Studio error stopped appearing.
Why is DAX Studio so sensitive about this?

**Comment by dgosbell** [comment] 2021-06-17 23:16
I'm not sure why the Microsoft engine is behaving like this. We are only querying the in-memory data using supported APIs so you should even be able to back up the database, restore it to a completely different server without any access to the source systems and the view metrics should still work. I can't think of anything that should be affected by anything in the data source for an in-memory model.

If you still have a model that produces this error can you hold down the shift key while starting DAX Studio to enable the [diagnostic logging](https://daxstudio.org/documentation/troubleshooting/logging-settings/) then reproduce this error then close DAX Studio and post the resulting log file back to this issue? That should tell me which part of the metric collection routines is triggering this message.

**Comment by Iviglious** [comment] 2021-06-22 16:39
Yeah, I understand, but looks like the connector used to extract the stats.
See attached the debug log file here: [DaxStudio-20210622.log](https://github.com/DaxStudio/DaxStudio/files/6695944/DaxStudio-20210622.log)
The first error topic says: `DocumentViewModel ViewAnalysisData Error loading VPA view with ReadStatisticsFromData enabled`
And then the issue seems to be in `PopulateReferences()` function `at Dax.Metadata.Extractor.DmvExtractor.PopulateReferences()` which for some reason calls `ExecuteTabular()`.
Possibly the issue is with the `Microsoft.AnalysisServices.AdomdClient`. Which version do you use?
Can we address it with MS?

**Comment by dgosbell** [comment] 2021-06-22 22:20
So the populate references issues the following query
```
SELECT DISTINCT 
    REFERENCED_OBJECT_TYPE, 
    REFERENCED_TABLE, 
    REFERENCED_OBJECT 
FROM $SYSTEM.DISCOVER_CALC_DEPENDENCY
```

If you run that same query in DAX Studio I'm assuming you will see the same error. I am currently using version 19.22 of the AdomdClient library, but I do not believe the issue is in the client library. You should be able to run the same query in SSMS and see the same error.

If you see this M Engine error just running the query above  then this is almost certainly a bug in SSAS 2019 and you would need to raise a support ticket with them to get this looked into. If you are not running the latest cumulative update for SQL Server it cold be worth testing that on a dev server if you can as it's possible that this issue has been fixed since MS has had a number of issues with the DISCOVER_CALC_DEPENDENCY call over the years.

**Comment by Iviglious** [comment] 2021-06-23 18:11
Thanks @dgosbell 
Yes, the query fails with the same error when I run it from SSMS.
I see latest CU is 11 and mine is CU8.
I noticed this page: https://docs.microsoft.com/en-us/analysis-services/client-libraries?view=asallproducts-allversions contains the latest versions of MS libraries including Adomd, so I though I might try upgrading these libraries in attempt to fix this issue.

**Comment by dgosbell** [comment] 2021-06-24 04:31
I'm almost certain this is not a client library issue. v2.16 of DAX Studio is using the same version of Adomd that is currently listed on that site (19.22.01). Try running an All Queries trace, then click on View Metrics. If you see this error as an ERR line in the All Queries trace that will prove that this is a server side error in SSAS 2019.

**Comment by dgosbell** [comment] 2021-06-24 22:14
> I was thinking of installing the libraries on the server (fix the server) and on my laptop too.

The server does not use these libraries so installing Adomd there will not change anything. And DAX Studio includes a local copy of those libraries and will not use the ones installed in the GAC (Global Assembly Cache) since most people have outdated versions in the GAC.

If the error is visible in the All Queries trace then only a CU update or a hotfix from Microsoft Support can fix it.

**Comment by Iviglious** [comment] 2021-06-25 18:00
Installed the latest CU11. The issue is still present. The libraries are still the old ones. Next step: Update the libraries.

**Comment by dgosbell** [comment] 2021-06-26 00:01
If you go into Help > About in DAX Studio and click on **Show Details** it will list all the libraries we load and their versions. There are a bunch in there as that list includes the core Microsoft .net system libraries, but the are sorted alphabetically so you will find it under `Microsoft.AnalysisServices.AdomdClient` - you should already see 19.22.0.1 on the client side if you are using DAX Studio 2.16.0

**Comment by Iviglious** [comment] 2021-06-30 16:40
I just installed DAX Studio 2.16.1 and this error is not appearing.
I tested with the original 2019 CU8 server (didn't installed any updates/libraries) and works.
Whatever was added to that version it fixed this issue.

**Comment by dgosbell** [comment] 2021-07-01 03:44
> I just installed DAX Studio 2.16.1 and this error is not appearing.
> I tested with the original 2019 CU8 server (didn't installed any updates/libraries) and works.
> Whatever was added to that version it fixed this issue.

There were no updates to 2.16.1 that would have impacted this issue. 2.16.1 just contained 3 UI fixes there were no changes to the View Metrics code or to the underlying Microsoft Libraries. Are you sure nothing was changed on the data model?

But since this seems to have been a server side issue and it's no longer happening I think I will close this issue

**Closed by dgosbell** 2021-07-01 03:44 UTC
Labels: awaiting reply
