### ISSUE TITLE
Turkish character, Date and deciable number problem

### ISSUE THREAD

**Issue by emrah2321** [DaxStudio/DaxStudio#444] opened 2020-10-27 11:45 UTC
Hi all, when I do Esport Data (CSV), it converts the date format to text, and the deciable number replaces the comma with a period. Can you please help if the Turkish format is distressed. I uploaded the sample files.

[Power Pivot.xlsx](https://github.com/DaxStudio/DaxStudio/files/5444957/Power.Pivot.xlsx)
[Orjinal.xlsx](https://github.com/DaxStudio/DaxStudio/files/5444958/Orjinal.xlsx)
[Export CSV.zip](https://github.com/DaxStudio/DaxStudio/files/5444961/Export.CSV.zip)

**Comment by dgosbell** [comment] 2020-10-28 07:25
> when I do Esport Data (CSV), it converts the date format to text

CSV is a text based format. We do force all dates to the ISO8601 standard format "YYYY-MM-DD hh:mm:ss.nnnn" so that they can be easily read in by other applications. Is that what you are talking about here when you say "converts the format to text"?

> and the deciable number replaces the comma with a period

This is a bug. The export code is not currently referencing the current culture on the PC correctly. This will be fixed in the next release.

**Comment by emrah2321** [comment] 2020-10-29 21:38
Date format "GG.AA.YYYY" csv converts to "YYYY-AA-GG ss: dd: ss.nnnn". Therefore, it does not look in Date format, but in Text format.

**Comment by dgosbell** [comment] 2020-10-29 22:30
> Date format "GG.AA.YYYY" csv converts to "YYYY-AA-GG ss: dd: ss.nnnn". Therefore, it does not look in Date format, but in Text format.

Yes, this is by design. All datetime columns are exported in ISO8601 format which is an international standard. This is the best format to use when exporting to text based file formats like CSV. Using any other format can result in the day and month fields being swapped when the data is imported into another programs.

**Comment by emrah2321** [comment] 2020-10-29 22:57
Okay, I get it, thank you. Will there be a fix for the other problem?

**Comment by dgosbell** [comment] 2020-10-30 06:31
Yes the fix for the other problem is checked in to our source code and it will be part of the next release.

If you are interested in testing a preview build you could try the current preview build from our build server here: [https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/36018912/artifacts](https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/36018912/artifacts)

It would actually be quite helpful as I'm pretty sure I've fixed the issue, but I have not had time to build a VM with different regional settings so that I could test this.

**Comment by emrah2321** [comment] 2020-11-01 00:05
Oh, thank you. I'll wait for the new version.

**Closed** 2020-11-02 05:15 UTC
Labels: bug
