### ISSUE TITLE
DAX Studio Logo Issue with latest relaease

### ISSUE THREAD

**Issue by saeed-numan** [DaxStudio/DaxStudio#966] opened 2022-09-27 05:10 UTC
DAX Studio v3.0.3.762
Connection: PowerBIDesktop - 16.0.44.29

## Summary of Issue

I have installed latest release of DAX Studio but DAX Studio logo not appearing in task bar and even in Desktop shortcut and I did the reinstallation as well and figured out it's something wrong with application...please find the attached screenshot for your reference. Thanks
![image](https://user-images.githubusercontent.com/105913263/192437005-f26deef2-2770-4477-8373-59b51bf1144a.png)

![image](https://user-images.githubusercontent.com/105913263/192437111-771c5a4a-60a0-4634-8fe9-0e3ef88bd680.png)

## Steps to Reproduce
1. Even after clean new installation 
2. Still

**Comment by dgosbell** [comment] 2022-09-27 05:35
Thanks for logging this, it is a duplicate of #963 and has already been fixed in the 3.0.5 release.

**Closed by dgosbell** 2022-09-27 05:35 UTC

**Comment by saeed-numan** [comment] 2022-09-27 11:05
Thanks
