### ISSUE TITLE
Opening Static Excel Output results in Excel Format Error/Repair Prompt

### ISSUE THREAD

**Issue by hwaeltken** [DaxStudio/DaxStudio#694] opened 2021-08-04 15:50 UTC
**Describe the bug**
When I export the DAX Studio output to Excel (Static) and then open the resulting Excel file, Excel registers an error, offers to repair the file and provides an error message around the XML Styles file. After repair the file works however.

**To Reproduce**
1. Select Output as "Static"
2. Output a Table in DAX Studio
3. Open the output Excel

**Expected behavior**
Excel should open without any errors

**Screenshots**
![DAXStudioStaticOutputExcelError](https://user-images.githubusercontent.com/17462584/128211849-879a3291-71d1-4904-a061-3ce03aabce61.jpg)

![DAXStudioStaticOutputExcelError_XMLStyle](https://user-images.githubusercontent.com/17462584/128211899-6a0b4bb3-0294-44b3-90ea-58694dffb7ba.jpg)

**Additional context**
Running Microsoft Excel 365 Version 2102 with DAXStudio PowerPivot and Acrobat Plugins

XML Error File reads the following:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>error128200_04.xml</logFileName><summary>Errors were detected in file 'G:\My Drive\Henrik\HR\DATA\PowerBIDAX\RHDTenure2021-03-31.xlsx'</summary><repairedRecords><repairedRecord>Repaired Records: Format from /xl/styles.xml part (Styles)</repairedRecord></repairedRecords></recoveryLog>

**Comment by dgosbell** [comment] 2021-08-04 22:40
I cannot reproduce this error using the steps provided. 

What version of DAX Studio are you using? How many rows & columns are in your output?

**Comment by dgosbell** [comment] 2021-08-27 23:42
Unable to reproduce this. Closing due to lack of response. If you have further information to add feel free to re-open this issue or create a new one

**Comment by hwaeltken** [comment] 2021-08-28 15:31
Darren, my apologies, your response from April did not register in my inbox
until now. I will check on studio version, but I believe it was the most
recent one available in April.  The tables are less than 50,000 rows, often
less than 1,000. Less than 50 columns.

I will test with another machine. I'm wondering if this is related to the
presence of other excel plug ins.


Regards,


Henrik

**Comment by dgosbell** [comment] 2021-08-28 23:47
No worries, I just don't like leaving issues open if I cannot reproduce the issue and I don't have any answers to help isolate the issue. 

I've just re-tested this feature using v2.16.2 with 999,999 rows and 20 columns and it produced a 96Mb file which opened without issue. I'm using a library called LargeXlsx to generate the Excel files, but the only similar issue I can see on their list is for files over 4Gb and that is meant to be fixed in the version of the library I'm using in v2.16.2. So it's possibly something specific in the content that is being written out. Have you had a look in the log file that was produced? Does that give any hints as to what the corruption was?

**Comment by dgosbell** [comment] 2021-11-15 09:35
Unable to reproduce this. Closing due to lack of response. If you have further information to add feel free to re-open this issue or create a new one

**Closed by dgosbell** 2021-11-15 09:35 UTC
Labels: awaiting reply
