### ISSUE TITLE
Unable to connect Dax Studio with Power Pivot

### ISSUE THREAD

**Issue by rtyaseen** [DaxStudio/DaxStudio#947] opened 2022-09-20 04:58 UTC
After updating the new version of Dax studio 3.0, I am not able to connect to my Data model in excel
I can connect Dax with power BI but not with Excel.

I have attached the error message so please help out to solve this issue.

<img width="302" alt="DAX Studio Error" src="https://user-images.githubusercontent.com/113963583/191170975-d82d656b-1513-4eb9-b9e6-20e179534b80.png">

**Comment by dgosbell** [comment] 2022-09-20 05:42
this is a duplicate of #884 so I'm going to close this issue and you can follow the progress and updates on #884

**Closed by dgosbell** 2022-09-20 05:42 UTC

**Comment by rtyaseen** [comment] 2022-09-20 07:08
Thanks for prompt response .

I would like to get your suggestion to re-install DAX studio for previous version as this issue started with new update of DAX studio 3.0

**Comment by dgosbell** [comment] 2022-09-20 07:24
This appears to be due to a bug in a recent Excel update so I don't think installing an older version will make any difference since I did not change any code in the addin for the v3 release.
