### ISSUE TITLE
Problem to generate metrics

### ISSUE THREAD

**Issue by nayronsilva** [DaxStudio/DaxStudio#574] opened 2021-03-18 13:15 UTC
**Describe the bug**
When I try to generate metrics of my  data base i recieve an error as you can see in my screen shot.

**To Reproduce**
1. Go to 'Advanced'
2. Click on 'View Metrics'

**Expected behavior**
Generate the metrics of the selected data base.

**Screenshots**
![image](https://user-images.githubusercontent.com/51278181/111631595-55f60300-87d2-11eb-83ae-d1104718d967.png)

**Comment by dgosbell** [comment] 2021-03-18 20:57
Duplicate of #549 - I'm going to close this issue as it is a Microsoft bug and we are tracking it on the original issue (which has a few workarounds) You can subscribe to the original issue to get informed of any updates.

**Closed by dgosbell** 2021-03-18 20:57 UTC
