### ISSUE TITLE
Enhancement - Add DaxStudio option to hide hidden tables/columns/measures

### ISSUE THREAD

**Issue by jm98** [DaxStudio/DaxStudio#167] opened 2019-03-15 14:39 UTC
As a developer
I do not want to see hidden items within the metadata model tree
So that I can remove visual clutter and concentrate on the entities that are published in the metadata to clients apps

Given the DaxStudio option "ShowHiddenItems" is FALSE
When I navigate the metadata model tree hierarchy
Then I shall not see any items that have their "IsHidden" property set to TRUE
And I shall not see  the children of each element that has its "IsHidden" property set to TRUE

Given the DaxStudio option "ShowHiddenItems" is TRUE (default value)
When I navigate the metadata model tree hierarchy
Then I shall shall see everything within the metadata model tree

**Comment by dgosbell** [comment] 2019-03-15 20:51
Duplicate of #159 (also raised by you :) ) but I might close that one as the title of this issue more clearly summarizes this suggestion.

**Comment by jm98** [comment] 2019-03-16 10:14
Sorry for the duplication  A senior moment

**Comment by dgosbell** [comment] 2019-06-03 05:11
Added in v2.9.0

**Closed by dgosbell** 2019-06-03 05:11 UTC
Labels: idea
