### ISSUE TITLE
View Metrics button does nothing

### ISSUE THREAD

**Issue by mwc360** [DaxStudio/DaxStudio#235] opened 2019-10-23 19:25 UTC
Clicking View Metrics after loading a model shows in the bottom left corner for a second that it was analyzed but no window pops up to show the metrics

**Comment by dgosbell** [comment] 2019-10-24 22:32
What sort of model is this (PowerPivot/Power BI Desktop/ SSAS / AzureAS)? Do you get this behaviour with other models or just with one specific model?

**Comment by dgosbell** [comment] 2019-10-26 05:34
Was there any message logged in the output pane?

**Comment by matthiastns** [comment] 2019-10-30 08:26
I have the same issue. It said it was working in the lower left status bar, but there was no Vertipaq tab at the end (only a few seconds). I now see that it works like charm with a different pbix. The one I tried first is a rather big model. I analyzed this bigger model earlier by using Vertipaq stand-alone (and was able to reduce it to 2/3 of size, thanks a lot) but it does not work from within DAX Studio. When I tried it now again after the successful test with a smaller pbix, it still does not work (although it said it was working in the status bar to the lower left) the succesful results from the smaller file remain in the Vertipaq window.

**Comment by dgosbell** [comment] 2019-10-30 09:55
@matthiastns So I have the same question as I asked the previous poster - Was there any message logged in the output pane when the view metrics did not work?

**Comment by matthiastns** [comment] 2019-10-30 12:53
Sorry, I should have mentioned it right away: There is nothing visible happening beside the message in the status bar "Analyzing model metrics" for  a few seconds and then "Ready". That's it. Nothing changes, the tabs remain empty as before.

**Comment by dgosbell** [comment] 2019-10-31 12:07
I'm not sure yet what is causing this, but I did find one hole in our error trapping. There is a preview build available on our build server [here](https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/28512060/artifacts) If you try this version it should hopefully report the error that is causing the metrics not to display. You can either use the installer or you can try the new portable version. To run the portable version you just download the zip file, unzip it to a folder and run the daxstudio.exe.

**Comment by KavasiMihaly** [comment] 2019-11-01 10:31
Hi,
Same here. Power BI Desktop model/nothing in the output/fairly larger model (almost 1 gb)/works fine with other models.

**Comment by KavasiMihaly** [comment] 2019-11-01 10:33
Tried with an other larger data model same. I same somehow the size of the model affects this issue.

**Comment by marcosqlbi** [comment] 2019-11-01 10:41
The size by itself is not enough because it works on models that are several GB in size. There is probably something else involved in the large model that fails. Did you try using the preview build as Darreng suggested in a previous message?

**Comment by dgosbell** [comment] 2019-11-01 11:02
@KavasiMihaly is this with the 2.9.4 release or the new preview build?

**Comment by KavasiMihaly** [comment] 2019-11-01 11:04
> @KavasiMihaly is this with the 2.9.4 release or the new preview build?

Hi it is with 2.9.4, will try the preview when I have a bit of time.

**Comment by hermesjrd** [comment] 2019-11-01 13:20
Hi Guys in my case the 2.9.5 (preview) work beautifully with all my Power BI projects. let me know If I can be help.

**Comment by dgosbell** [comment] 2019-11-02 08:35
@hermesjrd - so are you saying that you were having the issue reported in this thread and 2.9.5 fixed it? We've fixed a few other issues in 2.9.5, but I don't think we've fixed this one as it appears to be bypassing our existing error trapping.

**Comment by matthiastns** [comment] 2019-11-04 07:28
Hi There.
Sorry, I was offline the last 4 days (lucky me). 
I tried the portable Preview 2.9.5 on the pbix that is cuasing the problem. It did not work, but now it sends an lengthy error message to the output window. Unfortunately, I did not find a way to copy the output, so I took a screenshot.
![DAXStudio_ViewMetrics_Error_Output](https://user-images.githubusercontent.com/12641636/68104871-0369be80-fedd-11e9-9270-efe583ba06fc.PNG)

**Comment by marcosqlbi** [comment] 2019-11-04 09:38
Maybe the problem is some column name with the " character - I will investigate on it.

**Comment by marcosqlbi** [comment] 2019-11-04 11:00
I am able to reproduce the bug and pushed a fix to the VertiPaq Analyzer libraries. The next release of DAX Studio should have the fix included.

**Comment by adriantheuma** [comment] 2019-11-14 05:11
I am also having the same issue on a pbix file. There are no columns that have quotation marks that I know of. Is there a time frame for the release of the next version of DAX studio? Cheers,

**Comment by marcosqlbi** [comment] 2019-11-14 05:20
Please try this pre-release and let us know if it works or if you see a more detailed error: https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/28512060/artifacts

**Comment by KavasiMihaly** [comment] 2019-11-14 09:22
Hi, Tried the preview on 2 of the files that did not worked previously with 2.9.4. It works now :)

**Comment by peterbud** [comment] 2019-11-14 13:31
I have had the same issue with 2.9.4, but it works perfectly with the pre-release 2.9.5

**Comment by andyparkerson** [comment] 2019-11-14 18:31
# Overview
1. View Metrics didn't do anything (2.9.4)
2. Installed MSOLAP (x86) and AMO libraries
3. View Metrics works

# Description
I clicked View Metrics and nothing happened. I clicked Export Metrics. If it gave me the error "Error exporting metrics: The 'MSOLAP' provider is not registered on the local machine".

A post on the PowerBI Community by DavidKress points to the Microsoft Docs, which link me to the Azure Analysis Services libraries. I downloaded MSOLAP (x86), which didn't solve the problem, and then AMO, which ultimately did.

# Quick Links
- https://docs.microsoft.com/en-us/azure/analysis-services/analysis-services-data-providers
- https://community.powerbi.com/t5/Power-Query/HELP-The-MSOLAP-8-provider-is-not-registered-on-the-local-machin/td-p/594831)

**Comment by dgosbell** [comment] 2019-11-14 19:36
@andyparkerson - we found that bug where it was looking for the installed versions of MSOLAP/AMO in the latest preview builds, so it's not going to be necessary to do this going forward.

**Comment by adriantheuma** [comment] 2019-11-15 00:55
> Please try this pre-release and let us know if it works or if you see a more detailed error: https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/28512060/artifacts

Works well in 2.9.5 PREVIEW. Thank you.

**Comment by Shart243** [comment] 2019-12-09 23:59
Hi - just fyi, the 2.9.5 preview fixed my issue as well.  We use multi-factor authentication enabled on the Active Directory.  Thanks for your efforts here!

**Comment by dgosbell** [comment] 2019-12-20 00:27
This should now be fixed in the 2.10 release

**Closed by dgosbell** 2019-12-20 00:27 UTC
Labels: bug, fix-checked-in
