### ISSUE TITLE
Intelisense window hanging

### ISSUE THREAD

**Issue by ezinder** [DaxStudio/DaxStudio#643] opened 2021-06-03 22:54 UTC
DAX Studio v2.15.0.525
Connection: AnalysisServices - 15.0.34.27

## Summary of Issue
Intelisense pop-ups keep hanging over the editor text when query is improperly formatted. 

## Steps to Reproduce
1.   Write a "SUMMARIZECOLUMNS" statement like so: 
--------------------------------------------------------------------------
EVALUATE
SUMMARIZECOLUMNS (
    'Date'[Year],
    FILTER ( 'Date', 'Date'[Year] >= YEAR ( TODAY () ) - 3 ),
    "count 1", COUNTROWS ( 'Sales' )
)
------------------------------------------------------------------------------    
 
2.  add another line below the "count 1" , but do not add a "," at the end of the line. 
3. Any DAX function that prompts an intelisense window, will remain on the screen 
4. To remove the intelisense window, add new lines (\n) at the bottom of the query editor until the window scrolls past the pop-up visible view

**Comment by dgosbell** [comment] 2021-06-04 02:38
Sorry but I cannot reproduce this issue at all. I have seen issues where the code completion (intellisense) window sticks sometimes or any empty tooltip gets stuck, but I have not been able to figure out what triggers this. Often hitting the ESC key or clicking on a different tab then back will clear this. If I could figure out how this state gets triggered I could fix it, but it's a mystery at the moment.

Note the code completion in DAX Studio does not do a full parse of the entire statement (which is why we don't currently support variables) instead we do a single line parse so any text above or below the line you are typing on should not have any effect on the code completion options.

**Comment by dgosbell** [comment] 2021-06-05 03:02
If you can consistently reproduce this issue are you able to spot any other things that may help me reproduce this on my end? Or if you have the capability possibly even record a screen capture of the issue as I might help me spot what is triggering this

**Comment by SharmaAntriksh** [comment] 2021-06-05 14:54
@dgosbell  I think I figured why the empty window appears, if you place the cursor at a spot where the IntelliSense window will show up later then you can reproduce the error as shown below:

I have recorded audio with the demo:

https://user-images.githubusercontent.com/73054674/120895708-d8f16180-c63b-11eb-883a-39c490504efc.mp4

**Comment by dgosbell** [comment] 2021-06-06 03:22
Thanks @SharmaAntriksh  I think you may have found the issue. I had not been paying attention to the mouse position and I think the code completion window popping up under the mouse is the extra variable in this behaviour that I was missing. The standard behaviour of the completion window for the edit control I am using does not allow any mouse interaction so I've extended it slightly. But it looks like there is a bug when the window pops up under the mouse as opposed to the mouse moving over the window deliberately. I'm testing a fix for this now.

@ezinder  although it could be related I'm not sure if this is the same issue you are seeing. The video @SharmaAntriksh captured matches exactly with the bug I've observed, but I cannot replicate the behaviour you have describe where you have to enter new lines repeatedly to clear off the stuck window.

**Closed** 2021-06-22 01:41 UTC
Labels: bug, fix-checked-in
