### ISSUE TITLE
DAX Studio throws an unexpecyted

### ISSUE THREAD

**Issue by iColomboA** [DaxStudio/DaxStudio#802] opened 2022-02-15 09:20 UTC
DAX Studio v2.17.3.683
Connection: PowerBIDesktop - 16.0.5.24

## Summary of Issue
DAX Studio desn't work when a DAX query with direct query is tested (copied out form Power BI analyzer)

## Steps to Reproduce
1. open Power BI and start performance analyzer 
2. copy the the DAX query with direct query pieces to DAX studio and run it
3. the error "The syntax for DEFINE is incorrect" is thrown on the first line of the direct query section

**Comment by marcosqlbi** [comment] 2022-02-15 10:54
This is by design. The query that appears with Define is sent to the remote dataset and should not be executed on the local model. You should remove it and the message that appears when you paste the query should already warn you about that. If you keep both queries, only the first one can be executed locally - internally, the engine generates the query that is sent to the remote dataset. Performance Analyzer show all the queries (local and remote), but you only have to execute the local one in DAX Studio, the engine generates and send the other query to the remote dataset.

**Comment by dgosbell** [comment] 2022-02-16 02:59
I'm going to close this issue, since as Marco pointed out we already have the "Multiple Queries Detected" warning which explains this issue when pasting a query from Performance Analyzer that includes the remote query.

**Closed by dgosbell** 2022-02-16 02:59 UTC

**Comment by iColomboA** [comment] 2022-02-17 07:45
Sure!
