### ISSUE TITLE
DAX Query with IN clause

### ISSUE THREAD

**Issue by iprins** [DaxStudio/DaxStudio#386] opened 2020-07-22 14:41 UTC
When I enter `{1, 2}` in the popup window to enter my list in DAX Studio, I receive the following error:
 
`Query (1, 78) The  function expects a table expression for argument '2', but a string or numeric expression was used.`

I used the following basic query using an IN clause. Any idea how I should go about this? 

```
DEFINE VAR CustomerId = @CustomerId 
EVALUATE 
CALCULATETABLE( 
Customers, 
Customers[Id] IN @CustomerId 
)
``` 

Using the following expression directly
`EVALUATE CALCULATETABLE( Customers, Customers[Id] IN {1,2} )` works just fine.

**Comment by dgosbell** [comment] 2020-07-22 22:22
So this issue is not really specific to DAX Studio, any client tool that supports parameters will behave in the same way. 

The problem is that parameters are pass through as strings, so if you pass in `1,2  `
`EVALUATE CALCULATETABLE( Customers, Customers[Id] IN "1,2" )`

And even if you pass in `{1,2}` it will just be evaluated as
`EVALUATE CALCULATETABLE( Customers, Customers[Id] IN "{1,2}" )`

So people generally use an approach of pipe delimiting your list of IDs then using PATHCONTAINS
see [https://prologika.com/ssrs-multivalue-parameters-in-dax/](https://prologika.com/ssrs-multivalue-parameters-in-dax/)

So you could do something like
```
DEFINE 
VAR CustomerPath = SUBSTITUTE(@CustomerId, ",", "|")
EVALUATE 
FILTER( 
Customers, 
PATHCONTAINS(CustomerPath , Customers[Id] ) 
)
```

Or slightly more complicated, but better performing versions of this approach [https://blog.crossjoin.co.uk/2018/05/16/a-new-approach-to-handling-ssrs-multi-valued-parameters-in-dax-queries/](https://blog.crossjoin.co.uk/2018/05/16/a-new-approach-to-handling-ssrs-multi-valued-parameters-in-dax-queries/)

**Comment by dgosbell** [comment] 2020-07-28 07:34
I'm closing this as I'm assuming the previous reply answered your question, feel free to re-open if not.

**Closed by dgosbell** 2020-07-28 07:34 UTC

**Comment by iprins** [comment] 2020-07-28 07:37
Yes, it answered my question. Thank you.
