### ISSUE TITLE
Error opening metrics: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by mark-endicott** [DaxStudio/DaxStudio#1125] opened 2023-05-23 12:25 UTC
I receive this error when trying to import one particular VPAX file, others I am able to successfully, there was no indication of error when I exported it, and the only difference I can see in it to the ones that open is that it's around 100KB smaller than the files I have no issue with. 

Is there a way to recover this file?

**Comment by marcosqlbi** [comment] 2023-05-23 12:55
It would be nice to be able to reproduce the issue.
For the recovery - did you open it with Vertipaq Analyzer?
https://www.sqlbi.com/tools/vertipaq-analyzer/

It would be nice to reproduce the issue so we can fix it in DAX Studio.

**Comment by mark-endicott** [comment] 2023-05-23 13:57
Hi @marcosqlbi 

When opening with Vertipaq Analyzer I receive:

Run-time error '1004'

An issue with the Data Model is preventing Microsoft Excel from opening this workbook. Try restarting Microsoft Excel.

**Comment by marcosqlbi** [comment] 2023-05-23 20:01
Is there any chance you can share a VPAX file that produces this error?

**Comment by marcosqlbi** [comment] 2023-05-24 10:49
I sent you an email, let me know in case you didn't receive it.

**Comment by dgosbell** [comment] 2023-08-23 23:32
I did fix an issue related to an error when opening vpax files in the latest release. Are you able to check if this works now in 3.0.10?

**Comment by mark-endicott** [comment] 2023-08-29 10:57
@dgosbell - I'm afraid this vpax file will still not open on the new version.

**Comment by dgosbell** [comment] 2023-09-01 05:33
Then this must be a different issue, were you able to share the file with @marcosqlbi ? I don't have any vpax files throwing this error so it's hard to know what is causing it.

**Comment by marcosqlbi** [comment] 2023-09-01 07:07
From our investigation, the process terminated before completing the save operation. Mark was not able to provide more details about what happened during save, but the file is corrupted and cannot be recovered. We made some improvements to the library to reduce the possible corruption caused by exceptions. I would close this case as we are not able to do much else for that.

**Closed** 2023-09-01 07:29 UTC
Labels: bug
