### ISSUE TITLE
Error when export to static excel file

### ISSUE THREAD

**Issue by amarines2605** [DaxStudio/DaxStudio#923] opened 2022-09-05 14:34 UTC
DAX Studio v3.0.0.725
Connection: AnalysisServices - 14.0.249.70

## Summary of Issue
Error when export to static excel file
final excel file with 0 bytes
Error showed "The type initializer for 'PerTypeValues`1' threw an exception"

## Steps to Reproduce
1. Open .dax file
2. Select menu Results to Static Excel
3. Click on Run
4. Error is showed

**Comment by dgosbell** [comment] 2022-09-05 20:23
Thanks for reporting this issue. But this is a duplicate of #891 and I'm tracking this problem there so I'm going to close this one.

**Closed by dgosbell** 2022-09-05 20:23 UTC
