### ISSUE TITLE
Hidden Objects = False Dax Studio Wont Start Again

### ISSUE THREAD

**Issue by spacy0508** [DaxStudio/DaxStudio#457] opened 2020-11-10 05:50 UTC
After initially connecting to the local pbix file and setting the Hidden Objections flag to off in the Options screen, you cannot open or Launch Dax Studio again after closing it down.

**To Reproduce**
1. Open a 'pbix' and connect using PBI/SSDT Model.
2. Click on File --> Options --> Metadata Pane on the Standard Tab.
3. De-select the 'Show Hidden Columns, Tables and Measures option.
4. Click on Back Button to go back to editor. 
At this point the hidden objects are removed as you would expect.
5. Close Dax Studio and Try to Launch it again.

**Expected behavior**
I would expect it to request connection details if no default connection exist and show that the Hidden Objects have not loaded in the Left Pane of the Editor. However the Dax Studio application fails and generates the error log. The only way to get it up and running again, is to search for the registry key that holds the 'options' information and setting the flag back to true.

**Screenshots**
The following screen appears for about a second and then closes. I have also uploaded the log file.
![image](https://user-images.githubusercontent.com/28419344/98632564-79fc9000-236b-11eb-9930-dd6dd885baa5.png)
[DaxStudio-20201110.log](https://github.com/DaxStudio/DaxStudio/files/5515084/DaxStudio-20201110.log)

**Additional context**
The registry associated with the flag that will need to be reset to 'false' to get Dax Studio running again.
![RegistryKey](https://user-images.githubusercontent.com/28419344/98632901-22aaef80-236c-11eb-8812-d3452de4fe6c.png)

**Comment by dgosbell** [comment] 2020-11-10 06:51
Thanks for logging this issue. Thanks to your clear repro steps I was able to quickly find the root cause of this issue and I've checked in a fix which will be part of the next release.

**Comment by spacy0508** [comment] 2020-11-10 08:25
Cheers. That's great.

**Closed** 2021-01-18 09:23 UTC
Labels: bug, fix-checked-in
