### ISSUE TITLE
Ability to Export columns from All Queries results

### ISSUE THREAD

**Issue by scabral79** [DaxStudio/DaxStudio#299] opened 2020-03-26 13:38 UTC
**Is your feature request related to a problem? Please describe.**
When using DAX Studio to capture queries from another source (i.e Power BI, SSRS, etc), it would be beneficial if we could export the results to a csv or excel file for analysis

**Describe the solution you'd like**
Build in the ability to export the results of the All Queries tab when capturing DAX queries and timings against a certain SSAS instance

**Describe alternatives you've considered**
the only option now is to just manually scroll through the results or do a screen print and save the results to an image for future reference

**Additional context**

**Comment by dgosbell** [comment] 2020-03-27 04:59
Closing as this is an exact duplicate of issue #277

**Closed by dgosbell** 2020-03-27 04:59 UTC
Labels: duplicate, idea
