### ISSUE TITLE
Need some help to find out why i cant load Dax (Method Not Found ReadAsAsync)

### ISSUE THREAD

**Issue by SJ119** [DaxStudio/DaxStudio#259] opened 2019-11-29 19:14 UTC
First time using Dax. Just intalled it and trying to launch Dax Studio through Excel.
Keep getting the following error.
11/29/19 11:13:27 AM		Method not found: 'System.Threading.Tasks.Task`1<!!0> System.Net.Http.HttpContentExtensions.ReadAsAsync(System.Net.Http.HttpContent)'.

[DaxChecker.txt](https://github.com/DaxStudio/DaxStudio/files/3906248/DaxChecker.txt)

**Comment by dgosbell** [comment] 2019-12-03 04:28
This looks like a duplicate of #229. Unfortunately I can't reproduce this issue and the error message does not make any sense.

The excel addin works on all the machines that I currently have access to including the machines of a number of work colleagues. I had wondered if this was caused by an installer issue/corruption, but I had one of the users zip and upload their ```c:\program files\dax studio``` folder and the code runs on my machine and the Microsoft library containing the ReadAsAsync method was the correct version and the method was present.

I might try re-building this functionality to avoid using this particular library to see if this fixes this issue or at least provides an actionable error message. But at the moment I am a bit stumped as this issue seems to be machine dependant, but I can't figure out why.

**Comment by dgosbell** [comment] 2020-01-20 23:51
Can you checked if this issue still exists with the 2.10.2 release?

**Comment by SJ119** [comment] 2020-01-21 17:38
Hi.
Installing V. 2.9.2 seems to have fixed this issue.
Sorry i didnt reply on the thread earlier.
Thanks,
Soheb

**Closed** 2020-07-28 23:52 UTC
Labels: awaiting reply
