### ISSUE TITLE
Intellisense is not working - Ver. 2.13.1

### ISSUE THREAD

**Issue by CaveofW0nders** [DaxStudio/DaxStudio#462] opened 2020-11-18 11:35 UTC
**Describe the bug**

Intellisense is no longer working? I have it ticked in settings. I have tried downgrading to the previous version, but it's still not working.

**To Reproduce**
1. Type the name of a function or table name and see if it works.

**Expected behavior**
Table/function name completion.

**Comment by dgosbell** [comment] 2020-11-18 11:56
It is still working, but something does seem to break it occasionally. Unfortunately I have not figured out what triggers it to stop working so it is extremely hard to fix. The once or twice I have seen it break I've tried to follow the same series of actions, but I am unable to make it stop working a second time.

**Comment by CaveofW0nders** [comment] 2020-11-18 12:17
Thank you Darren; this is quite frustrating as I'm sure you can appreciate. Are there any general recommendations/steps I can take to try and get it working again, even something as simple as restarting my computer etc...

**Comment by dgosbell** [comment] 2020-11-19 00:48
I don't think a restart would help. The intellisense is internal to the edit control and each document has it's own instance of the edit control - the few times I've seen the intellisense break it was possible to open a second document and the intellisense would work in the second window even though it remained broken in the first one.

It's possible this issue is a variation of #451 but I can't check for sure as I don't have a reliable way of reproducing this issue. But it feels to me like I have not seen this issue on my dev branch since fixing #451 

If you wanted to test a preview build that includes this fix you can download one from the link below
https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/36169040/artifacts

I'd be interested to hear if that helps with this issue.

**Comment by CaveofW0nders** [comment] 2020-11-19 09:11
Hi Darren, something stranged happend this morning. I tried what you suggested i.e., opening a second document and started typing EVALUATE and intellisense managed to complete the word, however, immediately after that it stopped working and then DAX Studio crashed.

Below are the error messages that I recieved.:

![dax](https://user-images.githubusercontent.com/71261762/99645329-fb78b000-2a46-11eb-85b4-1ab5988c6f96.JPG)

![dax2](https://user-images.githubusercontent.com/71261762/99645351-00d5fa80-2a47-11eb-8fcd-3fec44ec448d.JPG)

![dax3](https://user-images.githubusercontent.com/71261762/99645365-04698180-2a47-11eb-8903-395d080626ee.JPG)

**Stack Trace**:

\n   at System.Windows.Media.Visual.PointToScreen(Point point)
   at ICSharpCode.AvalonEdit.CodeCompletion.CompletionWindowBase.UpdatePosition()
   at System.Windows.Window.OnLocationChanged(EventArgs e)
   at System.Windows.Window.WmMoveChangedHelper()
   at System.Windows.Window.WmMoveChanged()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by CaveofW0nders** [comment] 2020-11-19 09:30
When I downloaded the preview version, it initially worked. After closing and opening it again it has stopped working. The only error message I recieved was:

![Dax](https://user-images.githubusercontent.com/71261762/99647487-c6ba2800-2a49-11eb-9c0f-8493d0da56d2.JPG)

**Comment by dgosbell** [comment] 2020-11-19 11:09
So the "Visual is not connected to a PresentationSource" is a bug in the edit control we use. It seems to be some sort of race condition an only happens very rarely. I have only received a small number of these crashes.  A pull request has been raised [here](https://github.com/icsharpcode/AvalonEdit/pull/148) which looks like it should fix this issue, but this has not been rolled into an official release yet.

The other issues I've never seen before. 

What sort of data source are you connecting to? Do you see the metadata pane populate?

If these error are repeatable can you hold down the shift key while starting DAX Studio - this should generate a [diagnostic log file](https://daxstudio.org/documentation/troubleshooting/logging-settings/) if you could then attach this log file to this issue on github it might give me some hint as to what is going on.

> Note: Intellisense works for inbuilt functions but does not autocomplete tables, column names, or variables.

Note we don't support autocomplete for variables as we don't have a full DAX parser we just use some light weight heuristics, but the tables, columns and measures should work.

**Comment by CaveofW0nders** [comment] 2020-11-19 11:45
> What sort of data source are you connecting to? Do you see the metadata pane populate?

Connecting to a PBI file, from within power bi > External tools. The metadata pane is populated. I can still run queries and return results etc.

> If these error are repeatable can you hold down the shift key while starting DAX Studio - this should generate a diagnostic log file if you could then attach this log file to this issue on github it might give me some hint as to what is going on.

It's quite random, but I will try to do this.

Thank you for your help on this.

**Comment by tarmacx** [comment] 2020-12-04 13:05
@CaveofW0nders  I get a similar issue but I noticed recently that using the "Refresh Metadata" button would restore the intellisens functionnality. Maybe you can use that in the meantime.

**Comment by CaveofW0nders** [comment] 2020-12-04 15:21
> @CaveofW0nders I get a similar issue but I noticed recently that using the "Refresh Metadata" button would restore the intellisens functionnality. Maybe you can use that in the meantime.

Hey tarmacx, thanks for the suggestion, unfortunately, this didn't work for me. Opening a new tab seems to do the trick for now.

**Comment by jburns7744** [comment] 2020-12-31 12:46
Hey Team - this is an issue for my entire consulting firm which uses DAX Studio on the regular.  It's annoying of course to us folks, but we also are so grateful to have a free tool that performs as well as this one.  Thanks to Darren and SQLBI for developing this - even with no intellisense it would be a treat!

**Comment by dgosbell** [comment] 2021-01-18 11:50
This should be fixed in the 2.14 release which was just published

**Closed by dgosbell** 2021-01-18 11:50 UTC
Labels: bug
