### ISSUE TITLE
Error getting PowerBI/SSDT

### ISSUE THREAD

**Issue by ThimiosSp** [DaxStudio/DaxStudio#247] opened 2019-11-13 19:52 UTC
First installation of DAX Studio and I get an error when trying to connect to open PBI:
Error getting PowerBI/SSDT instances: One or more errors occurred.
Any ideas?

**Comment by dgosbell** [comment] 2019-11-13 20:42
Can you follow the steps [here](https://daxstudio.org/documentation/troubleshooting/logging-settings/) to turn on the debug logging. Then re-try connecting to PBI, then shutdown DAX Studio and upload the log file here?

**Comment by ThimiosSp** [comment] 2019-11-17 08:31
Forgive my delay but I was using DAX on my pc in the meanwhile. On my laptop though, the issue is that when I use SHIFT, DAX crashes... Manual enabling never works... I'll try to remove and re-install and come back to you.

**Comment by ThimiosSp** [comment] 2019-11-17 08:53
Removed, re-installed. Still crashes when left SHIFT is used.
Manually enabled diagnostic but still no logs are produced. Below is the config section:
 <appSettings>
    
        <add key="serilog:using:RollingFile" value="Serilog.Sinks.RollingFile" />
		<add key="serilog:minimum-level" value="Verbose" />    
		<add key="serilog:write-to:RollingFile.minimumLevel" value="Verbose" />
		<add key="serilog:write-to:RollingFile.pathFormat" value="C:\Program Files\DaxStudio\Log\DaxStudio-{Date}.txt" />
		<add key="serilog:write-to:RollingFile.retainedFileCountLimit" value="10" />
    <add key="ClientSettingsProvider.ServiceUri" value="" />
  </appSettings>
  <runtime>

Any ideas?

**Comment by ThimiosSp** [comment] 2019-11-17 08:55
Removed, re-installed. Still crashes when left SHIFT is used.
Manually enabled diagnostic but still no logs are produced. Attached the changed config section.
Any ideas?
[DaxStudio.exe.config_new.txt](https://github.com/DaxStudio/DaxStudio/files/3855399/DaxStudio.exe.config_new.txt)

**Comment by dgosbell** [comment] 2019-11-17 10:57
Did you put in the ```c:\program files\``` path? I can't think of anything in our code base that would do that. This is most likely what is causing the crash as the logging system will get an access denied error. The default log location is in your user profile, but any user write-able folder should work (maybe try using ```c:\temp```).

**Comment by ThimiosSp** [comment] 2019-11-17 11:26
Now I got it... Here you are:
[DaxStudio-20191117.txt](https://github.com/DaxStudio/DaxStudio/files/3855513/DaxStudio-20191117.txt)

**Comment by dgosbell** [comment] 2019-11-17 21:49
I can't reproduce this and I've double checked a number of different scenarios, but I never get this error. Unfortunately this type of error never says which object is not set.

Does this happen with all Power BI files or just one? 

Now that the logging is working can you try starting up with the Shift key held down (this won't fix the issue, but it should capture more detail in the lead up to the error)

**Comment by ThimiosSp** [comment] 2019-11-19 21:59
This happens with other Power BI files as well.
Shift key causes Power BI to crash. I'm attaching both a screenshot and the new log file.
[DaxStudio-20191119.txt](https://github.com/DaxStudio/DaxStudio/files/3866261/DaxStudio-20191119.txt)
![Crash](https://user-images.githubusercontent.com/57087340/69190192-8b300980-0b28-11ea-92d4-f3be77f68a27.png)

**Comment by dgosbell** [comment] 2019-11-20 01:50
The crash and the failure to find Power BI instances appear to be related. Both these features are calling into a Windows subsystem called WMI ( Windows Management Instrumentation).

Can you open a Powershell window on your machine and try and run the following commands:
```
Get-WmiObject -query "SELECT * FROM Win32_OperatingSystem"
```

```
Get-WmiObject -query "SELECT ProcessId, ParentProcessId FROM Win32_Process"
```
Do you get an error or do they both produce output?

These are roughly equivalent to the calls that are failing in DAX Studio. I don't know why this would happen. In theory this is the same information that you can see in Task Manager so you should not need any special permissions and should work on Windows 7 or later. I can add code to ignore the error in the diagnostic logging, but we need to find the parent processId for the PowerBI detection to work properly.

**Comment by ThimiosSp** [comment] 2019-11-20 09:17
I'm afraid that both produce an error. Pls see attached.
![PowerShell](https://user-images.githubusercontent.com/57087340/69225627-5ef7a580-0b87-11ea-9512-303e4aeeaa54.png)

**Comment by dgosbell** [comment] 2019-11-20 11:12
OK, so that means that it's not a problem with DAX Studio specifically - you have an issue on your PC as these commands work fine on all the systems I have tested. You could try some of the suggestions on the following post to repair WMI [https://www.lansweeper.com/knowledgebase/how-to-repair-a-corrupt-wmi-installation/](https://www.lansweeper.com/knowledgebase/how-to-repair-a-corrupt-wmi-installation/) 

I have just checked in some changes which will be part of the next version which will ignore any WMI issues when starting the diagnostic logging and when looking for Power BI or SSDT instances. But this means that if WMI is broken on a machine - that we can't tell whether we are connected to SSDT or PowerBI and we won't be able to show the file names for PowerBI.

**Closed** 2019-12-19 21:29 UTC
Labels: more information needed
