### ISSUE TITLE
2.11.0 Sticks Quite a Bit when Loading

### ISSUE THREAD

**Issue by jburns7744** [DaxStudio/DaxStudio#353] opened 2020-06-15 13:41 UTC
Hey DAX Studio Team - thanks again for maintaining this great tool - what a blessing! 

Noticed on 2.11.0 that the software often freezes and sticks on the loading, sometimes for 2-4 minutes.  The same thing happens if the application gets unused for a half-hour or so, and then I return to it.  Something it looks like is getting stuck.  Posting in case anyone else has noticed, perhaps this is an issue with my cache or something.

**Comment by dgosbell** [comment] 2020-06-15 22:27
I'm not currently aware of any significant or frequent freezing issues.

Did you notice this in versions prior to 2.11.0 or is this new behaviour?

When you say "sticks on loading" is this when you first start DAX Studio or after you click "Connect" to connect to a data source?

What sort of data source are you connected to? (eg Power BI Desktop, SSAS, Azure AS, Power BI XMLA endpoint, etc)

If this happens frequently for you are you able to start DAX Studio with the diagnostic logging switched on (see [https://daxstudio.org/documentation/troubleshooting/logging-settings/](https://daxstudio.org/documentation/troubleshooting/logging-settings/) ) either by using the shift key if it happens frequently or by changing the settings in the config file. Then after you see a freeze like this take note of the date and time, then close DAX Studio and post the date and time of the issue along with the latest log file back to this issue so that we can try and get an idea of what was going on at the time.

**Comment by rpertusalopez** [comment] 2020-06-16 07:38
exactly the same behaviour here Darren.
It takes 3-5 minutes to connect to our Azure Analysis Services, and if I leave the tool and come back half an hour later, gets frozen and takes another 5 minutes to be able to click anywhere. 
It all started in this version.

I will enable the diagnostic logging and let you know.

**Comment by jburns7744** [comment] 2020-06-16 19:16
@dgosbell Hi Darren, this is brand new behavior in 2.11.0.  I'm a heavy user of the tool for ~2 years and have never noticed this before.  The issue starts when we click Connect.  We are hitting Azure AS almost exclusively.   I'll try to do the diagnostic and post back here.

**Comment by dgosbell** [comment] 2020-06-17 04:42
I can't think of any major changes to the loading of the metadata. We have updated to a later version of the Microsoft AdomdClient libraries, so it could be an issue with them. And Azure AS is constantly being updated so it could also be an issue there...

In theory the time to load the metadata should be a function of the number of tables, columns and measures. But even the one of the largest models I have (nearly 400 columns and over 11,000 measures) only takes about 8 seconds to load.

Could you try with the previous version and see if that is still faster than the 2.11.0 release? If you don't want to uninstall/reinstall you could use the following
[Portable copy of v2.10.2](https://1drv.ms/u/s!AnSKp2UbblSYgdwwgoUpsTBxnXT-Tw?e=6dW2lR) you just unzip to a folder then double click on the DaxStudio.exe file.

The issue with connections timing out seems to be specific to Azure AS, it seems to have much more aggressive flushing of idle sessions. I can see about fixing this but I need more information on the error on any errors or warnings or a copy of the diagnostic logging. 

@jburns7744 - the default logging only captures errors and warnings, I really need the debug level logging that you can enable using the instructions in the link I posted previously. Those log messages are not directly related to metadata refresh. And DaxStudioChecker is only useful in situations where DAX Studio does not startup at all (and those scenarios are increasingly rare now)

**Comment by jburns7744** [comment] 2020-06-17 13:10
Morning Darren,

Good news - I booted up a good Azure VM and tested DAX Studio against the same Azure AS instance - and basically no problems here.  Looks like the issue is somehow on my machine.  Which makes sense that you've only heard from two of us on this issue since it really is a bit of a show-stopper.  Thanks so much for your attention to this and providing a link to v2.10.2 in case we need it.  I am guessing this issue on my main machine will just disappear after a while with various updates.

Thanks you sir.

**Comment by dgosbell** [comment] 2020-06-18 03:27
@jburns7744  that is interesting, thanks for letting me know. I'm assuming that an Azure VM would simplify the network route. So maybe the issue is related to a VPN, firewall, proxy or something like that which is between your work machine and Azure AS. It certainly is sounding like this might be related to factors external to DAX Studio.

@rpertusalopez did you have any luck capturing the diagnostic logs, that might give some hints. I can see one call to connection.open() that could potentially "stick" if the network was really slow, but pretty much everything else should be refreshing on a background thread.

**Comment by jburns7744** [comment] 2020-06-22 13:34
@dgosbell looks like the issue is gone with 2.11.1.  Not sure what the update was, but noticed significant improvement after downloading it on the original machine.  No remaining issues for me.  Thanks for much for your attention to this!

**Comment by dgosbell** [comment] 2020-06-22 23:28
@jburns7744 cool, thanks for letting us know. There was not really any specific code change for this issue between 2.11.0 and 2.11.1, but I did update to a later version of the Microsoft provider and I noticed that they have gone from v18.x to v19.x so this could have been an issue in the provider.

Since this issue appears to have resolved itself I'm going to close this issue

**Closed by dgosbell** 2020-06-22 23:28 UTC
