### ISSUE TITLE
Ver 2.9.4 /Vertipaq Analyzer

### ISSUE THREAD

**Issue by Amdisilword** [DaxStudio/DaxStudio#242] opened 2019-11-03 19:49 UTC
**Describe the bug**
Options/Advanced,  Marked, choose “ShowExport ….”
Connect to PBIx file
Advanced/View Metrics. Click one time on it
Can see it run Analyzing Metrix . The tab aren’t created. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dgosbell** [comment] 2019-11-03 21:50
This sounds like a duplicate of #235 so I might close this issue and use the existing issue to track this fault. Could you possibly download and test with the [preview release of 2.9.5](https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/28512060/artifacts)? Or if you had a pbix which triggers this issue which you could share that would be great. This issue seems to be somehow related to specific models the preview release will hopefully log the error message. So if you get an error from that version let us know what is says so that we can then fix it.

**Closed by dgosbell** 2019-11-03 21:50 UTC
Labels: duplicate
