### ISSUE TITLE
There is an error when DAX Studio connecting to PowerPivot

### ISSUE THREAD

**Issue by vikkeni** [DaxStudio/DaxStudio#884] opened 2022-08-05 07:34 UTC
Hello,  I have a problem using DAX studio recently,I can't connect PowerPivot with DAX studio.Before then,there was OK.
The error message is **Connection timed out or lost**,I've tried many times,The same error occurred on another computer，but it's OK when DAX Studio connecting Power bi desktop.
I don't know whether the Excel or DAX Studio is wrong.IS it a general problem?
My Excel version is **2208  beta** (Microsoft 365 business application Edition )
I don't know how to solve the problem. So,I've come specially to ask for your help.
I hope to get your reply！

I past a screenshot about the error
![image](https://user-images.githubusercontent.com/110656495/183018166-1e3cd34b-c68b-45cb-afc3-7b23846402ab.png)

**Comment by dgosbell** [comment] 2022-08-05 07:39
This seems to possibly be due to some change in the beta version of Excel. There have been other reports of issues with the 2208 build of Excel in issue #865 but I do not have access to the Beta version of Excel to confirm. Can you try on a computer with the normal release of Excel?

**Comment by vikkeni** [comment] 2022-08-05 08:02
thank you!
I've tested it on my colleague's computer,there was no error.
May be it Caused by the beta version

**Comment by tre4b** [comment] 2022-08-24 09:21
I came here looking for help with the same issue.  I've tried as much as I can but there is no info in the messages to help me debug the issue.   Initially the file was stored in onedrive.  I have moved it to my desktop but this did not change the issue.   I am trying to connnect to the data model in excel, and am using the plugin to open dax explorer.

Message is the same as the above (minus the hanzi)

**Comment by vikkeni** [comment] 2022-08-29 03:09
How do you tell Microsoft about this issue?

**Comment by dgosbell** [comment] 2022-08-29 03:54
> How do you tell Microsoft about this issue?

@vikkeni - I'm already in email contact with one of the Excel engineers and he is trying to help me figure this out.

**Comment by dgosbell** [comment] 2022-08-29 03:58
> I've tried as much as I can but there is no info in the messages to help me debug the issue.

@tre4b - Power Pivot was never designed to allow access from external tools, so I have to jump through a number of complicated hoops to get it working at all. I had to use internal undocumented APIs, so there was always a risk of something like this happening. I think the error messages seem a bit cryptic as the API calls were not designed to be used by external callers. 

I am very appreciative of the offer of assistance from the Excel team, but we still have not isolated the root cause yet. And it's tricky with time zones as our working hours do not overlap much. They have not deliberately changed anything to block DAX Studio, but there have been some upgrades to PowerPivot which have possibly contributed to this problem.

**Comment by vikkeni** [comment] 2022-08-29 05:14
> 
Okey ,thank you!

**Comment by marcosqlbi** [comment] 2022-08-29 06:54
@dgosbell I'm able to reproduce the issue on a PC with Version 2209 (Build 15619.20000 Click-to-Run) Beta Channel.
I tried yesterday on a Current channel build (2208) and it works there.
I'd say that there is something in the AddIn that doesn't work well, but I'm not sure about how to debug. Contact me by email if there is some specific test I could do.
![image](https://user-images.githubusercontent.com/13840816/187141059-0f79e6fc-f508-4097-b6f6-a5ec9446d787.png)

**Comment by lyliuyouyang** [comment] 2022-09-03 08:56
> @dgosbell我能够在具有版本 2209（内部版本 15619.20000 即点即用）测试版频道的电脑上重现此问题。我昨天在当前频道版本（2208）上尝试过，它在那里工作。我会说AddIn中有一些东西不能很好地工作，但我不确定如何调试。如果我可以做一些特定的测试，请通过电子邮件与我联系。 ![图像](https://user-images.githubusercontent.com/13840816/187141059-0f79e6fc-f508-4097-b6f6-a5ec9446d787.png)

please close #921 ,i watch this #884 now and found that is the same problem

**Comment by bfarrer** [comment] 2022-09-14 18:03
I'm running into a similar issue as described - I get a pop-up error specifically stating "Problem during AssemblyResolve in DAX Studio". The rest of the pop-up notification is attached. I've also attached my specific log.

I'm running Excel Version 2112 (Build 14729.20322).

![image](https://user-images.githubusercontent.com/47905408/190228071-bf6e3aea-193b-443c-96f2-4e3fd725da31.png)
![image](https://user-images.githubusercontent.com/47905408/190229073-133a48e5-2b21-4276-af57-138cfb4d0f4e.png)

**Comment by dgosbell** [comment] 2022-09-14 23:19
This is due to an issue in Excel. I have not been able to find any way to fix this from the DAX Studio side. But DAX Studio is also using 2 undocumented, internal API calls so it is not the Excel team's fault since this is not something they would test for. 

I have been in contact with people on the Excel team and it looks like we have found the root cause, but there is still some more testing that is required and I'm not sure yet what the timeline for getting this deployed will be.

**Comment by bfarrer** [comment] 2022-09-19 13:35
> 

Thanks @dgosbell - will this be an update to DAX Studio or Excel? If the latter, I can't imagine my company getting around to pushing an update through for my case. As you saw, we are already running a few versions behind.

**Comment by dgosbell** [comment] 2022-09-19 21:59
@bfarrer as I mentioned above it's an Excel issue. I've tried everything I can think of to work around it, but I'm a bit limited as Excel addins run in a separate security sandbox. The good news is that the existing DAX Studio addin should just start working again once the fix goes through its internal review process and the fix gets pushed out.

**Comment by Icey898** [comment] 2022-12-07 16:51
Good morning, I would like to know if this is still opened and valid. I understand that the error is caused by a change from Microsoft in the beta version but I would like know if anyone have any updates whatsoever on this issue. Personally I am still experiencing the problem.

**Comment by tmorris431** [comment] 2022-12-07 16:58
I cannot connect with Power BI.

**Comment by dgosbell** [comment] 2022-12-07 21:19
@Icey898 - Yes this issue is still open. Microsoft has a fix on the way, there have just been some delays getting it published.

**Comment by dgosbell** [comment] 2022-12-07 21:20
> I cannot connect with Power BI.

@tmorris431 - I don't think this is related to the Power Pivot issue. It would be better to open a new issue or a discussion and let me know what error / behaviour you are seeing and whether you are trying to connect to Power BI Desktop or the XMLA endpoint.

**Comment by tmorris431** [comment] 2022-12-08 12:46
> > I cannot connect with Power BI.
> 
> @tmorris431 - I don't think this is related to the Power Pivot issue. It would be better to open a new issue or a discussion and let me know what error / behaviour you are seeing and whether you are trying to connect to Power BI Desktop or the XMLA endpoint.

@dgosbell - Thank you. Please disregard. It is working now.

**Comment by LeoEsZe** [comment] 2023-01-01 14:47
Has anyone found a solution?

**Comment by LeoEsZe** [comment] 2023-01-01 15:33
> Como mencioné anteriormente, es un asunto de Excel. Intió todo lo que me me para hacer a trabajar a su alrededor, pero estoy poco limitado a a medida que los addins de Excel corren en una caja de arena de seguridad separada. La buena noticia es que el actual addin de DAX Studio debería empezar a trabajar de nuevo una vez que la solución pasa por su proceso de revisión interna y la solución se expulsa.

Is there any news?

**Comment by dgosbell** [comment] 2023-01-01 22:09
@LeoEsZe - no news yet, still waiting.

**Comment by z98abdi** [comment] 2023-01-08 16:48
is there any way to solve the problem of connecting from DAX Studio to New version of Excel?

**Comment by dgosbell** [comment] 2023-01-08 21:51
@z98abdi - no this is a bug in Excel. We are waiting for Microsoft to push out an update.

**Comment by dgosbell** [comment] 2023-02-24 09:08
Apparently, Microsoft has fixed this in the February update for Excel. So if you are seeing the following version or later under File > Account any existing versions of DAX Studio should start working with Power Pivot again. 

![image](https://user-images.githubusercontent.com/8241830/221137874-0041177e-df18-404d-9486-cd0d0ffd4149.png)

This is working on my machine. Is anyone else on this thread able to confirm that this version fixes the issue for them also?

**Comment by marcosqlbi** [comment] 2023-02-24 09:14
On my PC it doesn't work, but I have a different build:
![image](https://user-images.githubusercontent.com/13840816/221139439-ad77cf20-df53-4353-8c12-410c53ce5b27.png)

**Comment by dgosbell** [comment] 2023-02-24 10:31
@marcosqlbi - it's not a special build, but it looks like it is slightly ahead of the public release. It must be that later build number that is needed :(

**Comment by abdou151** [comment] 2023-02-24 11:22
It's currently working in my PC. it wasn't working previously. Here's my build:
![image](https://user-images.githubusercontent.com/14995345/221167025-ed4d1ecd-1d90-4abd-9fbd-d59aebedc381.png)

**Comment by Icey898** [comment] 2023-02-25 01:31
Hello, I can confirm that it is now connecting to the data model for the first time since august 2022 for me. My build is 2303 (16216.20004).

On thing is that I still cannot seem to start anything like All Queries or Server Timing here is the error
<img width="548" alt="20230224_Error_Trace" src="https://user-images.githubusercontent.com/120044055/221328700-90364e3d-86c8-4c84-a622-61c45a6f1fca.png">

**Comment by marcosqlbi** [comment] 2023-03-15 07:58
Good news, it works with version 2303 in Current Channel (Preview).
![image](https://user-images.githubusercontent.com/13840816/225243988-16e18ef7-7123-4d2d-80d5-c073bebadd91.png)

**Comment by dgosbell** [comment] 2023-04-19 03:20
Closing this issue as Microsoft appear to have fixed this in the 2303 build

**Closed by dgosbell** 2023-04-19 03:20 UTC
Labels: bug

**Comment by github-oken** [comment] 2023-05-18 08:20
![image](https://github.com/DaxStudio/DaxStudio/assets/10453181/9a78355b-f91d-4440-a31b-9b6cf49ebedc)

I still have this issue with Excel and Dax Studio. I think the issue is back with this build.

**Comment by dgosbell** [comment] 2023-05-19 03:45
@github-oken I cannot reproduce this issue on Version 2305 and I'm pretty sure it was working for me when I was on 2304.

When you say the issue is back are you getting the connection timeout error? Have you checked the log files https://daxstudio.org/docs/troubleshooting/logging-settings/ and do you see the same assembly load errors?
