### ISSUE TITLE
Color profiles crash dax studio with windows 10

### ISSUE THREAD

**Issue by OpenKartat** [DaxStudio/DaxStudio#779] opened 2021-12-17 06:36 UTC
Dax Studio wont't start if you have take some custom color profiles with Windows. I tried with version 2.15.0, 2.16 and 2.17.3.

After I disable windows color profiles, dax studio started normally. After error that, i coudn't, unfortinatly, replicate the error.

**Comment by dgosbell** [comment] 2021-12-18 03:43
Thanks for logging this. But without steps to reproduce this or a diagnostics log from when the error occurred there is no way to know what this issue is or how to fix it. I just tried changing the color profile on one of my systems and DAX Studio continues to run fine. If you cannot reproduce this issue either then there is no way to figure out now if it was the color profile or some other related issue. 

Since neither of us can repeat this crash I'm going to close this issue. There is nothing I do directly in DAX Studio to reference color profiles, although it could be some .net framework issue...

**Closed by dgosbell** 2021-12-18 03:43 UTC
