### ISSUE TITLE
Website front page download count cookie bug?

### ISSUE THREAD

**Issue by DaniilMaslyuk** [DaxStudio/DaxStudio#756] opened 2021-11-15 04:24 UTC
**Describe the bug**
Apparently some cookies mess up the download counter

**To Reproduce**
1. Go to daxstudio.org
2. Note the download count (in my GIF below it's 450)
3. Repeat steps 1 and 2 in Incognito mode (now I see 105)

**Expected behavior**
The download count should be the same

**Screenshots**
![DownloadCount (1)](https://user-images.githubusercontent.com/10683126/141722354-860af86f-c89c-4c0a-9a98-c539b314457b.gif)

**Additional context**
Feel free to close if not important

**Comment by dgosbell** [comment] 2021-11-15 06:57
I think what you are seeing is by design. I do cache the download count in a cookie for a few hours to avoid hitting the github API too hard. So if you open the home page in different browsers or in incognito mode I do expect that the counts might be different.

**Comment by dgosbell** [comment] 2022-08-30 04:07
closing this as by design. I deliberately cache the download counts for 24hrs to avoid hitting the github apis too frequently

**Closed by dgosbell** 2022-08-30 04:07 UTC
