### ISSUE TITLE
Getting an error when exporting PBI data to Azure SQL Server

### ISSUE THREAD

**Issue by vardges-16** [DaxStudio/DaxStudio#1035] opened 2023-01-25 20:32 UTC
I have a huge json file and haven't found a quicker way of parsing and exporting the data to Azure SQL DB other than parsing it using Power BI, connecting using Dax Studio, and exporting data to Azure SQL tables.

It worked before, however, I am getting the following error now:
"ExecuteNonQuery requires an open and available Connection. The connection's current state is closed".

Any idea why is this happening?

**Comment by dgosbell** [comment] 2023-01-26 05:30
It sounds like your connection to SQL Azure got interrupted. Can you start DAX Studio with the diagnostic logging enabled (see https://daxstudio.org/docs/troubleshooting/logging-settings/ ) then reproduce this error, then close DAX Studio and upload the log file to this issue on GitHub?

**Comment by vardges-16** [comment] 2023-01-26 20:43
Thank you for your reply, but after rerunning the parsing in power bi Dax studio was able to export the data.
If the issue happens again I'll post the log here.

**Comment by dgosbell** [comment] 2023-01-30 04:52
OK, I might close this issue for the time being since it looks like it was a point in time issue with the connection to Azure SQL. Possibly even re-running the export would have worked, but if you do capture a log file I'd definitely be interested to have a further look at this.

**Closed by dgosbell** 2023-01-30 04:52 UTC
