### ISSUE TITLE
DAX Studio > Advanced > View Metrics not working

### ISSUE THREAD

**Issue by swapnil-tamboli** [DaxStudio/DaxStudio#944] opened 2022-09-16 08:46 UTC
In DAX studio, when I click on Advanced > View Metrics. I get below error, please suggest:

Error viewing metrics: The specified column was not found in the context at line 8, column 5.

**Comment by dgosbell** [comment] 2022-09-16 10:26
this is a duplicate of #926 so I'm going to close this issue as I am tracking this bug there. We have a fix for this that will be part of the next release.

**Closed by dgosbell** 2022-09-16 10:26 UTC
