### ISSUE TITLE
A different IntelliSense tooltip appears if the function name is preceded by {

### ISSUE THREAD

**Issue by Kenneth-Barber** [DaxStudio/DaxStudio#1045] opened 2023-02-07 01:39 UTC
**Describe the bug**
If you type { followed immediately by a function name and then (, the IntelliSense tooltip that appears is very different than the one that would appear if you did not have the preceding {.

To be more specific, the tooltip in the former case is yellow, lacks a shadow, lacks the function description, has "{function" instead of the syntax information, and has a DAX Guide link in the format "https://dax.guide/{function" instead of the usual "https://dax.guide/FUNCTION".

Queries of the format EVALUATE {FUNCTION()} are common for evaluating scalar values during development, so this bug is not exactly an edge case.

**Screenshots**

When the function name is immediately preceded by {
![EVALUATE {VALUE(}](https://user-images.githubusercontent.com/17665493/217123404-f3ce3474-02c0-41cd-8f8e-bd1ee249bb13.png)

When the function name is not immediately preceded by {
![EVALUATE { VALUE(}](https://user-images.githubusercontent.com/17665493/217123409-58095399-a21d-4e6d-a38f-f522a21d2770.png)

The terminating } is not required to reproduce the bug. The VALUE function is used in this example, but the bug applies to any function.

**Comment by dgosbell** [comment] 2023-02-10 06:32
Thanks for logging this. It had me confused for a little bit as I could not reproduce it when running in debug mode, then I realised that I had found this a few months ago and fixed it already. So this will be fixed when the next release goes out.

**Closed** 2023-02-10 06:37 UTC
Labels: bug, fix-checked-in
