### ISSUE TITLE
Second run of Server Timings does not update the statistics

### ISSUE THREAD

**Issue by mark-endicott** [DaxStudio/DaxStudio#1299] opened 2024-08-27 16:02 UTC
DAX Studio v3.1.0.1028
Connection: PowerBIService - 16.0.144.19

When running the Server Timings against a data model held on the Power BI service, the first run produces the statistics and the associated SE Queries, but the 2nd run completes but does not update the statistics to reflect the new results, and the only two queries shown are for the ExecutionMetrics, rather than SE queries. 

## Steps to Reproduce
1. Run DAX query with Server timings enabled. 
2. Run DAX query again

**Comment by mark-endicott** [comment] 2024-08-27 16:04
![image](https://github.com/user-attachments/assets/c65151ec-c69f-40eb-ab02-9082a442429b)

**Comment by dgosbell** [comment] 2024-08-27 22:41
This was caused by a combination of auto-clearcache and the new Execution Metrics event support and was fixed in the 3.2 release.

**Closed by dgosbell** 2024-08-27 22:41 UTC
Labels: triage

**Comment by mark-endicott** [comment] 2024-08-28 08:49
@dgosbell - Thanks, I hadn't realised there was a new version!
