### ISSUE TITLE
Excel Add-in "Access Denied"

### ISSUE THREAD

**Issue by TedSkomsky** [DaxStudio/DaxStudio#489] opened 2020-12-26 15:35 UTC
**Describe the bug**
When I try to open the DAX Studio Add-In in Excel I get "Access Denied" error.   

- Error is only in the Excel Add-In, DAX Studio will open on it's own or through Power BI Desktop.
- This is a new computer and  new install of Microsoft 365 and DAX Studio
- DAX Studio version is 2.13.1
- Excel Version is 2011 (Build 13426.20332)

![image](https://user-images.githubusercontent.com/76535892/103154086-4c28aa80-4763-11eb-9c4c-4ef8041ebfae.png)

**To Reproduce**
1. From Excel with file already open, go to "Add-Ins"
2. Double click on  'DAX Studio'
3. See error described above

**Expected behavior**
DAX Studio is expected to open.

**Screenshots**
attached above.

**Additional context**

- I have uninstalled DAX Studio, and reinstalled 
- I have rebooted the computer
- I have run "Quick Repair" on Microsoft 365
- -- none of these steps has resolved the issue.

**Comment by dgosbell** [comment] 2020-12-27 00:39
Thanks for logging this, however it's not something I've seen before

The Excel Addin button does not require a double-click. Try single clicking and see if that fixes the issue.

Otherwise try holding down the shift key while starting up Excel (making sure that any Excel windows are closed first) to enable the [diagnostic logging](https://daxstudio.org/documentation/troubleshooting/logging-settings/). Then reproduce the issue that triggers this error and then shutdown Excel. This should generate a DaxStudioExcel-yyyymmdd.log file. If you then upload the log file with the latest timestamp to this issue on Github it might help me figure out what the issue is.

**Comment by TedSkomsky** [comment] 2020-12-27 01:26
Thank you for the reply.    

Single click on the Excel Add-In button did not resolve the issue.

The log file you requested is attached.   
[DaxStudioExcel-.log](https://github.com/DaxStudio/DaxStudio/files/5743969/DaxStudioExcel-.log)

**Comment by dgosbell** [comment] 2020-12-27 03:42
Hmmm, there is not much else in the log other than the access denied. Do you have a 3rd party anti-virus program that could be blocking the launch of DAX Studio? Can you try looking in the Windows Event Viewer and see if there are any hints in there of something on your machine that might be causing this. I can't reproduce this issue and it's the first time this has been reported as an issue.

**Comment by ArdieTrinidad** [comment] 2021-01-20 18:16
I have the same issue. It is working before but suddenly I am receiving the same error message while running the add-ins in excel.

![image](https://user-images.githubusercontent.com/77747624/105217225-05b14a80-5b6d-11eb-8b27-c896f4fa9a60.png)

**Comment by dgosbell** [comment] 2021-01-20 22:19
This is very strange. I still have no ideas at to what could be blocking this. 

Did you install DAX Studio using the **All Users** or **Current User** option?

As a test can you try running Excel as Admin and see if that behaves differently? (search for Excel in the start menu then right click and choose **Run as Administrator**)

**Comment by TedSkomsky** [comment] 2021-01-23 22:19
Our IT group is still looking at this but we do know it is related to "Real-time Protection" of our anti-virus software (proven by a test with real-time protection temporally turned off).  

The problem is only with Excel, DAX Studio loaded through Power BI Desktop has not had a problem loading.

**Comment by ArdieTrinidad** [comment] 2021-01-24 05:10
> This is very strange. I still have no ideas at to what could be blocking this.
> 
> Did you install DAX Studio using the **All Users** or **Current User** option?
> 
> As a test can you try running Excel as Admin and see if that behaves differently? (search for Excel in the start menu then right click and choose **Run as Administrator**)

We have tried all of it but no success. Error still persist.

**Comment by ArdieTrinidad** [comment] 2021-01-24 05:11
> Our IT group is still looking at this but we do know it is related to "Real-time Protection" of our anti-virus software (proven by a test with real-time protection temporally turned off).
> 
> The problem is only with Excel, DAX Studio loaded through Power BI Desktop has not had a problem loading.

Was it working already by turning off your anti-virus?

Yes. Ours also not working just on excel and there is no problem connecting to Power BI.

**Comment by dgosbell** [comment] 2021-01-24 10:01
@ArdieTrinidad  I'd love to help with this, but I'm pretty confident that this is something specific to your particular environment. It's either an overly aggressive AV like @TedSkomsky or it something else like some group policy restrictions. We do not set or alter any permissions when we install DAX Studio. It basically copies the files to the selected folder, sets a couple of registry keys to register the Excel addin and another key to register the .dax file type and that is it. And the Power BI External Tools and the DAX Studio Excel addin are launching the same program so it;'s possible that there is a policy that trusts software published by Microsoft more than other publishers, but that is not something I can affect or override, you will probably need to work with your IT dept to solve this.

**Comment by TedSkomsky** [comment] 2021-03-07 01:31
Our IT department has resolved this by adjusting the anti-virus policy.  This has resolved the issue in my case. DAX Studio now opens without error.

**Comment by dgosbell** [comment] 2021-06-11 09:21
Closing as it appears to have been related to the AV policy

**Closed by dgosbell** 2021-06-11 09:21 UTC
Labels: awaiting reply, more information needed
