### ISSUE TITLE
after installing version 3.06 : error: The connection cannot be used while an XmlReader object is open.

### ISSUE THREAD

**Issue by fbouckae-crm** [DaxStudio/DaxStudio#1076] opened 2023-03-14 10:34 UTC
Connecting to Azure Analysis Services.
open a DAX query (worked well on 3.05)
able to select database.
when running the query  i get error
**The connection cannot be used while an XmlReader object is open.**

tried connecting to other database.
simplified the query

no success.

**Comment by fbouckae-crm** [comment] 2023-03-14 10:38
removed 3.06 and reïnstalled 3.05.
now query works again

**Comment by marcosqlbi** [comment] 2023-03-14 14:30
Please, can you clarify whether the query runs correctly if you try to connect to the database again? (click Connect and reconnect to the database). It seems you did from your first message, but I want to be sure.

**Comment by fbouckae-crm** [comment] 2023-03-14 15:28
even restarted DAXstudio to be sure.  reconnected and ran the query on 2 different databases

**Comment by marcosqlbi** [comment] 2023-03-14 15:40
I'm not able to reproduce the issue. @dgosbell can you try that too?

**Comment by fbouckae-crm** [comment] 2023-03-14 19:36
Recap.
I installed 3.06 over 3.05. A query that worked on 3.05 did produce the above error on 3.06.
Restarted dax studio and retried without success.
Removed 3.06 and installed 3.05.
Retried the query and then it worked again. 

I can give it a try with completely removing 3.05 and installing 3.06.

I'll let you know the outcome tomorrow

**Comment by dgosbell** [comment] 2023-03-14 22:07
No, I cannot reproduce this issue either. We've had one other report of something similar here #983 but I think that was against v3.0.5 we never got any response to our follow up questions so I was not able to isolate a root cause.

@fbouckae-crm could you enable the diagnostic logging using the steps outlined here https://daxstudio.org/docs/troubleshooting/logging-settings/ then reproduce this error, then close DAX Studio and upload the log file to this issue?

**Comment by fbouckae-crm** [comment] 2023-03-15 07:14
reinstalled 3.06 over 3.05
started DAX studio with logging,
same issue
see attached log
[DaxStudio-20230315.log](https://github.com/DaxStudio/DaxStudio/files/10976917/DaxStudio-20230315.log)

**Comment by fbouckae-crm** [comment] 2023-03-15 07:26
removed DAX studio completely and reinstalled 3.06.
enabled verbose logging.
[DaxStudio-20230315.log](https://github.com/DaxStudio/DaxStudio/files/10977011/DaxStudio-20230315.log)

**Comment by martinhgrosse** [comment] 2023-03-16 10:05
+1 on this exact issue - it worked fine for a few hours, but then kept disconnecting from DB, saying: **The Connection cannot be used while an XmlReader object is open.**

@fbouckae-crm I would just follow your advice to uninstall, then grab 3.05 again - sad. I was so excited about the new visualisations on Query Plan/Server Timings! That is just super amazing!

![image](https://user-images.githubusercontent.com/70598068/225583600-acf4975e-de73-4c16-8c5a-dc6cff60126d.png)

**Comment by marcosqlbi** [comment] 2023-03-16 10:54
@martinhgrosse can you identify an action that triggers the issue? for @fbouckae-crm it seems happening all the time, whereas you are describing a situation that happens only sometimes.

**Comment by dgosbell** [comment] 2023-03-17 06:47
@fbouckae-crm your issue looks like maybe it's a race condition between the query and metadata population. There was a minor change in one of the methods in the call stack in the log that you posted to improve the detection of formatstrings in the data model. I can _kind of_ reproduce your issue occasionally if I connect to a slower data source like AAS **and** click refresh metadata and hit F5 at almost the same time. So my guess at the moment is that possibly with a more complex data model and different network connections (ie going through corporate firewalls and proxies) - that this could manifest itself more frequently.

I've got a preview build with a slightly different implementation of the problematic call which I think improves this (at least bringing it back in line more with the 3.0.5 behaviour)
https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/46527124/artifacts

Could you possibly test this (even using just the portable version) and see if it fixes this for you?

@martinhgrosse - even though it has a similar error your issue probably has a different cause. If you are able to reproduce it consistently could you capture a diagnostic log as described here https://daxstudio.org/docs/troubleshooting/logging-settings/  and post it back here?

**Comment by fbouckae-crm** [comment] 2023-03-17 07:48
Hi Darren,

I tried the preview build, and it works, I'll try to  test it further today, and let you know when there are issues.
thanks
Filip

P.S. sometimes after cancelling a long running query (had this also in 3.05) It gives an error when running a query subsequently. but the error disappears after reconnecting to the database.

**Comment by dgosbell** [comment] 2023-03-18 01:28
@martinhgrosse and @jerudamaja - are you able to go into Help > About then open the log file folder and check one of the log files on a date when this issue occurred? If you can find a log file with this error can you upload it to this issue on Github?

The default log will not capture the same amount of events as the debug level logging, but it should have captured the error events and if we can confirm that your instances of this error has a call to the same function that I've fixed in the 3.0.7 preview then there is a good chance that the same fix will work. At the moment I don't know if the root cause is the same.

**Comment by martinhgrosse** [comment] 2023-03-23 17:16
@dgosbell I grabbed the 3.0.7 version you provided a link for and I can no longer replicate my problem. Thanks for that!
@marcosqlbi I am sorry I couldn't respond sooner. in the end it was indeed every query, that produced the error; I will try to provide the error logs next time.
DAX Studio is an amazing design helper - thanks for your work on this!

**Comment by alazyworkaholic** [comment] 2023-03-28 13:57
+1 affected on 3.0.6.893 I have a complex model + complex network connection and any query always fails.
![image](https://user-images.githubusercontent.com/31052043/228260299-7b4b38e1-51c3-4ca7-88a3-4fb02b593106.png)
[DaxStudio-20230328.log](https://github.com/DaxStudio/DaxStudio/files/11090255/DaxStudio-20230328.log)

**Comment by marcosqlbi** [comment] 2023-03-28 13:59
@alazyworkaholic can you try preview of version 3.0.7 (see link from dgosbell two weeks ago in this thread).

**Comment by alazyworkaholic** [comment] 2023-03-29 14:43
My queries work in both 3.0.5 and 3.0.7 preview.

**Comment by marcosqlbi** [comment] 2023-03-29 14:55
Ok so the problem should be already fixed and will be included in the next release.

**Comment by markf7962** [comment] 2023-04-10 07:48
I have the same issue as the original poster, but it only occurs when executing against an AAS model. Same query against Power BI Prem Cap does not have the issue.

**Comment by Robin-Everaars** [comment] 2023-04-11 11:55
If it's of any help: Had the same issue today with 3.0.6, even though I could use it for some time without issues. The organisation I'm working at does do regular network changes. 3.0.7 works without issues!

**Comment by dgosbell** [comment] 2023-04-19 00:33
This issue should be fixed in the 3.0.7 release.

**Closed by dgosbell** 2023-04-19 00:33 UTC
Labels: bug
