### ISSUE TITLE
Spelling mistakes in DAX Studio

### ISSUE THREAD

**Issue by Kenneth-Barber** [DaxStudio/DaxStudio#1025] opened 2023-01-16 18:57 UTC
Here is a list of spelling mistakes in DAX Studio:

- If you right-click on DaxStudio.exe and go to Properties → Details tab → File description, it says "Dax Studio", but it should be "DAX Studio"
- If I pin DaxStudio.exe to the Taskbar and hover over the icon while DAX Studio is closed, it says "Dax Studio", but it should be "DAX Studio"
- In the "Connect" window that appears after you open DAX Studio, "PowerPivot" should be "Power Pivot"
- In the Help tab, "About DaxStudio" should be "About DAX Studio"
- In the Help tab, if you hover over any of the buttons in the Issues group, "Github" should be "GitHub"
- Under Help tab → About DaxStudio → Credits, "VertipaqAnalyzer" should be "VertiPaq Analyzer"
- In Advanced tab → View As, "Ok" should be "OK". The paragraph is also worded strangely and is missing ending punctuation on the 2nd sentence. Consider using something like this instead: "You can test one or more roles directly or impersonate another user to test all of their roles simultaneously.".

I'm sure that there are many more spelling mistakes along these lines (i.e. relaxed capitalization and casual omission of spaces). Take a good look through DAX Studio to ensure that all of the spelling is correct. Similar spelling mistakes are everywhere throughout the [documentation](https://daxstudio.org/docs/intro/).

**Comment by dgosbell** [comment] 2023-01-18 04:47
Thanks for logging this. I think I have fixes almost all of these plus a few others which I found. The only one that might be an issue is this one:

> * If I pin DaxStudio.exe to the Taskbar and hover over the icon while DAX Studio is closed, it says "Dax Studio", but it should be "DAX Studio"

How have you installed DAX Studio? If you used the installer it should already work this way. 

If you used the portable install then I don't think this is possible to fix since the way you fix this is to write out registry keys for the application and the portable version does not write anything to the registry by design.

**Comment by Kenneth-Barber** [comment] 2023-01-18 10:22
I am using the portable version. Since the portable version doesn't write to the registry, where is it getting "Dax Studio" from? How is this impossible to fix?

**Comment by dgosbell** [comment] 2023-01-20 02:02
> How is this impossible to fix?
So it's not _impossible_ to fix, the simplest fix is to use the installer. But not knowing the answer to "where is it getting "Dax Studio" from?" makes it really hard to fix this for the portable version.

**Comment by dgosbell** [comment] 2023-01-31 05:23
>  where is it getting "Dax Studio" from

@Kenneth-Barber  So it appears that Windows initially reads this from the Description property of the .exe file (which will be fixed in the next release) - however Windows caches this somewhere so changes to this property after the .exe file has been pinned once are not picked up. If you rename the .exe or put it in a different folder the updated description is used.

**Comment by Kenneth-Barber** [comment] 2023-01-31 06:49
@dgosbell Thanks for looking into that.

Also, I noticed another spelling mistake:
- In Advanced → View Metrics → VertiPaq Analyzer → Tables → Temperature column, in the tooltip, "feequency" should be "frequency"

**Closed** 2023-03-14 00:03 UTC
Labels: bug, fix-checked-in
