### ISSUE TITLE
Issue with PowerPivot and 2.14.1

### ISSUE THREAD

**Issue by 59Peter** [DaxStudio/DaxStudio#533] opened 2021-01-29 19:42 UTC
**Describe the bug**
After successfully launching connection from an Excel PowerPivot model, Unable to start trace for "All queries"
It's also impossible to start "server timings"

**Comment by dgosbell** [comment] 2021-01-29 23:33
Duplicate of #514 - thanks for reporting this. This issue is fixed in the source code and I will be pushing out a new release shortly. I see that the person that logged #514 actually closed it before I've published the new version so it was not obvious that this was a duplicate issue. I'm mainly pointing this out as there is a link to a pre-release build that you could try if you like.

**Comment by SharmaAntriksh** [comment] 2021-01-31 11:29
@dgosbell Sorry I didn't realize I am supposed to keep the issue open :) I am pretty new to GitHub! Do you want me to open it back?

**Comment by dgosbell** [comment] 2021-03-29 02:00
This should be fixed in v2.15 which was just released

**Closed by dgosbell** 2021-03-29 02:00 UTC
Labels: bug, fix-checked-in
