### ISSUE TITLE
Bug on closing DAX Studio

### ISSUE THREAD

**Issue by SharmaAntriksh** [DaxStudio/DaxStudio#925] opened 2022-09-06 14:55 UTC
DAX Studio throws an error upon performing the exact steps shown below

https://user-images.githubusercontent.com/73054674/188667579-47636566-7c47-4d9b-9ecb-81063fd80393.mp4

If you don't go to the results pane and close DS then there is no bug.

**Comment by dgosbell** [comment] 2022-09-08 00:23
Sorry but this appears to be a timing issue. I've tried doing the exact same thing as in your video and cannot reproduce this issue. I have added some extra error checking around one of the tasks that runs at shutdown, but unfortunately, it's not clear what is triggering this.

**Comment by dgosbell** [comment] 2022-09-22 02:54
I'm not sure if this is fixed in the 3.0.1 release, but I've added some improved error handling around the shutdown process. Can you install 3.0.1 and let me know if you are you still getting this crash?

**Comment by dgosbell** [comment] 2022-10-24 03:47
Assuming 3.0.1 fixed this.

**Closed by dgosbell** 2022-10-24 03:47 UTC
Labels: awaiting reply
