### ISSUE TITLE
No connection with PowerPivot (Method Not Found ReadAsAsync)

### ISSUE THREAD

**Issue by Romain452001** [DaxStudio/DaxStudio#229] opened 2019-10-15 11:06 UTC
Hello,
When I tried to connect DAX Studio with Excel PowerPivot, it doesn't work.
I have this error message : 

"Method Not Found: 'System. Threading.Task '1<!!0> System.Net.Http.HttpContentExtensions.ReasAsAsync(System.Net.Http.HttpContent)'

Could you help me please ? 

Thank you,

Best regards,

**Comment by Romain452001** [comment] 2019-10-15 11:10
<img width="512" alt="Error Message" src="https://user-images.githubusercontent.com/56562746/66826588-12e49000-ef4d-11e9-9a6b-75a434c66191.PNG">

**Comment by dgosbell** [comment] 2019-10-15 22:23
Hi @Romain452001 - when you go into Help > About in DAX Studio and click on "Show Details" what version of System.Net.Http.Formatting do you see?

![image](https://user-images.githubusercontent.com/8241830/66874336-87bfd480-eff6-11e9-926d-c98e729b9064.png)

**Comment by Romain452001** [comment] 2019-10-16 09:18
Hello @dgosbell,
Thank you for your help. 
I have the same value.

<img width="475" alt="Version" src="https://user-images.githubusercontent.com/56562746/66905731-b34abb00-f006-11e9-8df3-12c91082f6e7.PNG">

**Comment by dgosbell** [comment] 2019-10-16 23:13
hmm, that's the dll that contains the "missing" method so I had been wondering if somehow a different version had been picked up or if this dll was not detected on your machine as I don't see this issue on my machine. I'll have to do some more investigation and see if I can spot any other potential causes.

**Comment by dgosbell** [comment] 2019-10-24 22:45
I'm still not sure what's causing this as I can't get it to happen on my machine. Did you upgrade from a previous version of DAX Studio? Do you remember if the installer had to install an update for the .Net Framework? If so have you re-booted since this was done? If that doesn't help could you try doing an uninstall / re-install?

**Comment by WiTorLo** [comment] 2019-10-28 07:56
Hi,
Installing previous version solved this issue for me: "DAX Studio 2.9.2 Size: 5.98Mb | Date: 25 Jun 2019" from https://daxstudio.org/downloads/
Must be a bug in September update of Dax Studio.

**Comment by Romain452001** [comment] 2019-10-28 08:22
Hello @dgosbell, hello @WiTorLo 
Thank you for your message and the time you take to help me. 
I will try with an previous version and i come back to you.

Thank you,
Best regards, 
Romain

**Comment by Romain452001** [comment] 2019-10-30 09:02
Hello @dgosbell , hello @WiTorLo 
So i Tried with a previous version 2.9.2 and it works !!!
Thank you for your help !
Thanks again

**Comment by edpowerbizz** [comment] 2019-11-06 14:44
Hi,

I got the same error message.
Is there a way to solve this without downloading older version?

Thanks

**Comment by dgosbell** [comment] 2019-11-07 03:20
I'd love to fix this, but unfortunately I don't currently know what triggers this. The current version works fine on all the machines that I have access to. The only real difference between the 2.9.2 version and 2.9.4 was an update to one of the Microsoft libraries. I'm actually wondering now if this might be some installer/upgrade issue. 

Would it be possible to zip up your ```c:\program files\Dax Studio``` folder and post it back to this issue so that I can have a look at what was installed? 

Or you could try doing a full uninstall then a re-install of 2.9.4

Or you could try downloading and installing the latest preview build from [here](https://ci.appveyor.com/project/DarrenGosbell/daxstudio/build/artifacts) where I've rolled back the Microsoft libraries to the older version we used in 2.9.2

**Comment by dgosbell** [comment] 2019-11-12 22:12
@Romain452001 @WiTorLo @edpowerbizz - So I still cannot reproduce this issue on any of the machines I have access to and the error message itself is not enough as I can see that the method is not missing in the library we are using.

I've suggested trying a full uninstall/re-install of v2.9.4 can someone confirm if they've tried that and if it made any difference? (making sure that there are no files left in ``c:\program files\Dax Studio``` after the uninstall.)

I've tried rolling back the Microsoft library we are using for the "ReadAsAsync" call to the version we were using in 2.9.2 so the new preview build [here](https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/28649169/artifacts) might fix this - can someone check this and let me know? (although the library we are currently using works for me so I'm not sure if this will do anything)

**Comment by dgosbell** [comment] 2019-11-18 19:49
Are any of you using Excel 2010? If so the solution I suggested on #245 might be worth checking?

**Comment by veganEarth** [comment] 2019-11-28 01:09
I received the same error. I had to revert to version 2.9.2 to use Dax Studio.

**Comment by dgosbell** [comment] 2019-12-20 03:24
I've tried rolling back the Microsoft library we are using for ReadAsAsync in the 2.10 release which I just published so please give that a try and see if it has any effect on this issue

**Comment by dgosbell** [comment] 2020-01-20 23:50
Because I cannot reproduce this issue I do not know if the attempted fix in the 2.10.x releases has had any impact on this issue. So due to the lack of any further feedback I'm going to close this issue. If you are still having issues with the 2.10.2 release or later feel free to open a new issue.

**Closed by dgosbell** 2020-01-20 23:50 UTC
Labels: awaiting reply, more information needed
