### ISSUE TITLE
DAX Studio column table and size don't work with new Desktop PBI version

### ISSUE THREAD

**Issue by davidfombella** [DaxStudio/DaxStudio#305] opened 2020-04-05 11:13 UTC
Using Power BI desktop march 2020
**Versión: 2.79.5768.721 64-bit (marzo de 2020)**

And DAX studio 2.10.2

[https://exceleratorbi.com.au/table-size-from-power-bi-desktop/](https://exceleratorbi.com.au/table-size-from-power-bi-desktop/)

DMV query doesn't work

_SELECT dimension_name AS tablename,
attribute_name AS columnname,
datatype,(dictionary_size/1024) AS size_kb
FROM $system.discover_storage_table_columns
WHERE dictionary_size > 0_

**Comment by marcosqlbi** [comment] 2020-04-05 11:18
A better way to get table size is using VertiPaq Analyzer, which is integrated in DAX Studio:
https://www.sqlbi.com/blog/marco/2019/09/15/vertipaq-analyzer-2-0-preview-1/

Also check you imported data, if you use DirectQuery you cannot see table size.

**Comment by davidfombella** [comment] 2020-04-05 11:21
Using import of course. Will check vertipaq analyzer thanks

**Comment by dgosbell** [comment] 2020-04-05 12:20
What do you mean by "doesn't work"? Are you getting an error message? If so what does is the text of that error message?

**Comment by davidfombella** [comment] 2020-04-05 12:44
Hi @dgosbell  I run the query with no outputs in below area. 
I execute/run query with no outputs on below results area

**Comment by davidfombella** [comment] 2020-04-05 12:57
![gggggggggggggggg](https://user-images.githubusercontent.com/2682459/78498903-b7ea6380-774d-11ea-9ae1-c2b07ec2d6bc.PNG)
 Hitting run , no outputs...I am experiencing it is only with this file that doesn't include datavisualizations.
How to avoid multiple localedate tables?

**Comment by dgosbell** [comment] 2020-04-05 23:40
> Now works looks random..

It should not be random. I've tried a number of times against different versions of PBI Desktop and SSAS and it worked every time. But the Vertipaq Analyzer feature Marco linked to is a much simpler way of getting the size information now.

> How to avoid multiple localedate tables?

Go into options in Power BI Desktop and under "Data Load" (either globally or for the current file) you can turn off the Auto date/time option (note that you could break some visuals if you are using the auto date time fields anywhere)

**Comment by dgosbell** [comment] 2020-04-09 12:35
Closing this as we are unable to reproduce this issue

**Closed by dgosbell** 2020-04-09 12:35 UTC
