### ISSUE TITLE
report "PerTypeValues'1" ERROR when results export type set as static

### ISSUE THREAD

**Issue by renyusen168** [DaxStudio/DaxStudio#912] opened 2022-08-30 01:58 UTC
DAX Studio v3.0.0.725
Connection: AnalysisServices - 14.0.213.1

## Steps to Reproduce
1.set results as static
2.run
3.log shows :"PerTypeValues'1"的类型初始值设定项引发异常

**Comment by dgosbell** [comment] 2022-08-30 04:01
Thanks for reporting this. I'm going to close this particular issue as it is a duplicate of #891 and I'm tracking this bug there. I've identified the issue and it should be fixed soon.

**Closed by dgosbell** 2022-08-30 04:01 UTC
