### ISSUE TITLE
Timeouts for Trace when Selecting Server Timings

### ISSUE THREAD

**Issue by DaveStabilify** [DaxStudio/DaxStudio#668] opened 2021-07-08 15:53 UTC
DAX Studio v2.16.1.615
Connection: PowerBIDesktop - 15.1.92.26

## Summary of Issue
Unable to use Server Timings - "Timeout exceeded attempting to start Trace."

## Steps to Reproduce
1. Open External Tools from PBI Desktop
2. Select Server Timings
3. Increased timeout setting to 60 seconds - same problem.
**The issue does not occur in the release build here https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/39828643/artifacts
**

**Comment by dgosbell** [comment] 2021-07-09 00:21
Thanks for logging this. I'm going to close this issue as it is a duplicate of #664 and I'm already tracking this problem against that issue.  And as you have noted I have a preview build of 2.16.2 where this appears to be fixed. 

The only outstanding issue is that there are some scenarios where 2.16.1 does not timeout which is why this problem was not picked up early so I'm trying to double check 2.16.2 across all possible data sources and connection types to make sure there are not any other hidden issues

**Closed by dgosbell** 2021-07-09 00:21 UTC
Labels: bug, duplicate
