### ISSUE TITLE
Issue - Getting Error: Server sent an unrecognizable response

### ISSUE THREAD

**Issue by martijnreurslag** [DaxStudio/DaxStudio#465] opened 2020-11-19 18:31 UTC
Hello,

Sporadically getting the error “Server sent an unrecognizable response & Cannot access closed stream” for some reason, have attached the DAX Studio Log File (Debug Logging Enabled) that captured the raised exception. 

Now when rerunning the same DAX statement it executes without issues and shows the results. Not fully sure if this is an issue in DAX Studio or connection related, have not yet been able to reproduce the same in SSMS. Articles I found on this talk about either invalid/control characters or large XMLA response size but as it executes fine on the retry it doesn't seem to be related. 

It does seem to happen only for statements that scan larger datasets but the result-set is relative small (as visible in the screen capture). Here it is twice the same statement, first it executed fine and then got the exception was raised. Note that the connection is to an AAS database.
 
Any idea what is causing this? Let me know if more details are needed for this

![image](https://user-images.githubusercontent.com/71427745/99707833-49200780-2a9d-11eb-9ee1-ae9dff5edd0d.png)

[DaxStudio-20201119_001.log](https://github.com/DaxStudio/DaxStudio/files/5568812/DaxStudio-20201119_001.log)

**Comment by dgosbell** [comment] 2020-11-27 08:52
Thanks for reporting this. The log file was really helpful. I have not been able to reproduce this issue myself. But I'm pretty sure I know what the root cause is and I should be able to include a fix in the next release.

**Comment by tarmacx** [comment] 2020-12-04 16:08
@dgosbell  as requested in the #429 here is my log
[DaxStudio-20201204 - Copie.log](https://github.com/DaxStudio/DaxStudio/files/5643875/DaxStudio-20201204.-.Copie.log)
There you go.
I tried 3 times. It failed really quickly this time.

**Comment by dgosbell** [comment] 2020-12-04 20:57
Thanks @tarmacx from the log this looks to be triggered by the same root cause so the fix for the issue here should hopefully correct this. 

This is not actually time related, it's an issue when you click or alt-tab away from DAX Studio during a long running operation then click back. I added a check to see if the connection is still open, but in some circumstances this interferes with the current query.

**Comment by dgosbell** [comment] 2021-01-18 11:49
This should be fixed in the 2.14 release which was just published

**Closed by dgosbell** 2021-01-18 11:49 UTC
Labels: bug, fix-checked-in
