### ISSUE TITLE
Regression bug from #199?

### ISSUE THREAD

**Issue by Oxenskiold-DAX** [DaxStudio/DaxStudio#262] opened 2019-12-11 17:35 UTC
This may be a regression bug from #199 

When you double click on a column in the Metadata tree – without pressing the shift key at the same time - the column reference is inserted into the editor, however, the Metadata tree still has focus – not the editor. This means that when you try entering something after the double click nothing happens in the editor because - as mentioned - the Metadata tree still has focus. I think it used to be so that the editor received focus after the double click hence the title of this issue.

Pressing the shift key while double-clicking works perfectly as specified in #199  and in this case the editor subsequently has focus. (Thanks for implementing this btw).

**Comment by dgosbell** [comment] 2019-12-12 03:47
I don't believe this is a regression. If I override the double click (like I do when the shift key is down) I can set the focus to the editor. If I let the default double click event happen it "steals" the focus back after my code runs. I'm not sure if there is a simple fix for this.

I'm kind of leaning towards just making the "shift-doubleclick" behaviour the default since people can always click on the arrows to expand and collapse the columns. Then the focus will stay where I put it.

**Comment by dgosbell** [comment] 2022-08-30 04:14
Doing some clean up on old issues. This should no longer be an issue in the new v3 UI

**Closed by dgosbell** 2022-08-30 04:14 UTC
