### ISSUE TITLE
The Connection either timed out or was lost

### ISSUE THREAD

**Issue by Ephezius** [DaxStudio/DaxStudio#429] opened 2020-09-11 17:12 UTC
**Describe the bug**
Every time we launch DAX Studio (from Power BI Desktop), we have approximately 5 minutes or exactly one run before it disconnects from the model.  This is a live model that lives in Azure (tabular)

**To Reproduce**
1. Go to Power BI Desktop (opening our file that uses our Live Connection)
2. Click on DAX Studio under the External Tools tab; click the user name to login
3. Paste a query, or write one and run
4. Attempt to run again
5. Error generated

**Expected behavior**
Disconnections happen to us all day long.  We are continuously closing DAX Studio and reopening it.  We would like it to maintain the connection, or at least prompt for login.

**Screenshots**

**Additional context**

**Comment by dgosbell** [comment] 2020-09-12 03:47
This looks like a duplicate of #356. I don't do any regular work with Azure AS and I don't see this sort of issue at all. It appears that Azure AS may have more aggressive session timeouts, but this sort of thing can also be affected by operations like scaling out or data refresh operations.

I have already spent a few hours this week working on a possible solution for this but there are a number of complex interactions to deal with and I'm now thinking of taking a step back and building it into the architecture differently. I would like to get this working seamlessly so that DAX Studio will automatically re-connect and continue to perform the selected action even if the connection was dropped by the server. 

> We are continuously closing DAX Studio and reopening it

You don't need to close DAX Studio, you can just click on the connect button in the tool bar
![image](https://user-images.githubusercontent.com/8241830/92983610-ce100300-f4e7-11ea-82e5-f215fafbbb3a.png)

You might then need to open the advanced options and re-select your current database or re-select the appropriate database in the metadata pane once the connection is re-established. But this should let you continue to work with your query.

**Comment by dgosbell** [comment] 2020-10-20 21:56
Please try using the 2.13 release. I've added functionality to automatically re-connect if the server drops the connection.

**Comment by Ephezius** [comment] 2020-10-21 19:04
Thanks so much. We’ll give it a shot!

**Comment by tarmacx** [comment] 2020-12-04 12:54
I've got similar problems with my connection to powerbi service. I  use Microsoft Account credentials to connect to powerbi://app.powerbi.com/... and I can't run queries that returns a large amount of data without receiving the same error as you. I will try to investiguate if it is just a coincidence that I get the error during does tables or if I reach the 5 min mark as you suggested. (did that with latest 2.13 version)

**Comment by tarmacx** [comment] 2020-12-04 12:59
![image](https://user-images.githubusercontent.com/13239306/101166592-8a202c00-3606-11eb-94bc-b7fcca9088cc.png)
It's a shorter timeout than that... @dgosbell do you think it's different and that should submit another issue or it's related ?

**Comment by dgosbell** [comment] 2020-12-04 13:59
@tarmacx actually I think your errors could possibly be another form of the issue in #465 and a fix for that is coming in the next release. If you are able to start DAX Studio with the shift key held down so that the [diagnostic logging](https://daxstudio.org/documentation/troubleshooting/logging-settings/) is enabled and then reproduce this issue and upload the log file here I could confirm if my suspicions are correct.

**Comment by dgosbell** [comment] 2021-01-18 12:01
This should be fixed in the 2.14 release which was just published

**Closed by dgosbell** 2021-01-18 12:01 UTC
Labels: awaiting reply
