### ISSUE TITLE
Unable to connect to Power BI PPU instance

### ISSUE THREAD

**Issue by rminder** [DaxStudio/DaxStudio#669] opened 2021-07-09 18:56 UTC
I am using DAX Studio 2.16.1. I am attempting to connect to my Power BI PPU instance (see the first image). I am getting an error shown in the second image.

First, it doesn't appear the DAX Studio is recognizing this as a PPU instance, which it is. Secondly, it's asking for an initial catalog and I don't even know what that is referring to.

Thank you.

![Image](https://user-images.githubusercontent.com/20615192/125124148-a537aa80-e0c5-11eb-8c5b-7116697afad2.png)
![Image1](https://user-images.githubusercontent.com/20615192/125124150-a5d04100-e0c5-11eb-813d-ba6ba293daf5.png)

**Comment by dgosbell** [comment] 2021-07-10 01:33
Thanks for logging this. I'm not exactly sure what the issue is as I test against a PPU instance regularly to make sure the XMLA endpoint connections function properly with any new features I add. 

I did wonder if the & in the workspace name was causing an issue, but I created a new workspace with a similar name to yours and it worked fine. Do you have any data sets published to that workspace?

The initial catalog is the term the Microsoft driver uses for the dataset. So it's basically asking what dataset should it connect to. You can specify this in the advance options (1) by selecting it from the dropdown (2) but this should not be necessary, if you have one or more datasets published to that workspace DAX Studio should just pick the first from the list and then you can change that later if you want using the dropdown at the top of the metadata pane.

![image](https://user-images.githubusercontent.com/8241830/125147967-5bf16480-e172-11eb-8dc2-6fe223b90f92.png)

When you open the dropdown for the initial catalog do you see any datasets available there?

**Comment by rminder** [comment] 2021-07-10 10:45
Hi Darin - I tried this again and here is exactly what I am doing:

- I load DAX Studio and enter the address of my Power BI PPU instance into the Tabular Server Connect box
- I click Connect
- I get a Microsoft **Sign in to your account** dialog box. I select the correct account.
- I get the errors I included in my first email. 

Note, if I start DAX Studio, enter my Power BI PPU instance and then attempt to click the Initial Catalog dropdown, before connecting, I get prompted to enter my credentials by Microsoft, I immediately get an error saying "Error refreshing database list for Initial Catalog: Initial catalog property is required in order to connect to Power BI Pro workspaces."

This error doesn't even make any sense. I need to enter an initial catalog before I can see a list of catalogs???

Yes I do have a dataset in the workspace I am attempting to connect to and 3 dataflows. 

Thanks - Randy

**Comment by rminder** [comment] 2021-07-10 10:51
Hi Darin - I think I solved my issue. I have both a Power BI Pro license and Power BI PPU license. The workspace was set to use my Pro license. When I switched this over to PPU, DAX Studio was able to connect. Perhaps the error message could be changed to make it clearer what the problem might be?

I noticed however that DAX Studio doesn't see my dataflows, just my datasets. Should I be able to see dataflows?

**Comment by dgosbell** [comment] 2021-07-10 12:02
> Perhaps the error message could be changed to make it clearer what the problem might be?

This error is coming from the Microsoft data provider so I cannot really change it. I might mention it to some of the contacts I have a Microsoft though as it seems like strange wording for this error.

But I'm also thinking of possibly extending the connection dialog at some point in the future so that it can provide a list of workspaces. At that point I would have more information that just an address string and could limit the selection to just premium or PPU workspaces.

> Should I be able to see dataflows?

No you should not see dataflows, you cannot run DAX directly against a dataflow. You can only connect to datasets with DAX Studio. If you want to query a dataflow using DAX you will need to load it into a dataset first. 

Since you found the solution for this issue I'm going to close it.

**Closed by dgosbell** 2021-07-10 12:02 UTC

**Comment by rminder** [comment] 2021-07-10 12:41
Thank you Darren!
