### ISSUE TITLE
new install all works except Excel add-in

### ISSUE THREAD

**Issue by davidcwhitney** [DaxStudio/DaxStudio#961] opened 2022-09-23 21:43 UTC
I got a new job and talked the boss into letting me install DAX Studio.  I connect to a hosted virtual machine, which is where we installed for all users.  Note I am the only user on this VM.  Everything is peachy except I get an error trying to launch DAX Studio from the icon on the Excel Add-Ins ribbon.

OS Name	Microsoft Windows 10 Enterprise
Version	10.0.19044 Build 19044
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	xxxxxxx
System Manufacturer	VMware, Inc.
System Model	VMware7,1
System Type	x64-based PC
System SKU	
Processor	Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz, 2597 Mhz, 2 Core(s), 2 Logical Processor(s)

Excel 2016 16.0.5332.1 32-bit

Here is the first error:
Dax Studio
Problem during AssemblyResolve in Dax Studio
For Assembly Microsoft.Excel.Amo, Version=11.0.0.0, Culture=neutral,
PublicKeyToken=89845dcd8080cc91 :
Error loading AMO from " - Value cannot be null.
Parameter name: assemblyFile
at
DaxStudio.ExcelAddin.Xmla.ExcelAmoWrapper.get_ExcelAmoAssembly[]
at
DaxStudio.ExcelAddin.ThisAddln.currentDomain_AssemblyResolveiObje
ct sender, ResolveEventArgs args]

Click OK and another comes up with the same message.  Click OK and observe the log:
16:29:02 Establishing Connection
16:29:43 The following error occurred while updating the connection: The connection either timed out or was lost.
16:31:02 Error Connecting: The remote server returned an error: [500) Internal Server Error.

Do not be concerned about the duration.  I believe the log recorded the time I clicked on OK so there was some intentional delay.

Thanks.

**Comment by dgosbell** [comment] 2022-09-23 21:50
This is a duplicate of #884 there is nothing I can do as it's an Excel issue. The team has a fix which is going through internal approvals now. Please follow the earlier issue for updates

**Closed by dgosbell** 2022-09-23 21:50 UTC
