### ISSUE TITLE
DAX STUDIO CONNECTION ISSUE - WIN 10 

### ISSUE THREAD

**Issue by marc-dejong** [DaxStudio/DaxStudio#932] opened 2022-09-10 18:45 UTC
DAX Studio v3.0.0.725
Connection: not connected

## Steps to Reproduce
1.
2.
[DAX_STUDIO_ERROR_2022-09-10_13-41-32.pdf](https://github.com/DaxStudio/DaxStudio/files/9541195/DAX_STUDIO_ERROR_2022-09-10_13-41-32.pdf)

**Comment by dgosbell** [comment] 2022-09-10 23:04
This is a duplicate of #884 so I'm going to close this as I'm tracking the errors with connecting to PowerPivot there.

The Excel team has changed something in the Power Pivot engine. I'm using internal undocumented api calls to connect so this is not really their fault, but I'm working with a couple of the Excel engineers to see if we can find a fix.

**Closed by dgosbell** 2022-09-10 23:04 UTC
